package integration

import (
	"context"
	"testing"
	"time"

	"connectrpc.com/connect"
	dbuuid "github.com/nvcnvn/tech-office/backend/database/dbuuid"
	rpcv1 "github.com/nvcnvn/tech-office/backend/rpc/v1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRitualTasksImprovementLazyResources covers the lazy creation of chat channels and
// description documents for ritual instance tasks.
//
// Before this feature: every generated ritual instance had a channel and doc created at
// generation time, wasting resources for instances that may never be opened.
// After this feature: channel and doc are created on first user interaction (get task detail).
func TestRitualTasksImprovementLazyResources(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Lazy Resource Project", uniqueProjectKey("LZRC"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	_ = w.createRitualDefinition(owner, proj.ID, "Daily Check", dailyRecurrenceRule())
	w.generateRitualInstances(owner)

	tasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	require.NotEmpty(t, tasks, "expected ritual instances to be generated")

	t.Run("when a ritual instance is generated by the scheduler", func(t *testing.T) {
		task := tasks[0]

		t.Run("it has no chat channel (lazy — not yet created)", func(t *testing.T) {
			// FR-001: System MUST NOT create a chat channel when generating an instance.
			assert.Empty(t, task.ChannelId,
				"ritual instance should have no channel until first user interaction")
		})

		t.Run("it has no description document (lazy — not yet created)", func(t *testing.T) {
			// FR-002: System MUST NOT create a description document when generating an instance.
			assert.Empty(t, task.DescriptionDocumentId,
				"ritual instance should have no description doc until first user interaction")
		})
	})

	t.Run("when a user opens a ritual instance detail view", func(t *testing.T) {
		task := tasks[1]
		// GetTask triggers EnsureTaskResources for ritual instances.
		fetched := w.getTask(owner, task.Id)

		// FR-003: System MUST create channel when user first accesses the detail view.
		t.Run("the task now has a chat channel created on demand", func(t *testing.T) {
			assert.NotEmpty(t, fetched.ChannelId,
				"first GetTask should trigger lazy channel creation")
		})

		// FR-003: System MUST create description doc when user first accesses detail view.
		t.Run("the task now has a description document created on demand", func(t *testing.T) {
			assert.NotEmpty(t, fetched.DescriptionDocumentId,
				"first GetTask should trigger lazy description doc creation")
		})

		// FR-005: Lazy resource creation MUST be idempotent.
		t.Run("subsequent GetTask calls return the same channel and document", func(t *testing.T) {
			fetchedAgain := w.getTask(owner, task.Id)
			assert.Equal(t, fetched.ChannelId, fetchedAgain.ChannelId,
				"channel ID must be stable across repeated GetTask calls")
			assert.Equal(t, fetched.DescriptionDocumentId, fetchedAgain.DescriptionDocumentId,
				"description doc ID must be stable across repeated GetTask calls")
		})
	})

	t.Run("when a standard task is created", func(t *testing.T) {
		standardProj := w.createProject(owner, "Standard Task Project", uniqueProjectKey("STLZ"))
		level0 := levelByDepth(standardProj.Levels, 0)
		require.NotNil(t, level0)
		standardTask := w.createTask(owner, standardProj.ID, "Standard Task", level0.Id)

		// FR-006: Standard tasks MUST continue to create channels eagerly.
		t.Run("it still has a channel created eagerly (no behavior change)", func(t *testing.T) {
			assert.NotEmpty(t, standardTask.ChannelId,
				"standard tasks should still get a channel at creation time")
		})

		// FR-006: Standard tasks MUST continue to create docs eagerly.
		t.Run("it still has a description document created eagerly (no behavior change)", func(t *testing.T) {
			assert.NotEmpty(t, standardTask.DescriptionDocumentId,
				"standard tasks should still get a description doc at creation time")
		})
	})
}

// TestRitualTasksImprovementConcurrentAccess verifies that concurrent GetTask calls
// for the same uninitialized ritual instance do not produce duplicate channels or documents.
func TestRitualTasksImprovementConcurrentAccess(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	emp := w.withEmployee()
	proj := w.createProjectWithMode(owner, "Concurrent Access Project", uniqueProjectKey("CONC"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	w.addProjectMember(owner, proj.ID, emp.ID, rpcv1.ProjectMemberRole_PROJECT_MEMBER_ROLE_MEMBER)
	_ = w.createRitualDefinition(owner, proj.ID, "Concurrent Ritual", dailyRecurrenceRule())
	w.generateRitualInstances(owner)

	tasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	require.NotEmpty(t, tasks)
	taskID := tasks[0].Id

	// Both callers trigger EnsureTaskResources; only one should create resources.
	t.Run("when two users open the same ritual instance simultaneously", func(t *testing.T) {
		taskFromOwner := w.getTask(owner, taskID)
		taskFromEmp := w.getTask(emp, taskID)

		// FR-005: Idempotent — concurrent requests produce exactly one channel.
		t.Run("both see the same channel ID (no duplicate channel created)", func(t *testing.T) {
			assert.NotEmpty(t, taskFromOwner.ChannelId)
			assert.Equal(t, taskFromOwner.ChannelId, taskFromEmp.ChannelId,
				"concurrent callers must see the same channel — no duplicate created")
		})

		// FR-005: Idempotent — concurrent requests produce exactly one document.
		t.Run("both see the same document ID (no duplicate document created)", func(t *testing.T) {
			assert.NotEmpty(t, taskFromOwner.DescriptionDocumentId)
			assert.Equal(t, taskFromOwner.DescriptionDocumentId, taskFromEmp.DescriptionDocumentId,
				"concurrent callers must see the same doc — no duplicate created")
		})
	})
}

// TestRitualTasksImprovementScheduleChangeImpact verifies the preview endpoint that
// returns impact counts before a schedule change is applied.
func TestRitualTasksImprovementScheduleChangeImpact(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Impact Preview Project", uniqueProjectKey("IMPC"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Daily Check", dailyRecurrenceRule())
	w.generateRitualInstances(owner)

	t.Run("when querying impact of changing daily to weekly", func(t *testing.T) {
		impact := w.getScheduleChangeImpact(owner, def.Id, weeklyRecurrenceRule())

		// FR-013: Impact preview must include count of instances to be removed.
		t.Run("it returns the count of future untouched instances to be removed", func(t *testing.T) {
			assert.Greater(t, impact.InstancesToRemove, int32(0),
				"daily ritual should have multiple future untouched instances")
		})

		// FR-013: Impact preview must include count of instances to be kept as standalone.
		t.Run("it returns the count of instances that would be detached", func(t *testing.T) {
			// Initially all are untouched, so touched count should be 0.
			assert.Equal(t, int32(0), impact.InstancesToDetach,
				"no instances have been touched yet, so detach count should be 0")
		})

		// FR-013: Impact preview must include count of new instances to be created.
		t.Run("it returns an estimate of new instances to be created", func(t *testing.T) {
			assert.Greater(t, impact.InstancesToCreate, int32(0),
				"new weekly instances should be estimated")
		})
	})

	t.Run("when one future instance becomes touched (user opens its detail)", func(t *testing.T) {
		tasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
		require.NotEmpty(t, tasks)
		w.getTask(owner, tasks[0].Id) // triggers lazy resource creation → task becomes "touched"
		impact := w.getScheduleChangeImpact(owner, def.Id, weeklyRecurrenceRule())

		t.Run("the detach count increases by 1 for the now-touched instance", func(t *testing.T) {
			assert.Equal(t, int32(1), impact.InstancesToDetach,
				"one instance was touched (channel created), so detach count should be 1")
		})

		t.Run("the remove count decreases by 1 correspondingly", func(t *testing.T) {
			// Total = untouched + touched; touched one moved from remove → detach bucket.
			assert.GreaterOrEqual(t, impact.InstancesToRemove, int32(0))
		})
	})
}

// TestRitualTasksImprovementScheduleChangeUntouched verifies that a schedule change
// correctly soft-deletes future untouched instances.
func TestRitualTasksImprovementScheduleChangeUntouched(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Untouched Cleanup Project", uniqueProjectKey("UNTC"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Daily Safety", dailyRecurrenceRule())
	w.generateRitualInstances(owner)
	beforeTasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	require.NotEmpty(t, beforeTasks, "need existing ritual instances to test cleanup")

	t.Run("when the schedule changes and all future instances are untouched", func(t *testing.T) {
		result := w.changeRitualDefinitionSchedule(owner, def.Id, weeklyRecurrenceRule())

		// FR-007: All future untouched instances are soft-deleted.
		t.Run("the returned instances_removed count matches untouched future count", func(t *testing.T) {
			assert.Greater(t, result.InstancesRemoved, int32(0),
				"schedule change should soft-delete untouched future instances")
		})

		// FR-010: New instances generated using the updated recurrence rule.
		t.Run("new weekly instances are generated after cleanup", func(t *testing.T) {
			assert.Greater(t, result.InstancesCreated, int32(0),
				"new instances should be generated on the weekly schedule")
		})

		// FR-015: schedule_version counter increments on each recurrence change.
		t.Run("the definition schedule_version incremented", func(t *testing.T) {
			updatedDef := w.getRitualDefinition(owner, def.Id)
			assert.Equal(t, int32(2), updatedDef.ScheduleVersion,
				"first schedule change should increment version from 1 to 2")
		})

		t.Run("the new recurrence rule matches the requested pattern", func(t *testing.T) {
			updatedDef := w.getRitualDefinition(owner, def.Id)
			assert.Equal(t, rpcv1.RecurrenceType_RECURRENCE_TYPE_WEEKLY, updatedDef.RecurrenceRule.Type,
				"definition's recurrence rule should be updated to weekly")
		})
	})

	t.Run("when running the scheduler after a schedule change", func(t *testing.T) {
		w.generateRitualInstances(owner)
		afterTasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))

		// FR-010: Regenerated instances use the updated recurrence rule.
		t.Run("new instances follow the weekly pattern, not the original daily pattern", func(t *testing.T) {
			require.NotEmpty(t, afterTasks)
			// Weekly = fewer instances than daily over same window.
			assert.Less(t, len(afterTasks), len(beforeTasks),
				"weekly schedule should produce fewer instances than daily schedule")
		})
	})
}

// TestRitualTasksImprovementScheduleChangeTouched verifies that touched future instances
// are converted to standalone tasks rather than deleted when the schedule changes.
func TestRitualTasksImprovementScheduleChangeTouched(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Touched Detach Project", uniqueProjectKey("TDET"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Daily Ops", dailyRecurrenceRule())
	w.generateRitualInstances(owner)
	tasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	require.NotEmpty(t, tasks)
	touchedTaskID := tasks[0].Id
	// Touch one future instance by opening its detail (triggers lazy resource creation).
	w.getTask(owner, touchedTaskID) // creates channel → task is now "touched"

	t.Run("when the schedule changes after one instance was touched", func(t *testing.T) {
		result := w.changeRitualDefinitionSchedule(owner, def.Id, weeklyRecurrenceRule())

		// FR-008: Touched future instances are detached as standalone tasks.
		t.Run("the touched instance count is reflected in the result", func(t *testing.T) {
			assert.Equal(t, int32(1), result.InstancesDetached,
				"exactly one instance was touched (channel created), so detach count must be 1")
		})

		// FR-008: ritual_definition_id cleared, task_kind = 'standard'.
		t.Run("the touched instance becomes a standalone standard task", func(t *testing.T) {
			detachedTask := w.getTask(owner, touchedTaskID)
			assert.Equal(t, rpcv1.TaskKind_TASK_KIND_STANDARD, detachedTask.TaskKind,
				"detached task must have task_kind = standard")
			assert.Empty(t, detachedTask.RitualDefinitionId,
				"detached task must have no ritual definition link")
		})

		// FR-017: detached_from_ritual flag enables UI to show origin label.
		t.Run("the touched instance has the detached_from_ritual flag set", func(t *testing.T) {
			detachedTask := w.getTask(owner, touchedTaskID)
			assert.True(t, detachedTask.DetachedFromRitual,
				"detached task must have detached_from_ritual = true")
		})

		// FR-016: Detached tasks retain original scheduled_date as advisory metadata.
		t.Run("the detached task retains its original scheduled date", func(t *testing.T) {
			detachedTask := w.getTask(owner, touchedTaskID)
			assert.NotEmpty(t, detachedTask.ScheduledDate,
				"detached task must retain its original scheduled_date")
		})

		t.Run("the detached task still appears in task lists (not deleted)", func(t *testing.T) {
			allTasks := w.listTasks(owner, proj.ID)
			var found bool
			for _, task := range allTasks {
				if task.Id == touchedTaskID {
					found = true
					break
				}
			}
			assert.True(t, found, "detached task must still appear in task list — it was not deleted")
		})
	})
}

// TestRitualTasksImprovementScheduleChangeHistorical verifies that historical instances
// (scheduled_date ≤ today) are never modified during a schedule change.
func TestRitualTasksImprovementScheduleChangeHistorical(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Historical Protection Project", uniqueProjectKey("HIST"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Historical Daily", dailyRecurrenceRule())
	// Inject a past-date ritual instance directly via the DB to simulate historical data.
	pastTaskID := w.injectPastRitualInstance(owner, proj, def)

	t.Run("when the schedule changes after historical instances exist", func(t *testing.T) {
		w.changeRitualDefinitionSchedule(owner, def.Id, weeklyRecurrenceRule())

		// FR-009: System MUST NOT modify instances with scheduled_date ≤ today.
		t.Run("historical instances are not soft-deleted", func(t *testing.T) {
			historicalTask := w.getTask(owner, pastTaskID)
			assert.NotNil(t, historicalTask,
				"historical instance must still be accessible after schedule change")
			assert.Equal(t, rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE, historicalTask.TaskKind,
				"historical instance must still be a ritual instance (not modified)")
		})

		// FR-009: Historical instances are never touched.
		t.Run("historical instances retain their ritual definition link", func(t *testing.T) {
			historicalTask := w.getTask(owner, pastTaskID)
			assert.Equal(t, def.Id, historicalTask.RitualDefinitionId,
				"historical instance must retain its ritual_definition_id")
		})

		t.Run("historical instances are not detached", func(t *testing.T) {
			historicalTask := w.getTask(owner, pastTaskID)
			assert.False(t, historicalTask.DetachedFromRitual,
				"historical instance must not be marked as detached")
		})
	})
}

// TestRitualTasksImprovementScheduleChangeAtomicity verifies that the schedule change
// operation is atomic — if anything fails, no partial changes are persisted.
func TestRitualTasksImprovementScheduleChangeAtomicity(t *testing.T) {
	t.Parallel()
	// FR-012: The entire schedule change operation executes atomically.
	// This is a structural test — we rely on the transaction boundary in the Connect layer.
	// The integration test verifies the observable effect: after a successful change,
	// ALL expected modifications are present (soft-deletes, detaches, new instances, version bump).
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Atomicity Project", uniqueProjectKey("ATOM"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Atomic Daily", dailyRecurrenceRule())
	w.generateRitualInstances(owner)
	beforeVersion := w.getRitualDefinition(owner, def.Id).ScheduleVersion
	beforeTasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	result := w.changeRitualDefinitionSchedule(owner, def.Id, weeklyRecurrenceRule())

	// FR-012: Atomic — all or nothing.
	t.Run("after a successful schedule change, all state changes are consistently applied", func(t *testing.T) {
		afterDef := w.getRitualDefinition(owner, def.Id)
		afterTasks := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
		assert.Equal(t, beforeVersion+1, afterDef.ScheduleVersion,
			"schedule_version must be incremented as part of the atomic operation")
		assert.Equal(t, rpcv1.RecurrenceType_RECURRENCE_TYPE_WEEKLY, afterDef.RecurrenceRule.Type,
			"recurrence rule must be updated as part of the atomic operation")
		assert.Greater(t, result.InstancesRemoved, int32(0),
			"soft-deleted instances must be reflected in response")
		assert.Greater(t, result.InstancesCreated, int32(0),
			"new instances must be generated as part of the atomic operation")
		assert.NotEqual(t, len(beforeTasks), len(afterTasks),
			"task list must change after schedule change (old removed, new generated)")
	})
}

// TestRitualTasksImprovementConfirmationRequired verifies that applying a schedule
// change without the confirmed=true flag is rejected.
func TestRitualTasksImprovementConfirmationRequired(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Confirmation Required Project", uniqueProjectKey("CONF"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Confirmation Ritual", dailyRecurrenceRule())

	t.Run("when applying a schedule change without confirmed=true", func(t *testing.T) {
		err := w.changeRitualDefinitionScheduleWithConfirmation(owner, def.Id, weeklyRecurrenceRule(), false)

		// FR-014: User MUST explicitly confirm before change is applied.
		t.Run("the server rejects the request with a failed precondition error", func(t *testing.T) {
			require.Error(t, err)
			assert.Equal(t, connect.CodeFailedPrecondition, connect.CodeOf(err),
				"unconfirmed schedule change must be rejected with FailedPrecondition")
		})

		t.Run("the definition schedule is unchanged", func(t *testing.T) {
			def := w.getRitualDefinition(owner, def.Id)
			assert.Equal(t, rpcv1.RecurrenceType_RECURRENCE_TYPE_DAILY, def.RecurrenceRule.Type,
				"definition should not change when schedule change is rejected")
			assert.Equal(t, int32(1), def.ScheduleVersion,
				"schedule_version must not increment when change is rejected")
		})
	})
}

// TestRitualTasksImprovementAccessControl verifies that only the definition creator
// or a project admin may change the recurrence schedule.
func TestRitualTasksImprovementAccessControl(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Access Control Project", uniqueProjectKey("ACTL"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	creator := w.withEmployee()
	nonAdmin := w.withEmployee()
	admin := w.withEmployee()
	w.addProjectMember(owner, proj.ID, creator.ID, rpcv1.ProjectMemberRole_PROJECT_MEMBER_ROLE_MEMBER)
	w.addProjectMember(owner, proj.ID, nonAdmin.ID, rpcv1.ProjectMemberRole_PROJECT_MEMBER_ROLE_MEMBER)
	w.addProjectMember(owner, proj.ID, admin.ID, rpcv1.ProjectMemberRole_PROJECT_MEMBER_ROLE_ADMIN)
	// Creator creates the definition (only admin/owner can currently do this per existing RBAC;
	// in this test, use owner to create and then test change permissions)
	def := w.createRitualDefinition(owner, proj.ID, "Access Controlled Ritual", dailyRecurrenceRule())

	t.Run("when a regular project member (non-creator, non-admin) attempts a schedule change", func(t *testing.T) {
		err := w.changeRitualDefinitionScheduleWithConfirmation(nonAdmin, def.Id, weeklyRecurrenceRule(), true)

		// FR-018: Only creator OR project admin may modify the recurrence pattern.
		t.Run("the request is denied with permission denied", func(t *testing.T) {
			require.Error(t, err)
			assert.Equal(t, connect.CodePermissionDenied, connect.CodeOf(err))
		})
	})

	t.Run("when a project admin changes the schedule", func(t *testing.T) {
		result := w.changeRitualDefinitionSchedule(admin, def.Id, weeklyRecurrenceRule())

		// FR-018: Project admin is authorized.
		t.Run("the change is applied successfully", func(t *testing.T) {
			assert.NotNil(t, result.RitualDefinition,
				"admin should be able to change the schedule")
		})
	})
}

// TestRitualTasksImprovementRapidScheduleChanges verifies that repeated schedule changes
// apply the "Clean Slate Forward" logic consistently (idempotent design).
func TestRitualTasksImprovementRapidScheduleChanges(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "Rapid Change Project", uniqueProjectKey("RPDC"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "Rapid Change Ritual", dailyRecurrenceRule())
	w.generateRitualInstances(owner)

	t.Run("when changing daily→weekly→bi-weekly in sequence", func(t *testing.T) {
		// First change: daily → weekly
		result1 := w.changeRitualDefinitionSchedule(owner, def.Id, weeklyRecurrenceRule())
		defAfterFirst := w.getRitualDefinition(owner, def.Id)
		// Second change: weekly → bi-weekly (every 2 weeks)
		result2 := w.changeRitualDefinitionSchedule(owner, def.Id, biWeeklyRecurrenceRule())
		defAfterSecond := w.getRitualDefinition(owner, def.Id)

		t.Run("each change increments the schedule_version", func(t *testing.T) {
			assert.Equal(t, int32(2), defAfterFirst.ScheduleVersion)
			assert.Equal(t, int32(3), defAfterSecond.ScheduleVersion)
		})

		t.Run("each change generates new instances matching the new pattern", func(t *testing.T) {
			assert.Greater(t, result1.InstancesCreated, int32(0))
			assert.Greater(t, result2.InstancesCreated, int32(0))
			// Bi-weekly should produce fewer instances than weekly over same window
			assert.LessOrEqual(t, result2.InstancesCreated, result1.InstancesCreated,
				"bi-weekly should produce fewer or equal instances than weekly")
		})

		t.Run("final instances follow the bi-weekly pattern", func(t *testing.T) {
			assert.Equal(t, rpcv1.RecurrenceType_RECURRENCE_TYPE_WEEKLY, defAfterSecond.RecurrenceRule.Type)
			assert.Equal(t, int32(2), defAfterSecond.RecurrenceRule.Interval,
				"bi-weekly = interval of 2 weeks")
		})
	})
}

// ---------------------------------------------------------------------------
// Scenario-specific testWorld helpers
// (These will be implemented in this file or in helper_test.go once design is approved)
// ---------------------------------------------------------------------------

// getScheduleChangeImpact calls GetScheduleChangeImpact RPC and returns the parsed response.
func (w *testWorld) getScheduleChangeImpact(actor testUser, ritualDefinitionID string, newRule *rpcv1.RecurrenceRule) *rpcv1.GetScheduleChangeImpactResponse {
	w.t.Helper()
	req := connect.NewRequest(&rpcv1.GetScheduleChangeImpactRequest{
		RitualDefinitionId: ritualDefinitionID,
		NewRecurrenceRule:  newRule,
	})
	req.Header().Set("Authorization", "Bearer "+actor.Token)
	resp, err := w.collab.GetScheduleChangeImpact(context.Background(), req)
	require.NoError(w.t, err)
	return resp.Msg
}

// changeRitualDefinitionSchedule calls ChangeRitualDefinitionSchedule with confirmed=true.
func (w *testWorld) changeRitualDefinitionSchedule(actor testUser, ritualDefinitionID string, newRule *rpcv1.RecurrenceRule) *rpcv1.ChangeRitualDefinitionScheduleResponse {
	w.t.Helper()
	req := connect.NewRequest(&rpcv1.ChangeRitualDefinitionScheduleRequest{
		RitualDefinitionId: ritualDefinitionID,
		NewRecurrenceRule:  newRule,
		Confirmed:          true,
	})
	req.Header().Set("Authorization", "Bearer "+actor.Token)
	resp, err := w.collab.ChangeRitualDefinitionSchedule(context.Background(), req)
	require.NoError(w.t, err)
	return resp.Msg
}

// changeRitualDefinitionScheduleWithConfirmation allows setting confirmed explicitly.
func (w *testWorld) changeRitualDefinitionScheduleWithConfirmation(actor testUser, ritualDefinitionID string, newRule *rpcv1.RecurrenceRule, confirmed bool) error {
	w.t.Helper()
	req := connect.NewRequest(&rpcv1.ChangeRitualDefinitionScheduleRequest{
		RitualDefinitionId: ritualDefinitionID,
		NewRecurrenceRule:  newRule,
		Confirmed:          confirmed,
	})
	req.Header().Set("Authorization", "Bearer "+actor.Token)
	_, err := w.collab.ChangeRitualDefinitionSchedule(context.Background(), req)
	return err
}

// injectPastRitualInstance creates a ritual instance task with a past scheduled_date
// by first generating instances normally, then backdating one via direct SQL.
func (w *testWorld) injectPastRitualInstance(actor testUser, proj projectResult, def *rpcv1.RitualDefinition) string {
	w.t.Helper()
	// Generate instances so we have real task rows.
	w.generateRitualInstances(actor)
	tasks := w.listTasksWithKind(actor, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	require.NotEmpty(w.t, tasks, "need at least one ritual instance to backdate")

	pastTaskID := tasks[0].Id
	pastDate := time.Now().AddDate(0, 0, -7)
	_, err := globalDB.Exec(context.Background(),
		`UPDATE collaboration.task SET scheduled_date = $1 WHERE id = $2 AND organization_id = $3`,
		pastDate, dbuuid.MustParse(pastTaskID), actor.OrgID,
	)
	require.NoError(w.t, err)
	return pastTaskID
}

// weeklyRecurrenceRule returns a weekly recurrence rule for use in test cases.
func weeklyRecurrenceRule() *rpcv1.RecurrenceRule {
	return &rpcv1.RecurrenceRule{
		Type:       rpcv1.RecurrenceType_RECURRENCE_TYPE_WEEKLY,
		Interval:   1,
		DaysOfWeek: []int32{1}, // Monday
	}
}

// biWeeklyRecurrenceRule returns a bi-weekly (every 2 weeks) recurrence rule.
func biWeeklyRecurrenceRule() *rpcv1.RecurrenceRule {
	return &rpcv1.RecurrenceRule{
		Type:       rpcv1.RecurrenceType_RECURRENCE_TYPE_WEEKLY,
		Interval:   2,
		DaysOfWeek: []int32{1}, // Monday
	}
}

// TestRitualTasksImprovementIdenticalScheduleNoOp verifies that changing a ritual's
// recurrence schedule to an identical rule is a no-op: no instances are removed,
// detached, or newly created, and the schedule_version remains unchanged.
func TestRitualTasksImprovementIdenticalScheduleNoOp(t *testing.T) {
	t.Parallel()
	w := newTestWorld(t)
	owner := w.withOwner()
	proj := w.createProjectWithMode(owner, "No-op Schedule Project", uniqueProjectKey("NOOP"), rpcv1.CollaborationMode_COLLABORATION_MODE_RITUAL)
	def := w.createRitualDefinition(owner, proj.ID, "No-op Ritual", dailyRecurrenceRule())
	w.generateRitualInstances(owner)

	defBefore := w.getRitualDefinition(owner, def.Id)
	initialInstances := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))
	instanceCountBefore := len(initialInstances)

	t.Run("when changing daily to the exact same daily rule", func(t *testing.T) {
		result := w.changeRitualDefinitionSchedule(owner, def.Id, dailyRecurrenceRule())
		defAfter := w.getRitualDefinition(owner, def.Id)
		instancesAfter := w.listTasksWithKind(owner, proj.ID, ptr(rpcv1.TaskKind_TASK_KIND_RITUAL_INSTANCE))

		t.Run("returns zero impact counts", func(t *testing.T) {
			assert.Equal(t, int32(0), result.InstancesRemoved)
			assert.Equal(t, int32(0), result.InstancesDetached)
			assert.Equal(t, int32(0), result.InstancesCreated)
		})

		t.Run("does not increment schedule_version", func(t *testing.T) {
			assert.Equal(t, defBefore.ScheduleVersion, defAfter.ScheduleVersion)
		})

		t.Run("does not remove any existing instances", func(t *testing.T) {
			assert.Equal(t, instanceCountBefore, len(instancesAfter))
		})
	})
}
