apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tech-office-postgres-dev

resources:
  - namespace.yaml
  - ../../base/database
  - ../../base/whisper

labels:
  - pairs:
      environment: dev