apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: api-https
      hostname: transformar.api.devguards.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: backend-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: voice-https
      hostname: transformar.media.devguards.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: livekit-signal-tls
      allowedRoutes:
        namespaces:
          from: Same