// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpc/v1/chat_files.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestChannelFileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`  // Channel to attach file to
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                     // Original filename
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`     // Client-declared MIME type
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // File size in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestChannelFileUploadRequest) Reset() {
	*x = RequestChannelFileUploadRequest{}
	mi := &file_rpc_v1_chat_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestChannelFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestChannelFileUploadRequest) ProtoMessage() {}

func (x *RequestChannelFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_chat_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestChannelFileUploadRequest.ProtoReflect.Descriptor instead.
func (*RequestChannelFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_chat_files_proto_rawDescGZIP(), []int{0}
}

func (x *RequestChannelFileUploadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RequestChannelFileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RequestChannelFileUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RequestChannelFileUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type RequestChannelFileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // Generated file ID
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // Presigned R2 upload URL
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // URL expiration time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestChannelFileUploadResponse) Reset() {
	*x = RequestChannelFileUploadResponse{}
	mi := &file_rpc_v1_chat_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestChannelFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestChannelFileUploadResponse) ProtoMessage() {}

func (x *RequestChannelFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_chat_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestChannelFileUploadResponse.ProtoReflect.Descriptor instead.
func (*RequestChannelFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_chat_files_proto_rawDescGZIP(), []int{1}
}

func (x *RequestChannelFileUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RequestChannelFileUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *RequestChannelFileUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmChannelFileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // Channel file was attached to
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // File ID from request response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmChannelFileUploadRequest) Reset() {
	*x = ConfirmChannelFileUploadRequest{}
	mi := &file_rpc_v1_chat_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmChannelFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmChannelFileUploadRequest) ProtoMessage() {}

func (x *ConfirmChannelFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_chat_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmChannelFileUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmChannelFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_chat_files_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmChannelFileUploadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ConfirmChannelFileUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ConfirmChannelFileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileMetadata          `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"` // Confirmed file metadata (imported from files.proto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmChannelFileUploadResponse) Reset() {
	*x = ConfirmChannelFileUploadResponse{}
	mi := &file_rpc_v1_chat_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmChannelFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmChannelFileUploadResponse) ProtoMessage() {}

func (x *ConfirmChannelFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_chat_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmChannelFileUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmChannelFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_chat_files_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmChannelFileUploadResponse) GetFile() *FileMetadata {
	if x != nil {
		return x.File
	}
	return nil
}

var File_rpc_v1_chat_files_proto protoreflect.FileDescriptor

const file_rpc_v1_chat_files_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/v1/chat_files.proto\x12\x06rpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11rpc/v1/rbac.proto\x1a\x12rpc/v1/files.proto\"\x98\x01\n" +
	"\x1fRequestChannelFileUploadRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x95\x01\n" +
	" RequestChannelFileUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"Y\n" +
	"\x1fConfirmChannelFileUploadRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"L\n" +
	" ConfirmChannelFileUploadResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.rpc.v1.FileMetadataR\x04file2\xa1\x02\n" +
	"\x0fChatFileService\x12\x85\x01\n" +
	"\x18RequestChannelFileUpload\x12'.rpc.v1.RequestChannelFileUploadRequest\x1a(.rpc.v1.RequestChannelFileUploadResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.filesUpload\x12\x85\x01\n" +
	"\x18ConfirmChannelFileUpload\x12'.rpc.v1.ConfirmChannelFileUploadRequest\x1a(.rpc.v1.ConfirmChannelFileUploadResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.filesUploadB\x89\x01\n" +
	"\n" +
	"com.rpc.v1B\x0eChatFilesProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_chat_files_proto_rawDescOnce sync.Once
	file_rpc_v1_chat_files_proto_rawDescData []byte
)

func file_rpc_v1_chat_files_proto_rawDescGZIP() []byte {
	file_rpc_v1_chat_files_proto_rawDescOnce.Do(func() {
		file_rpc_v1_chat_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_chat_files_proto_rawDesc), len(file_rpc_v1_chat_files_proto_rawDesc)))
	})
	return file_rpc_v1_chat_files_proto_rawDescData
}

var file_rpc_v1_chat_files_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_v1_chat_files_proto_goTypes = []any{
	(*RequestChannelFileUploadRequest)(nil),  // 0: rpc.v1.RequestChannelFileUploadRequest
	(*RequestChannelFileUploadResponse)(nil), // 1: rpc.v1.RequestChannelFileUploadResponse
	(*ConfirmChannelFileUploadRequest)(nil),  // 2: rpc.v1.ConfirmChannelFileUploadRequest
	(*ConfirmChannelFileUploadResponse)(nil), // 3: rpc.v1.ConfirmChannelFileUploadResponse
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
	(*FileMetadata)(nil),                     // 5: rpc.v1.FileMetadata
}
var file_rpc_v1_chat_files_proto_depIdxs = []int32{
	4, // 0: rpc.v1.RequestChannelFileUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 1: rpc.v1.ConfirmChannelFileUploadResponse.file:type_name -> rpc.v1.FileMetadata
	0, // 2: rpc.v1.ChatFileService.RequestChannelFileUpload:input_type -> rpc.v1.RequestChannelFileUploadRequest
	2, // 3: rpc.v1.ChatFileService.ConfirmChannelFileUpload:input_type -> rpc.v1.ConfirmChannelFileUploadRequest
	1, // 4: rpc.v1.ChatFileService.RequestChannelFileUpload:output_type -> rpc.v1.RequestChannelFileUploadResponse
	3, // 5: rpc.v1.ChatFileService.ConfirmChannelFileUpload:output_type -> rpc.v1.ConfirmChannelFileUploadResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_v1_chat_files_proto_init() }
func file_rpc_v1_chat_files_proto_init() {
	if File_rpc_v1_chat_files_proto != nil {
		return
	}
	file_rpc_v1_rbac_proto_init()
	file_rpc_v1_files_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_chat_files_proto_rawDesc), len(file_rpc_v1_chat_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_chat_files_proto_goTypes,
		DependencyIndexes: file_rpc_v1_chat_files_proto_depIdxs,
		MessageInfos:      file_rpc_v1_chat_files_proto_msgTypes,
	}.Build()
	File_rpc_v1_chat_files_proto = out.File
	file_rpc_v1_chat_files_proto_goTypes = nil
	file_rpc_v1_chat_files_proto_depIdxs = nil
}
