// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/compliance.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportTargetKind: what sort of item a report points at.
// MUST align with the target_kind CHECK on compliance.content_report.
type ReportTargetKind int32

const (
	ReportTargetKind_REPORT_TARGET_KIND_UNSPECIFIED      ReportTargetKind = 0
	ReportTargetKind_REPORT_TARGET_KIND_CHAT_MESSAGE     ReportTargetKind = 1
	ReportTargetKind_REPORT_TARGET_KIND_DIRECT_MESSAGE   ReportTargetKind = 2
	ReportTargetKind_REPORT_TARGET_KIND_FILE             ReportTargetKind = 3
	ReportTargetKind_REPORT_TARGET_KIND_DOCUMENT_COMMENT ReportTargetKind = 4
	ReportTargetKind_REPORT_TARGET_KIND_CALL_RECORD      ReportTargetKind = 5
)

// Enum value maps for ReportTargetKind.
var (
	ReportTargetKind_name = map[int32]string{
		0: "REPORT_TARGET_KIND_UNSPECIFIED",
		1: "REPORT_TARGET_KIND_CHAT_MESSAGE",
		2: "REPORT_TARGET_KIND_DIRECT_MESSAGE",
		3: "REPORT_TARGET_KIND_FILE",
		4: "REPORT_TARGET_KIND_DOCUMENT_COMMENT",
		5: "REPORT_TARGET_KIND_CALL_RECORD",
	}
	ReportTargetKind_value = map[string]int32{
		"REPORT_TARGET_KIND_UNSPECIFIED":      0,
		"REPORT_TARGET_KIND_CHAT_MESSAGE":     1,
		"REPORT_TARGET_KIND_DIRECT_MESSAGE":   2,
		"REPORT_TARGET_KIND_FILE":             3,
		"REPORT_TARGET_KIND_DOCUMENT_COMMENT": 4,
		"REPORT_TARGET_KIND_CALL_RECORD":      5,
	}
)

func (x ReportTargetKind) Enum() *ReportTargetKind {
	p := new(ReportTargetKind)
	*p = x
	return p
}

func (x ReportTargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportTargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[0].Descriptor()
}

func (ReportTargetKind) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[0]
}

func (x ReportTargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportTargetKind.Descriptor instead.
func (ReportTargetKind) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{0}
}

// ReportReason: why the reporter says the item is abusive.
// MUST align with the reason CHECK on compliance.content_report.
type ReportReason int32

const (
	ReportReason_REPORT_REASON_UNSPECIFIED    ReportReason = 0
	ReportReason_REPORT_REASON_HARASSMENT     ReportReason = 1
	ReportReason_REPORT_REASON_HATE_SPEECH    ReportReason = 2
	ReportReason_REPORT_REASON_SEXUAL_CONTENT ReportReason = 3
	ReportReason_REPORT_REASON_VIOLENCE       ReportReason = 4
	ReportReason_REPORT_REASON_SPAM           ReportReason = 5
	ReportReason_REPORT_REASON_OTHER          ReportReason = 6
)

// Enum value maps for ReportReason.
var (
	ReportReason_name = map[int32]string{
		0: "REPORT_REASON_UNSPECIFIED",
		1: "REPORT_REASON_HARASSMENT",
		2: "REPORT_REASON_HATE_SPEECH",
		3: "REPORT_REASON_SEXUAL_CONTENT",
		4: "REPORT_REASON_VIOLENCE",
		5: "REPORT_REASON_SPAM",
		6: "REPORT_REASON_OTHER",
	}
	ReportReason_value = map[string]int32{
		"REPORT_REASON_UNSPECIFIED":    0,
		"REPORT_REASON_HARASSMENT":     1,
		"REPORT_REASON_HATE_SPEECH":    2,
		"REPORT_REASON_SEXUAL_CONTENT": 3,
		"REPORT_REASON_VIOLENCE":       4,
		"REPORT_REASON_SPAM":           5,
		"REPORT_REASON_OTHER":          6,
	}
)

func (x ReportReason) Enum() *ReportReason {
	p := new(ReportReason)
	*p = x
	return p
}

func (x ReportReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportReason) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[1].Descriptor()
}

func (ReportReason) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[1]
}

func (x ReportReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportReason.Descriptor instead.
func (ReportReason) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{1}
}

// ReportStatus: where a report stands. 'actioned' and 'dismissed' are the two
// outcomes; both require an outcome note.
// MUST align with the status CHECK on compliance.content_report.
type ReportStatus int32

const (
	ReportStatus_REPORT_STATUS_UNSPECIFIED ReportStatus = 0
	ReportStatus_REPORT_STATUS_OUTSTANDING ReportStatus = 1
	ReportStatus_REPORT_STATUS_ACTIONED    ReportStatus = 2
	ReportStatus_REPORT_STATUS_DISMISSED   ReportStatus = 3
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_UNSPECIFIED",
		1: "REPORT_STATUS_OUTSTANDING",
		2: "REPORT_STATUS_ACTIONED",
		3: "REPORT_STATUS_DISMISSED",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_UNSPECIFIED": 0,
		"REPORT_STATUS_OUTSTANDING": 1,
		"REPORT_STATUS_ACTIONED":    2,
		"REPORT_STATUS_DISMISSED":   3,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[2].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[2]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{2}
}

// RemovalRequestStatus.
// MUST align with the status CHECK on compliance.removal_request.
type RemovalRequestStatus int32

const (
	RemovalRequestStatus_REMOVAL_REQUEST_STATUS_UNSPECIFIED RemovalRequestStatus = 0
	RemovalRequestStatus_REMOVAL_REQUEST_STATUS_OUTSTANDING RemovalRequestStatus = 1
	RemovalRequestStatus_REMOVAL_REQUEST_STATUS_GRANTED     RemovalRequestStatus = 2
	RemovalRequestStatus_REMOVAL_REQUEST_STATUS_DECLINED    RemovalRequestStatus = 3
)

// Enum value maps for RemovalRequestStatus.
var (
	RemovalRequestStatus_name = map[int32]string{
		0: "REMOVAL_REQUEST_STATUS_UNSPECIFIED",
		1: "REMOVAL_REQUEST_STATUS_OUTSTANDING",
		2: "REMOVAL_REQUEST_STATUS_GRANTED",
		3: "REMOVAL_REQUEST_STATUS_DECLINED",
	}
	RemovalRequestStatus_value = map[string]int32{
		"REMOVAL_REQUEST_STATUS_UNSPECIFIED": 0,
		"REMOVAL_REQUEST_STATUS_OUTSTANDING": 1,
		"REMOVAL_REQUEST_STATUS_GRANTED":     2,
		"REMOVAL_REQUEST_STATUS_DECLINED":    3,
	}
)

func (x RemovalRequestStatus) Enum() *RemovalRequestStatus {
	p := new(RemovalRequestStatus)
	*p = x
	return p
}

func (x RemovalRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemovalRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[3].Descriptor()
}

func (RemovalRequestStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[3]
}

func (x RemovalRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemovalRequestStatus.Descriptor instead.
func (RemovalRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{3}
}

// AccountDeletionState: the resumable erase state machine.
// MUST align with the state CHECK on compliance.account_deletion.
type AccountDeletionState int32

const (
	AccountDeletionState_ACCOUNT_DELETION_STATE_UNSPECIFIED AccountDeletionState = 0
	AccountDeletionState_ACCOUNT_DELETION_STATE_PENDING     AccountDeletionState = 1
	AccountDeletionState_ACCOUNT_DELETION_STATE_ANONYMISING AccountDeletionState = 2
	AccountDeletionState_ACCOUNT_DELETION_STATE_PURGING     AccountDeletionState = 3
	AccountDeletionState_ACCOUNT_DELETION_STATE_DONE        AccountDeletionState = 4
	AccountDeletionState_ACCOUNT_DELETION_STATE_FAILED      AccountDeletionState = 5
)

// Enum value maps for AccountDeletionState.
var (
	AccountDeletionState_name = map[int32]string{
		0: "ACCOUNT_DELETION_STATE_UNSPECIFIED",
		1: "ACCOUNT_DELETION_STATE_PENDING",
		2: "ACCOUNT_DELETION_STATE_ANONYMISING",
		3: "ACCOUNT_DELETION_STATE_PURGING",
		4: "ACCOUNT_DELETION_STATE_DONE",
		5: "ACCOUNT_DELETION_STATE_FAILED",
	}
	AccountDeletionState_value = map[string]int32{
		"ACCOUNT_DELETION_STATE_UNSPECIFIED": 0,
		"ACCOUNT_DELETION_STATE_PENDING":     1,
		"ACCOUNT_DELETION_STATE_ANONYMISING": 2,
		"ACCOUNT_DELETION_STATE_PURGING":     3,
		"ACCOUNT_DELETION_STATE_DONE":        4,
		"ACCOUNT_DELETION_STATE_FAILED":      5,
	}
)

func (x AccountDeletionState) Enum() *AccountDeletionState {
	p := new(AccountDeletionState)
	*p = x
	return p
}

func (x AccountDeletionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountDeletionState) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[4].Descriptor()
}

func (AccountDeletionState) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[4]
}

func (x AccountDeletionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountDeletionState.Descriptor instead.
func (AccountDeletionState) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{4}
}

// AccountRemovalPath: which of the two deletion paths a person gets, decided by
// iam.user.is_org_managed.
type AccountRemovalPath int32

const (
	AccountRemovalPath_ACCOUNT_REMOVAL_PATH_UNSPECIFIED AccountRemovalPath = 0
	// Self-registered: full in-app deletion.
	AccountRemovalPath_ACCOUNT_REMOVAL_PATH_SELF_DELETE AccountRemovalPath = 1
	// Admin-provisioned: an in-app request addressed to the organization's owners.
	AccountRemovalPath_ACCOUNT_REMOVAL_PATH_REQUEST_REMOVAL AccountRemovalPath = 2
)

// Enum value maps for AccountRemovalPath.
var (
	AccountRemovalPath_name = map[int32]string{
		0: "ACCOUNT_REMOVAL_PATH_UNSPECIFIED",
		1: "ACCOUNT_REMOVAL_PATH_SELF_DELETE",
		2: "ACCOUNT_REMOVAL_PATH_REQUEST_REMOVAL",
	}
	AccountRemovalPath_value = map[string]int32{
		"ACCOUNT_REMOVAL_PATH_UNSPECIFIED":     0,
		"ACCOUNT_REMOVAL_PATH_SELF_DELETE":     1,
		"ACCOUNT_REMOVAL_PATH_REQUEST_REMOVAL": 2,
	}
)

func (x AccountRemovalPath) Enum() *AccountRemovalPath {
	p := new(AccountRemovalPath)
	*p = x
	return p
}

func (x AccountRemovalPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountRemovalPath) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_compliance_proto_enumTypes[5].Descriptor()
}

func (AccountRemovalPath) Type() protoreflect.EnumType {
	return &file_rpc_v1_compliance_proto_enumTypes[5]
}

func (x AccountRemovalPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountRemovalPath.Descriptor instead.
func (AccountRemovalPath) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{5}
}

type ContentReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterEmployeeId string                 `protobuf:"bytes,2,opt,name=reporter_employee_id,json=reporterEmployeeId,proto3" json:"reporter_employee_id,omitempty"`
	ReporterName       string                 `protobuf:"bytes,3,opt,name=reporter_name,json=reporterName,proto3" json:"reporter_name,omitempty"`
	ReportedEmployeeId string                 `protobuf:"bytes,4,opt,name=reported_employee_id,json=reportedEmployeeId,proto3" json:"reported_employee_id,omitempty"`
	ReportedName       string                 `protobuf:"bytes,5,opt,name=reported_name,json=reportedName,proto3" json:"reported_name,omitempty"`
	TargetKind         ReportTargetKind       `protobuf:"varint,6,opt,name=target_kind,json=targetKind,proto3,enum=rpc.v1.ReportTargetKind" json:"target_kind,omitempty"`
	TargetId           string                 `protobuf:"bytes,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// The reported content as it stood at report time. This is what keeps a report
	// reviewable after its subject is deleted (FR-018).
	ContentSnapshot      string                 `protobuf:"bytes,8,opt,name=content_snapshot,json=contentSnapshot,proto3" json:"content_snapshot,omitempty"`
	Reason               ReportReason           `protobuf:"varint,9,opt,name=reason,proto3,enum=rpc.v1.ReportReason" json:"reason,omitempty"`
	Note                 string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	Status               ReportStatus           `protobuf:"varint,11,opt,name=status,proto3,enum=rpc.v1.ReportStatus" json:"status,omitempty"`
	OutcomeNote          string                 `protobuf:"bytes,12,opt,name=outcome_note,json=outcomeNote,proto3" json:"outcome_note,omitempty"`
	ReviewedByEmployeeId string                 `protobuf:"bytes,13,opt,name=reviewed_by_employee_id,json=reviewedByEmployeeId,proto3" json:"reviewed_by_employee_id,omitempty"`
	ReviewedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContentReport) Reset() {
	*x = ContentReport{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentReport) ProtoMessage() {}

func (x *ContentReport) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentReport.ProtoReflect.Descriptor instead.
func (*ContentReport) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ContentReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentReport) GetReporterEmployeeId() string {
	if x != nil {
		return x.ReporterEmployeeId
	}
	return ""
}

func (x *ContentReport) GetReporterName() string {
	if x != nil {
		return x.ReporterName
	}
	return ""
}

func (x *ContentReport) GetReportedEmployeeId() string {
	if x != nil {
		return x.ReportedEmployeeId
	}
	return ""
}

func (x *ContentReport) GetReportedName() string {
	if x != nil {
		return x.ReportedName
	}
	return ""
}

func (x *ContentReport) GetTargetKind() ReportTargetKind {
	if x != nil {
		return x.TargetKind
	}
	return ReportTargetKind_REPORT_TARGET_KIND_UNSPECIFIED
}

func (x *ContentReport) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ContentReport) GetContentSnapshot() string {
	if x != nil {
		return x.ContentSnapshot
	}
	return ""
}

func (x *ContentReport) GetReason() ReportReason {
	if x != nil {
		return x.Reason
	}
	return ReportReason_REPORT_REASON_UNSPECIFIED
}

func (x *ContentReport) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ContentReport) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *ContentReport) GetOutcomeNote() string {
	if x != nil {
		return x.OutcomeNote
	}
	return ""
}

func (x *ContentReport) GetReviewedByEmployeeId() string {
	if x != nil {
		return x.ReviewedByEmployeeId
	}
	return ""
}

func (x *ContentReport) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

func (x *ContentReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReportContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetKind    ReportTargetKind       `protobuf:"varint,1,opt,name=target_kind,json=targetKind,proto3,enum=rpc.v1.ReportTargetKind" json:"target_kind,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Reason        ReportReason           `protobuf:"varint,3,opt,name=reason,proto3,enum=rpc.v1.ReportReason" json:"reason,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContentRequest) Reset() {
	*x = ReportContentRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContentRequest) ProtoMessage() {}

func (x *ReportContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContentRequest.ProtoReflect.Descriptor instead.
func (*ReportContentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *ReportContentRequest) GetTargetKind() ReportTargetKind {
	if x != nil {
		return x.TargetKind
	}
	return ReportTargetKind_REPORT_TARGET_KIND_UNSPECIFIED
}

func (x *ReportContentRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ReportContentRequest) GetReason() ReportReason {
	if x != nil {
		return x.Reason
	}
	return ReportReason_REPORT_REASON_UNSPECIFIED
}

func (x *ReportContentRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ReportContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContentResponse) Reset() {
	*x = ReportContentResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContentResponse) ProtoMessage() {}

func (x *ReportContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContentResponse.ProtoReflect.Descriptor instead.
func (*ReportContentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *ReportContentResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportContentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListReportsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Omit to list every report regardless of status.
	StatusFilter ReportStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=rpc.v1.ReportStatus" json:"status_filter,omitempty"`
	// UUID v7 cursor, nullable per Principle IX: empty means "start at the newest".
	Cursor        string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *ListReportsRequest) GetStatusFilter() ReportStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *ListReportsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListReportsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListReportsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Reports []*ContentReport       `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	// Empty when there is no further page.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *ListReportsResponse) GetReports() []*ContentReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *GetReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetReportResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Report *ContentReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	// Populated only while the reported item still exists.
	LiveContentDeepLink string `protobuf:"bytes,2,opt,name=live_content_deep_link,json=liveContentDeepLink,proto3" json:"live_content_deep_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{6}
}

func (x *GetReportResponse) GetReport() *ContentReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetReportResponse) GetLiveContentDeepLink() string {
	if x != nil {
		return x.LiveContentDeepLink
	}
	return ""
}

type ResolveReportRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReportId string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// ACTIONED or DISMISSED. OUTSTANDING is rejected.
	Outcome ReportStatus `protobuf:"varint,2,opt,name=outcome,proto3,enum=rpc.v1.ReportStatus" json:"outcome,omitempty"`
	// Required and non-empty.
	OutcomeNote   string `protobuf:"bytes,3,opt,name=outcome_note,json=outcomeNote,proto3" json:"outcome_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReportRequest) Reset() {
	*x = ResolveReportRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReportRequest) ProtoMessage() {}

func (x *ResolveReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReportRequest.ProtoReflect.Descriptor instead.
func (*ResolveReportRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ResolveReportRequest) GetOutcome() ReportStatus {
	if x != nil {
		return x.Outcome
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *ResolveReportRequest) GetOutcomeNote() string {
	if x != nil {
		return x.OutcomeNote
	}
	return ""
}

type ResolveReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ContentReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReportResponse) Reset() {
	*x = ResolveReportResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReportResponse) ProtoMessage() {}

func (x *ResolveReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReportResponse.ProtoReflect.Descriptor instead.
func (*ResolveReportResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveReportResponse) GetReport() *ContentReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type BlockedPerson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedPerson) Reset() {
	*x = BlockedPerson{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedPerson) ProtoMessage() {}

func (x *BlockedPerson) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedPerson.ProtoReflect.Descriptor instead.
func (*BlockedPerson) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedPerson) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockedPerson) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *BlockedPerson) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BlockedPerson) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BlockedPerson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BlockPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPersonRequest) Reset() {
	*x = BlockPersonRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPersonRequest) ProtoMessage() {}

func (x *BlockPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPersonRequest.ProtoReflect.Descriptor instead.
func (*BlockPersonRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{10}
}

func (x *BlockPersonRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type BlockPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPersonResponse) Reset() {
	*x = BlockPersonResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPersonResponse) ProtoMessage() {}

func (x *BlockPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPersonResponse.ProtoReflect.Descriptor instead.
func (*BlockPersonResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{11}
}

func (x *BlockPersonResponse) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockPersonResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UnblockPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPersonRequest) Reset() {
	*x = UnblockPersonRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPersonRequest) ProtoMessage() {}

func (x *UnblockPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPersonRequest.ProtoReflect.Descriptor instead.
func (*UnblockPersonRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{12}
}

func (x *UnblockPersonRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type UnblockPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPersonResponse) Reset() {
	*x = UnblockPersonResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPersonResponse) ProtoMessage() {}

func (x *UnblockPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPersonResponse.ProtoReflect.Descriptor instead.
func (*UnblockPersonResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{13}
}

type ListBlockedPeopleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedPeopleRequest) Reset() {
	*x = ListBlockedPeopleRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedPeopleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedPeopleRequest) ProtoMessage() {}

func (x *ListBlockedPeopleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedPeopleRequest.ProtoReflect.Descriptor instead.
func (*ListBlockedPeopleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{14}
}

type ListBlockedPeopleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocked       []*BlockedPerson       `protobuf:"bytes,1,rep,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedPeopleResponse) Reset() {
	*x = ListBlockedPeopleResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedPeopleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedPeopleResponse) ProtoMessage() {}

func (x *ListBlockedPeopleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedPeopleResponse.ProtoReflect.Descriptor instead.
func (*ListBlockedPeopleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{15}
}

func (x *ListBlockedPeopleResponse) GetBlocked() []*BlockedPerson {
	if x != nil {
		return x.Blocked
	}
	return nil
}

type RemovalRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId          string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	EmployeeName        string                 `protobuf:"bytes,3,opt,name=employee_name,json=employeeName,proto3" json:"employee_name,omitempty"`
	Status              RemovalRequestStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=rpc.v1.RemovalRequestStatus" json:"status,omitempty"`
	Note                string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	DecidedByEmployeeId string                 `protobuf:"bytes,6,opt,name=decided_by_employee_id,json=decidedByEmployeeId,proto3" json:"decided_by_employee_id,omitempty"`
	DecidedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RemovalRequest) Reset() {
	*x = RemovalRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovalRequest) ProtoMessage() {}

func (x *RemovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovalRequest.ProtoReflect.Descriptor instead.
func (*RemovalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{16}
}

func (x *RemovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemovalRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *RemovalRequest) GetEmployeeName() string {
	if x != nil {
		return x.EmployeeName
	}
	return ""
}

func (x *RemovalRequest) GetStatus() RemovalRequestStatus {
	if x != nil {
		return x.Status
	}
	return RemovalRequestStatus_REMOVAL_REQUEST_STATUS_UNSPECIFIED
}

func (x *RemovalRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RemovalRequest) GetDecidedByEmployeeId() string {
	if x != nil {
		return x.DecidedByEmployeeId
	}
	return ""
}

func (x *RemovalRequest) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *RemovalRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAccountRemovalPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRemovalPathRequest) Reset() {
	*x = GetAccountRemovalPathRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRemovalPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRemovalPathRequest) ProtoMessage() {}

func (x *GetAccountRemovalPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRemovalPathRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRemovalPathRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{17}
}

type GetAccountRemovalPathResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  AccountRemovalPath     `protobuf:"varint,1,opt,name=path,proto3,enum=rpc.v1.AccountRemovalPath" json:"path,omitempty"`
	// Populated only for REQUEST_REMOVAL.
	ManagingOrganizationName string `protobuf:"bytes,2,opt,name=managing_organization_name,json=managingOrganizationName,proto3" json:"managing_organization_name,omitempty"`
	// The person's most recent request, if they have made one.
	LatestRequest *RemovalRequest `protobuf:"bytes,3,opt,name=latest_request,json=latestRequest,proto3" json:"latest_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRemovalPathResponse) Reset() {
	*x = GetAccountRemovalPathResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRemovalPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRemovalPathResponse) ProtoMessage() {}

func (x *GetAccountRemovalPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRemovalPathResponse.ProtoReflect.Descriptor instead.
func (*GetAccountRemovalPathResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{18}
}

func (x *GetAccountRemovalPathResponse) GetPath() AccountRemovalPath {
	if x != nil {
		return x.Path
	}
	return AccountRemovalPath_ACCOUNT_REMOVAL_PATH_UNSPECIFIED
}

func (x *GetAccountRemovalPathResponse) GetManagingOrganizationName() string {
	if x != nil {
		return x.ManagingOrganizationName
	}
	return ""
}

func (x *GetAccountRemovalPathResponse) GetLatestRequest() *RemovalRequest {
	if x != nil {
		return x.LatestRequest
	}
	return nil
}

type RequestAccountRemovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          string                 `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountRemovalRequest) Reset() {
	*x = RequestAccountRemovalRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountRemovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountRemovalRequest) ProtoMessage() {}

func (x *RequestAccountRemovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountRemovalRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountRemovalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{19}
}

func (x *RequestAccountRemovalRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RequestAccountRemovalResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *RemovalRequest        `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// True when an outstanding request already existed and was returned unchanged.
	AlreadyOutstanding bool `protobuf:"varint,2,opt,name=already_outstanding,json=alreadyOutstanding,proto3" json:"already_outstanding,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestAccountRemovalResponse) Reset() {
	*x = RequestAccountRemovalResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountRemovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountRemovalResponse) ProtoMessage() {}

func (x *RequestAccountRemovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountRemovalResponse.ProtoReflect.Descriptor instead.
func (*RequestAccountRemovalResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{20}
}

func (x *RequestAccountRemovalResponse) GetRequest() *RemovalRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RequestAccountRemovalResponse) GetAlreadyOutstanding() bool {
	if x != nil {
		return x.AlreadyOutstanding
	}
	return false
}

type ListRemovalRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  RemovalRequestStatus   `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=rpc.v1.RemovalRequestStatus" json:"status_filter,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemovalRequestsRequest) Reset() {
	*x = ListRemovalRequestsRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemovalRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemovalRequestsRequest) ProtoMessage() {}

func (x *ListRemovalRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemovalRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRemovalRequestsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{21}
}

func (x *ListRemovalRequestsRequest) GetStatusFilter() RemovalRequestStatus {
	if x != nil {
		return x.StatusFilter
	}
	return RemovalRequestStatus_REMOVAL_REQUEST_STATUS_UNSPECIFIED
}

func (x *ListRemovalRequestsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRemovalRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRemovalRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RemovalRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemovalRequestsResponse) Reset() {
	*x = ListRemovalRequestsResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemovalRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemovalRequestsResponse) ProtoMessage() {}

func (x *ListRemovalRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemovalRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRemovalRequestsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{22}
}

func (x *ListRemovalRequestsResponse) GetRequests() []*RemovalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListRemovalRequestsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DecideRemovalRequestRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// GRANTED or DECLINED. OUTSTANDING is rejected.
	Decision      RemovalRequestStatus `protobuf:"varint,2,opt,name=decision,proto3,enum=rpc.v1.RemovalRequestStatus" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRemovalRequestRequest) Reset() {
	*x = DecideRemovalRequestRequest{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRemovalRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRemovalRequestRequest) ProtoMessage() {}

func (x *DecideRemovalRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRemovalRequestRequest.ProtoReflect.Descriptor instead.
func (*DecideRemovalRequestRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{23}
}

func (x *DecideRemovalRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecideRemovalRequestRequest) GetDecision() RemovalRequestStatus {
	if x != nil {
		return x.Decision
	}
	return RemovalRequestStatus_REMOVAL_REQUEST_STATUS_UNSPECIFIED
}

type DecideRemovalRequestResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *RemovalRequest        `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// True when granting this request ended the person's last membership and so
	// enqueued the global purge of their identity data.
	GlobalPurgeEnqueued bool `protobuf:"varint,2,opt,name=global_purge_enqueued,json=globalPurgeEnqueued,proto3" json:"global_purge_enqueued,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DecideRemovalRequestResponse) Reset() {
	*x = DecideRemovalRequestResponse{}
	mi := &file_rpc_v1_compliance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRemovalRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRemovalRequestResponse) ProtoMessage() {}

func (x *DecideRemovalRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_compliance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRemovalRequestResponse.ProtoReflect.Descriptor instead.
func (*DecideRemovalRequestResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_compliance_proto_rawDescGZIP(), []int{24}
}

func (x *DecideRemovalRequestResponse) GetRequest() *RemovalRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DecideRemovalRequestResponse) GetGlobalPurgeEnqueued() bool {
	if x != nil {
		return x.GlobalPurgeEnqueued
	}
	return false
}

var File_rpc_v1_compliance_proto protoreflect.FileDescriptor

const file_rpc_v1_compliance_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/v1/compliance.proto\x12\x06rpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11rpc/v1/rbac.proto\"\x92\x05\n" +
	"\rContentReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14reporter_employee_id\x18\x02 \x01(\tR\x12reporterEmployeeId\x12#\n" +
	"\rreporter_name\x18\x03 \x01(\tR\freporterName\x120\n" +
	"\x14reported_employee_id\x18\x04 \x01(\tR\x12reportedEmployeeId\x12#\n" +
	"\rreported_name\x18\x05 \x01(\tR\freportedName\x129\n" +
	"\vtarget_kind\x18\x06 \x01(\x0e2\x18.rpc.v1.ReportTargetKindR\n" +
	"targetKind\x12\x1b\n" +
	"\ttarget_id\x18\a \x01(\tR\btargetId\x12)\n" +
	"\x10content_snapshot\x18\b \x01(\tR\x0fcontentSnapshot\x12,\n" +
	"\x06reason\x18\t \x01(\x0e2\x14.rpc.v1.ReportReasonR\x06reason\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\x12,\n" +
	"\x06status\x18\v \x01(\x0e2\x14.rpc.v1.ReportStatusR\x06status\x12!\n" +
	"\foutcome_note\x18\f \x01(\tR\voutcomeNote\x125\n" +
	"\x17reviewed_by_employee_id\x18\r \x01(\tR\x14reviewedByEmployeeId\x12;\n" +
	"\vreviewed_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb0\x01\n" +
	"\x14ReportContentRequest\x129\n" +
	"\vtarget_kind\x18\x01 \x01(\x0e2\x18.rpc.v1.ReportTargetKindR\n" +
	"targetKind\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12,\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x14.rpc.v1.ReportReasonR\x06reason\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"o\n" +
	"\x15ReportContentResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"}\n" +
	"\x12ListReportsRequest\x129\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x14.rpc.v1.ReportStatusR\fstatusFilter\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"g\n" +
	"\x13ListReportsResponse\x12/\n" +
	"\areports\x18\x01 \x03(\v2\x15.rpc.v1.ContentReportR\areports\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"/\n" +
	"\x10GetReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"w\n" +
	"\x11GetReportResponse\x12-\n" +
	"\x06report\x18\x01 \x01(\v2\x15.rpc.v1.ContentReportR\x06report\x123\n" +
	"\x16live_content_deep_link\x18\x02 \x01(\tR\x13liveContentDeepLink\"\x86\x01\n" +
	"\x14ResolveReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12.\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x14.rpc.v1.ReportStatusR\aoutcome\x12!\n" +
	"\foutcome_note\x18\x03 \x01(\tR\voutcomeNote\"F\n" +
	"\x15ResolveReportResponse\x12-\n" +
	"\x06report\x18\x01 \x01(\v2\x15.rpc.v1.ContentReportR\x06report\"\xbf\x01\n" +
	"\rBlockedPerson\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x12BlockPersonRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\"k\n" +
	"\x13BlockPersonResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"7\n" +
	"\x14UnblockPersonRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\"\x17\n" +
	"\x15UnblockPersonResponse\"\x1a\n" +
	"\x18ListBlockedPeopleRequest\"L\n" +
	"\x19ListBlockedPeopleResponse\x12/\n" +
	"\ablocked\x18\x01 \x03(\v2\x15.rpc.v1.BlockedPersonR\ablocked\"\xdb\x02\n" +
	"\x0eRemovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\x12#\n" +
	"\remployee_name\x18\x03 \x01(\tR\femployeeName\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.rpc.v1.RemovalRequestStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x123\n" +
	"\x16decided_by_employee_id\x18\x06 \x01(\tR\x13decidedByEmployeeId\x129\n" +
	"\n" +
	"decided_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x1e\n" +
	"\x1cGetAccountRemovalPathRequest\"\xcc\x01\n" +
	"\x1dGetAccountRemovalPathResponse\x12.\n" +
	"\x04path\x18\x01 \x01(\x0e2\x1a.rpc.v1.AccountRemovalPathR\x04path\x12<\n" +
	"\x1amanaging_organization_name\x18\x02 \x01(\tR\x18managingOrganizationName\x12=\n" +
	"\x0elatest_request\x18\x03 \x01(\v2\x16.rpc.v1.RemovalRequestR\rlatestRequest\"2\n" +
	"\x1cRequestAccountRemovalRequest\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\"\x82\x01\n" +
	"\x1dRequestAccountRemovalResponse\x120\n" +
	"\arequest\x18\x01 \x01(\v2\x16.rpc.v1.RemovalRequestR\arequest\x12/\n" +
	"\x13already_outstanding\x18\x02 \x01(\bR\x12alreadyOutstanding\"\x8d\x01\n" +
	"\x1aListRemovalRequestsRequest\x12A\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x1c.rpc.v1.RemovalRequestStatusR\fstatusFilter\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"r\n" +
	"\x1bListRemovalRequestsResponse\x122\n" +
	"\brequests\x18\x01 \x03(\v2\x16.rpc.v1.RemovalRequestR\brequests\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"v\n" +
	"\x1bDecideRemovalRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1c.rpc.v1.RemovalRequestStatusR\bdecision\"\x84\x01\n" +
	"\x1cDecideRemovalRequestResponse\x120\n" +
	"\arequest\x18\x01 \x01(\v2\x16.rpc.v1.RemovalRequestR\arequest\x122\n" +
	"\x15global_purge_enqueued\x18\x02 \x01(\bR\x13globalPurgeEnqueued*\xec\x01\n" +
	"\x10ReportTargetKind\x12\"\n" +
	"\x1eREPORT_TARGET_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fREPORT_TARGET_KIND_CHAT_MESSAGE\x10\x01\x12%\n" +
	"!REPORT_TARGET_KIND_DIRECT_MESSAGE\x10\x02\x12\x1b\n" +
	"\x17REPORT_TARGET_KIND_FILE\x10\x03\x12'\n" +
	"#REPORT_TARGET_KIND_DOCUMENT_COMMENT\x10\x04\x12\"\n" +
	"\x1eREPORT_TARGET_KIND_CALL_RECORD\x10\x05*\xd9\x01\n" +
	"\fReportReason\x12\x1d\n" +
	"\x19REPORT_REASON_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REPORT_REASON_HARASSMENT\x10\x01\x12\x1d\n" +
	"\x19REPORT_REASON_HATE_SPEECH\x10\x02\x12 \n" +
	"\x1cREPORT_REASON_SEXUAL_CONTENT\x10\x03\x12\x1a\n" +
	"\x16REPORT_REASON_VIOLENCE\x10\x04\x12\x16\n" +
	"\x12REPORT_REASON_SPAM\x10\x05\x12\x17\n" +
	"\x13REPORT_REASON_OTHER\x10\x06*\x85\x01\n" +
	"\fReportStatus\x12\x1d\n" +
	"\x19REPORT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19REPORT_STATUS_OUTSTANDING\x10\x01\x12\x1a\n" +
	"\x16REPORT_STATUS_ACTIONED\x10\x02\x12\x1b\n" +
	"\x17REPORT_STATUS_DISMISSED\x10\x03*\xaf\x01\n" +
	"\x14RemovalRequestStatus\x12&\n" +
	"\"REMOVAL_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"REMOVAL_REQUEST_STATUS_OUTSTANDING\x10\x01\x12\"\n" +
	"\x1eREMOVAL_REQUEST_STATUS_GRANTED\x10\x02\x12#\n" +
	"\x1fREMOVAL_REQUEST_STATUS_DECLINED\x10\x03*\xf2\x01\n" +
	"\x14AccountDeletionState\x12&\n" +
	"\"ACCOUNT_DELETION_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eACCOUNT_DELETION_STATE_PENDING\x10\x01\x12&\n" +
	"\"ACCOUNT_DELETION_STATE_ANONYMISING\x10\x02\x12\"\n" +
	"\x1eACCOUNT_DELETION_STATE_PURGING\x10\x03\x12\x1f\n" +
	"\x1bACCOUNT_DELETION_STATE_DONE\x10\x04\x12!\n" +
	"\x1dACCOUNT_DELETION_STATE_FAILED\x10\x05*\x8a\x01\n" +
	"\x12AccountRemovalPath\x12$\n" +
	" ACCOUNT_REMOVAL_PATH_UNSPECIFIED\x10\x00\x12$\n" +
	" ACCOUNT_REMOVAL_PATH_SELF_DELETE\x10\x01\x12(\n" +
	"$ACCOUNT_REMOVAL_PATH_REQUEST_REMOVAL\x10\x022\xf0\t\n" +
	"\x11ComplianceService\x12l\n" +
	"\rReportContent\x12\x1c.rpc.v1.ReportContentRequest\x1a\x1d.rpc.v1.ReportContentResponse\"\x1e\x82\xf9+\x1a\n" +
	"\x18compliance.reportContent\x12f\n" +
	"\vListReports\x12\x1a.rpc.v1.ListReportsRequest\x1a\x1b.rpc.v1.ListReportsResponse\"\x1e\x82\xf9+\x1a\n" +
	"\x18compliance.reviewReports\x12`\n" +
	"\tGetReport\x12\x18.rpc.v1.GetReportRequest\x1a\x19.rpc.v1.GetReportResponse\"\x1e\x82\xf9+\x1a\n" +
	"\x18compliance.reviewReports\x12l\n" +
	"\rResolveReport\x12\x1c.rpc.v1.ResolveReportRequest\x1a\x1d.rpc.v1.ResolveReportResponse\"\x1e\x82\xf9+\x1a\n" +
	"\x18compliance.reviewReports\x12d\n" +
	"\vBlockPerson\x12\x1a.rpc.v1.BlockPersonRequest\x1a\x1b.rpc.v1.BlockPersonResponse\"\x1c\x82\xf9+\x18\n" +
	"\x16compliance.blockPerson\x12j\n" +
	"\rUnblockPerson\x12\x1c.rpc.v1.UnblockPersonRequest\x1a\x1d.rpc.v1.UnblockPersonResponse\"\x1c\x82\xf9+\x18\n" +
	"\x16compliance.blockPerson\x12v\n" +
	"\x11ListBlockedPeople\x12 .rpc.v1.ListBlockedPeopleRequest\x1a!.rpc.v1.ListBlockedPeopleResponse\"\x1c\x82\xf9+\x18\n" +
	"\x16compliance.blockPerson\x12j\n" +
	"\x15GetAccountRemovalPath\x12$.rpc.v1.GetAccountRemovalPathRequest\x1a%.rpc.v1.GetAccountRemovalPathResponse\"\x04\x82\xf9+\x00\x12j\n" +
	"\x15RequestAccountRemoval\x12$.rpc.v1.RequestAccountRemovalRequest\x1a%.rpc.v1.RequestAccountRemovalResponse\"\x04\x82\xf9+\x00\x12\x86\x01\n" +
	"\x13ListRemovalRequests\x12\".rpc.v1.ListRemovalRequestsRequest\x1a#.rpc.v1.ListRemovalRequestsResponse\"&\x82\xf9+\"\n" +
	" compliance.manageRemovalRequests\x12\x89\x01\n" +
	"\x14DecideRemovalRequest\x12#.rpc.v1.DecideRemovalRequestRequest\x1a$.rpc.v1.DecideRemovalRequestResponse\"&\x82\xf9+\"\n" +
	" compliance.manageRemovalRequestsB\x8a\x01\n" +
	"\n" +
	"com.rpc.v1B\x0fComplianceProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_compliance_proto_rawDescOnce sync.Once
	file_rpc_v1_compliance_proto_rawDescData []byte
)

func file_rpc_v1_compliance_proto_rawDescGZIP() []byte {
	file_rpc_v1_compliance_proto_rawDescOnce.Do(func() {
		file_rpc_v1_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_compliance_proto_rawDesc), len(file_rpc_v1_compliance_proto_rawDesc)))
	})
	return file_rpc_v1_compliance_proto_rawDescData
}

var file_rpc_v1_compliance_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_rpc_v1_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rpc_v1_compliance_proto_goTypes = []any{
	(ReportTargetKind)(0),                 // 0: rpc.v1.ReportTargetKind
	(ReportReason)(0),                     // 1: rpc.v1.ReportReason
	(ReportStatus)(0),                     // 2: rpc.v1.ReportStatus
	(RemovalRequestStatus)(0),             // 3: rpc.v1.RemovalRequestStatus
	(AccountDeletionState)(0),             // 4: rpc.v1.AccountDeletionState
	(AccountRemovalPath)(0),               // 5: rpc.v1.AccountRemovalPath
	(*ContentReport)(nil),                 // 6: rpc.v1.ContentReport
	(*ReportContentRequest)(nil),          // 7: rpc.v1.ReportContentRequest
	(*ReportContentResponse)(nil),         // 8: rpc.v1.ReportContentResponse
	(*ListReportsRequest)(nil),            // 9: rpc.v1.ListReportsRequest
	(*ListReportsResponse)(nil),           // 10: rpc.v1.ListReportsResponse
	(*GetReportRequest)(nil),              // 11: rpc.v1.GetReportRequest
	(*GetReportResponse)(nil),             // 12: rpc.v1.GetReportResponse
	(*ResolveReportRequest)(nil),          // 13: rpc.v1.ResolveReportRequest
	(*ResolveReportResponse)(nil),         // 14: rpc.v1.ResolveReportResponse
	(*BlockedPerson)(nil),                 // 15: rpc.v1.BlockedPerson
	(*BlockPersonRequest)(nil),            // 16: rpc.v1.BlockPersonRequest
	(*BlockPersonResponse)(nil),           // 17: rpc.v1.BlockPersonResponse
	(*UnblockPersonRequest)(nil),          // 18: rpc.v1.UnblockPersonRequest
	(*UnblockPersonResponse)(nil),         // 19: rpc.v1.UnblockPersonResponse
	(*ListBlockedPeopleRequest)(nil),      // 20: rpc.v1.ListBlockedPeopleRequest
	(*ListBlockedPeopleResponse)(nil),     // 21: rpc.v1.ListBlockedPeopleResponse
	(*RemovalRequest)(nil),                // 22: rpc.v1.RemovalRequest
	(*GetAccountRemovalPathRequest)(nil),  // 23: rpc.v1.GetAccountRemovalPathRequest
	(*GetAccountRemovalPathResponse)(nil), // 24: rpc.v1.GetAccountRemovalPathResponse
	(*RequestAccountRemovalRequest)(nil),  // 25: rpc.v1.RequestAccountRemovalRequest
	(*RequestAccountRemovalResponse)(nil), // 26: rpc.v1.RequestAccountRemovalResponse
	(*ListRemovalRequestsRequest)(nil),    // 27: rpc.v1.ListRemovalRequestsRequest
	(*ListRemovalRequestsResponse)(nil),   // 28: rpc.v1.ListRemovalRequestsResponse
	(*DecideRemovalRequestRequest)(nil),   // 29: rpc.v1.DecideRemovalRequestRequest
	(*DecideRemovalRequestResponse)(nil),  // 30: rpc.v1.DecideRemovalRequestResponse
	(*timestamppb.Timestamp)(nil),         // 31: google.protobuf.Timestamp
}
var file_rpc_v1_compliance_proto_depIdxs = []int32{
	0,  // 0: rpc.v1.ContentReport.target_kind:type_name -> rpc.v1.ReportTargetKind
	1,  // 1: rpc.v1.ContentReport.reason:type_name -> rpc.v1.ReportReason
	2,  // 2: rpc.v1.ContentReport.status:type_name -> rpc.v1.ReportStatus
	31, // 3: rpc.v1.ContentReport.reviewed_at:type_name -> google.protobuf.Timestamp
	31, // 4: rpc.v1.ContentReport.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: rpc.v1.ReportContentRequest.target_kind:type_name -> rpc.v1.ReportTargetKind
	1,  // 6: rpc.v1.ReportContentRequest.reason:type_name -> rpc.v1.ReportReason
	31, // 7: rpc.v1.ReportContentResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 8: rpc.v1.ListReportsRequest.status_filter:type_name -> rpc.v1.ReportStatus
	6,  // 9: rpc.v1.ListReportsResponse.reports:type_name -> rpc.v1.ContentReport
	6,  // 10: rpc.v1.GetReportResponse.report:type_name -> rpc.v1.ContentReport
	2,  // 11: rpc.v1.ResolveReportRequest.outcome:type_name -> rpc.v1.ReportStatus
	6,  // 12: rpc.v1.ResolveReportResponse.report:type_name -> rpc.v1.ContentReport
	31, // 13: rpc.v1.BlockedPerson.created_at:type_name -> google.protobuf.Timestamp
	31, // 14: rpc.v1.BlockPersonResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 15: rpc.v1.ListBlockedPeopleResponse.blocked:type_name -> rpc.v1.BlockedPerson
	3,  // 16: rpc.v1.RemovalRequest.status:type_name -> rpc.v1.RemovalRequestStatus
	31, // 17: rpc.v1.RemovalRequest.decided_at:type_name -> google.protobuf.Timestamp
	31, // 18: rpc.v1.RemovalRequest.created_at:type_name -> google.protobuf.Timestamp
	5,  // 19: rpc.v1.GetAccountRemovalPathResponse.path:type_name -> rpc.v1.AccountRemovalPath
	22, // 20: rpc.v1.GetAccountRemovalPathResponse.latest_request:type_name -> rpc.v1.RemovalRequest
	22, // 21: rpc.v1.RequestAccountRemovalResponse.request:type_name -> rpc.v1.RemovalRequest
	3,  // 22: rpc.v1.ListRemovalRequestsRequest.status_filter:type_name -> rpc.v1.RemovalRequestStatus
	22, // 23: rpc.v1.ListRemovalRequestsResponse.requests:type_name -> rpc.v1.RemovalRequest
	3,  // 24: rpc.v1.DecideRemovalRequestRequest.decision:type_name -> rpc.v1.RemovalRequestStatus
	22, // 25: rpc.v1.DecideRemovalRequestResponse.request:type_name -> rpc.v1.RemovalRequest
	7,  // 26: rpc.v1.ComplianceService.ReportContent:input_type -> rpc.v1.ReportContentRequest
	9,  // 27: rpc.v1.ComplianceService.ListReports:input_type -> rpc.v1.ListReportsRequest
	11, // 28: rpc.v1.ComplianceService.GetReport:input_type -> rpc.v1.GetReportRequest
	13, // 29: rpc.v1.ComplianceService.ResolveReport:input_type -> rpc.v1.ResolveReportRequest
	16, // 30: rpc.v1.ComplianceService.BlockPerson:input_type -> rpc.v1.BlockPersonRequest
	18, // 31: rpc.v1.ComplianceService.UnblockPerson:input_type -> rpc.v1.UnblockPersonRequest
	20, // 32: rpc.v1.ComplianceService.ListBlockedPeople:input_type -> rpc.v1.ListBlockedPeopleRequest
	23, // 33: rpc.v1.ComplianceService.GetAccountRemovalPath:input_type -> rpc.v1.GetAccountRemovalPathRequest
	25, // 34: rpc.v1.ComplianceService.RequestAccountRemoval:input_type -> rpc.v1.RequestAccountRemovalRequest
	27, // 35: rpc.v1.ComplianceService.ListRemovalRequests:input_type -> rpc.v1.ListRemovalRequestsRequest
	29, // 36: rpc.v1.ComplianceService.DecideRemovalRequest:input_type -> rpc.v1.DecideRemovalRequestRequest
	8,  // 37: rpc.v1.ComplianceService.ReportContent:output_type -> rpc.v1.ReportContentResponse
	10, // 38: rpc.v1.ComplianceService.ListReports:output_type -> rpc.v1.ListReportsResponse
	12, // 39: rpc.v1.ComplianceService.GetReport:output_type -> rpc.v1.GetReportResponse
	14, // 40: rpc.v1.ComplianceService.ResolveReport:output_type -> rpc.v1.ResolveReportResponse
	17, // 41: rpc.v1.ComplianceService.BlockPerson:output_type -> rpc.v1.BlockPersonResponse
	19, // 42: rpc.v1.ComplianceService.UnblockPerson:output_type -> rpc.v1.UnblockPersonResponse
	21, // 43: rpc.v1.ComplianceService.ListBlockedPeople:output_type -> rpc.v1.ListBlockedPeopleResponse
	24, // 44: rpc.v1.ComplianceService.GetAccountRemovalPath:output_type -> rpc.v1.GetAccountRemovalPathResponse
	26, // 45: rpc.v1.ComplianceService.RequestAccountRemoval:output_type -> rpc.v1.RequestAccountRemovalResponse
	28, // 46: rpc.v1.ComplianceService.ListRemovalRequests:output_type -> rpc.v1.ListRemovalRequestsResponse
	30, // 47: rpc.v1.ComplianceService.DecideRemovalRequest:output_type -> rpc.v1.DecideRemovalRequestResponse
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_rpc_v1_compliance_proto_init() }
func file_rpc_v1_compliance_proto_init() {
	if File_rpc_v1_compliance_proto != nil {
		return
	}
	file_rpc_v1_rbac_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_compliance_proto_rawDesc), len(file_rpc_v1_compliance_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_compliance_proto_goTypes,
		DependencyIndexes: file_rpc_v1_compliance_proto_depIdxs,
		EnumInfos:         file_rpc_v1_compliance_proto_enumTypes,
		MessageInfos:      file_rpc_v1_compliance_proto_msgTypes,
	}.Build()
	File_rpc_v1_compliance_proto = out.File
	file_rpc_v1_compliance_proto_goTypes = nil
	file_rpc_v1_compliance_proto_depIdxs = nil
}
