// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/docs_error_details.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentVersionConflict — attached to ABORTED when DocumentService.UpdateDocument
// is refused because the base version the editor started from is no longer the
// document's current version (feature 049).
//
// Without this detail a client can only say "that didn't save". With it, the editor
// can name the person who got there first, say when, and reload exactly the version
// it needs — without a second round trip.
//
// Only ever produced for a caller who already passed the write-access check, so the
// author's name discloses nothing they could not read in the version history.
type DocumentVersionConflict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The document's current version number, i.e. what the client's base version should
	// have been. Reload this version to be able to save. (FR-005)
	CurrentVersionNumber int32 `protobuf:"varint,1,opt,name=current_version_number,json=currentVersionNumber,proto3" json:"current_version_number,omitempty"`
	// Display name of the person whose save created current_version_number. (FR-006)
	ConflictingAuthorName string `protobuf:"bytes,2,opt,name=conflicting_author_name,json=conflictingAuthorName,proto3" json:"conflicting_author_name,omitempty"`
	// When that version was created. (FR-006)
	ConflictingChangedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=conflicting_changed_at,json=conflictingChangedAt,proto3" json:"conflicting_changed_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DocumentVersionConflict) Reset() {
	*x = DocumentVersionConflict{}
	mi := &file_rpc_v1_docs_error_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersionConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersionConflict) ProtoMessage() {}

func (x *DocumentVersionConflict) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_docs_error_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersionConflict.ProtoReflect.Descriptor instead.
func (*DocumentVersionConflict) Descriptor() ([]byte, []int) {
	return file_rpc_v1_docs_error_details_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentVersionConflict) GetCurrentVersionNumber() int32 {
	if x != nil {
		return x.CurrentVersionNumber
	}
	return 0
}

func (x *DocumentVersionConflict) GetConflictingAuthorName() string {
	if x != nil {
		return x.ConflictingAuthorName
	}
	return ""
}

func (x *DocumentVersionConflict) GetConflictingChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConflictingChangedAt
	}
	return nil
}

var File_rpc_v1_docs_error_details_proto protoreflect.FileDescriptor

const file_rpc_v1_docs_error_details_proto_rawDesc = "" +
	"\n" +
	"\x1frpc/v1/docs_error_details.proto\x12\x06rpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x17DocumentVersionConflict\x124\n" +
	"\x16current_version_number\x18\x01 \x01(\x05R\x14currentVersionNumber\x126\n" +
	"\x17conflicting_author_name\x18\x02 \x01(\tR\x15conflictingAuthorName\x12P\n" +
	"\x16conflicting_changed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x14conflictingChangedAtB\x90\x01\n" +
	"\n" +
	"com.rpc.v1B\x15DocsErrorDetailsProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_docs_error_details_proto_rawDescOnce sync.Once
	file_rpc_v1_docs_error_details_proto_rawDescData []byte
)

func file_rpc_v1_docs_error_details_proto_rawDescGZIP() []byte {
	file_rpc_v1_docs_error_details_proto_rawDescOnce.Do(func() {
		file_rpc_v1_docs_error_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_docs_error_details_proto_rawDesc), len(file_rpc_v1_docs_error_details_proto_rawDesc)))
	})
	return file_rpc_v1_docs_error_details_proto_rawDescData
}

var file_rpc_v1_docs_error_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_v1_docs_error_details_proto_goTypes = []any{
	(*DocumentVersionConflict)(nil), // 0: rpc.v1.DocumentVersionConflict
	(*timestamppb.Timestamp)(nil),   // 1: google.protobuf.Timestamp
}
var file_rpc_v1_docs_error_details_proto_depIdxs = []int32{
	1, // 0: rpc.v1.DocumentVersionConflict.conflicting_changed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_v1_docs_error_details_proto_init() }
func file_rpc_v1_docs_error_details_proto_init() {
	if File_rpc_v1_docs_error_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_docs_error_details_proto_rawDesc), len(file_rpc_v1_docs_error_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_v1_docs_error_details_proto_goTypes,
		DependencyIndexes: file_rpc_v1_docs_error_details_proto_depIdxs,
		MessageInfos:      file_rpc_v1_docs_error_details_proto_msgTypes,
	}.Build()
	File_rpc_v1_docs_error_details_proto = out.File
	file_rpc_v1_docs_error_details_proto_goTypes = nil
	file_rpc_v1_docs_error_details_proto_depIdxs = nil
}
