// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/preference.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Theme mode selection
type ThemeMode int32

const (
	ThemeMode_THEME_MODE_UNSPECIFIED ThemeMode = 0 // Invalid/default value
	ThemeMode_THEME_MODE_LIGHT       ThemeMode = 1 // Light theme
	ThemeMode_THEME_MODE_DARK        ThemeMode = 2 // Dark theme
)

// Enum value maps for ThemeMode.
var (
	ThemeMode_name = map[int32]string{
		0: "THEME_MODE_UNSPECIFIED",
		1: "THEME_MODE_LIGHT",
		2: "THEME_MODE_DARK",
	}
	ThemeMode_value = map[string]int32{
		"THEME_MODE_UNSPECIFIED": 0,
		"THEME_MODE_LIGHT":       1,
		"THEME_MODE_DARK":        2,
	}
)

func (x ThemeMode) Enum() *ThemeMode {
	p := new(ThemeMode)
	*p = x
	return p
}

func (x ThemeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThemeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_preference_proto_enumTypes[0].Descriptor()
}

func (ThemeMode) Type() protoreflect.EnumType {
	return &file_rpc_v1_preference_proto_enumTypes[0]
}

func (x ThemeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThemeMode.Descriptor instead.
func (ThemeMode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{0}
}

// How the theme preference was determined
type PreferenceSource int32

const (
	PreferenceSource_PREFERENCE_SOURCE_UNSPECIFIED PreferenceSource = 0 // Invalid/default value
	PreferenceSource_PREFERENCE_SOURCE_MANUAL      PreferenceSource = 1 // User manually selected via toggle
	PreferenceSource_PREFERENCE_SOURCE_OS_DEFAULT  PreferenceSource = 2 // Detected from OS/browser preference
)

// Enum value maps for PreferenceSource.
var (
	PreferenceSource_name = map[int32]string{
		0: "PREFERENCE_SOURCE_UNSPECIFIED",
		1: "PREFERENCE_SOURCE_MANUAL",
		2: "PREFERENCE_SOURCE_OS_DEFAULT",
	}
	PreferenceSource_value = map[string]int32{
		"PREFERENCE_SOURCE_UNSPECIFIED": 0,
		"PREFERENCE_SOURCE_MANUAL":      1,
		"PREFERENCE_SOURCE_OS_DEFAULT":  2,
	}
)

func (x PreferenceSource) Enum() *PreferenceSource {
	p := new(PreferenceSource)
	*p = x
	return p
}

func (x PreferenceSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceSource) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_preference_proto_enumTypes[1].Descriptor()
}

func (PreferenceSource) Type() protoreflect.EnumType {
	return &file_rpc_v1_preference_proto_enumTypes[1]
}

func (x PreferenceSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceSource.Descriptor instead.
func (PreferenceSource) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{1}
}

// User preference settings
type UserPreference struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // UUID v7
	EmployeeId       string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`                                                 // Employee UUID (identity)
	ThemeMode        ThemeMode              `protobuf:"varint,3,opt,name=theme_mode,json=themeMode,proto3,enum=rpc.v1.ThemeMode" json:"theme_mode,omitempty"`                             // Active theme mode
	PreferenceSource PreferenceSource       `protobuf:"varint,4,opt,name=preference_source,json=preferenceSource,proto3,enum=rpc.v1.PreferenceSource" json:"preference_source,omitempty"` // How theme was selected
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                    // Last update timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserPreference) Reset() {
	*x = UserPreference{}
	mi := &file_rpc_v1_preference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreference) ProtoMessage() {}

func (x *UserPreference) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreference.ProtoReflect.Descriptor instead.
func (*UserPreference) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{0}
}

func (x *UserPreference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPreference) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *UserPreference) GetThemeMode() ThemeMode {
	if x != nil {
		return x.ThemeMode
	}
	return ThemeMode_THEME_MODE_UNSPECIFIED
}

func (x *UserPreference) GetPreferenceSource() PreferenceSource {
	if x != nil {
		return x.PreferenceSource
	}
	return PreferenceSource_PREFERENCE_SOURCE_UNSPECIFIED
}

func (x *UserPreference) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetUserPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferenceRequest) Reset() {
	*x = GetUserPreferenceRequest{}
	mi := &file_rpc_v1_preference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferenceRequest) ProtoMessage() {}

func (x *GetUserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{1}
}

type GetUserPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *UserPreference        `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"` // Current preference settings or defaults
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`        // True if preference record exists, false if returning defaults
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferenceResponse) Reset() {
	*x = GetUserPreferenceResponse{}
	mi := &file_rpc_v1_preference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferenceResponse) ProtoMessage() {}

func (x *GetUserPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferenceResponse.ProtoReflect.Descriptor instead.
func (*GetUserPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPreferenceResponse) GetPreference() *UserPreference {
	if x != nil {
		return x.Preference
	}
	return nil
}

func (x *GetUserPreferenceResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UpdateUserPreferenceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ThemeMode        ThemeMode              `protobuf:"varint,1,opt,name=theme_mode,json=themeMode,proto3,enum=rpc.v1.ThemeMode" json:"theme_mode,omitempty"`                             // New theme mode
	PreferenceSource PreferenceSource       `protobuf:"varint,2,opt,name=preference_source,json=preferenceSource,proto3,enum=rpc.v1.PreferenceSource" json:"preference_source,omitempty"` // How the theme was selected
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserPreferenceRequest) Reset() {
	*x = UpdateUserPreferenceRequest{}
	mi := &file_rpc_v1_preference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferenceRequest) ProtoMessage() {}

func (x *UpdateUserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserPreferenceRequest) GetThemeMode() ThemeMode {
	if x != nil {
		return x.ThemeMode
	}
	return ThemeMode_THEME_MODE_UNSPECIFIED
}

func (x *UpdateUserPreferenceRequest) GetPreferenceSource() PreferenceSource {
	if x != nil {
		return x.PreferenceSource
	}
	return PreferenceSource_PREFERENCE_SOURCE_UNSPECIFIED
}

type UpdateUserPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *UserPreference        `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"` // Updated preference settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferenceResponse) Reset() {
	*x = UpdateUserPreferenceResponse{}
	mi := &file_rpc_v1_preference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferenceResponse) ProtoMessage() {}

func (x *UpdateUserPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferenceResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserPreferenceResponse) GetPreference() *UserPreference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type ResetUserPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPreferenceRequest) Reset() {
	*x = ResetUserPreferenceRequest{}
	mi := &file_rpc_v1_preference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPreferenceRequest) ProtoMessage() {}

func (x *ResetUserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*ResetUserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{5}
}

type ResetUserPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if reset was successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPreferenceResponse) Reset() {
	*x = ResetUserPreferenceResponse{}
	mi := &file_rpc_v1_preference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPreferenceResponse) ProtoMessage() {}

func (x *ResetUserPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_preference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPreferenceResponse.ProtoReflect.Descriptor instead.
func (*ResetUserPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_preference_proto_rawDescGZIP(), []int{6}
}

func (x *ResetUserPreferenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_v1_preference_proto protoreflect.FileDescriptor

const file_rpc_v1_preference_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/v1/preference.proto\x12\x06rpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11rpc/v1/rbac.proto\"\xf5\x01\n" +
	"\x0eUserPreference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\x120\n" +
	"\n" +
	"theme_mode\x18\x03 \x01(\x0e2\x11.rpc.v1.ThemeModeR\tthemeMode\x12E\n" +
	"\x11preference_source\x18\x04 \x01(\x0e2\x18.rpc.v1.PreferenceSourceR\x10preferenceSource\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1a\n" +
	"\x18GetUserPreferenceRequest\"k\n" +
	"\x19GetUserPreferenceResponse\x126\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x16.rpc.v1.UserPreferenceR\n" +
	"preference\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"\x96\x01\n" +
	"\x1bUpdateUserPreferenceRequest\x120\n" +
	"\n" +
	"theme_mode\x18\x01 \x01(\x0e2\x11.rpc.v1.ThemeModeR\tthemeMode\x12E\n" +
	"\x11preference_source\x18\x02 \x01(\x0e2\x18.rpc.v1.PreferenceSourceR\x10preferenceSource\"V\n" +
	"\x1cUpdateUserPreferenceResponse\x126\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x16.rpc.v1.UserPreferenceR\n" +
	"preference\"\x1c\n" +
	"\x1aResetUserPreferenceRequest\"7\n" +
	"\x1bResetUserPreferenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*R\n" +
	"\tThemeMode\x12\x1a\n" +
	"\x16THEME_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10THEME_MODE_LIGHT\x10\x01\x12\x13\n" +
	"\x0fTHEME_MODE_DARK\x10\x02*u\n" +
	"\x10PreferenceSource\x12!\n" +
	"\x1dPREFERENCE_SOURCE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PREFERENCE_SOURCE_MANUAL\x10\x01\x12 \n" +
	"\x1cPREFERENCE_SOURCE_OS_DEFAULT\x10\x022\xe6\x02\n" +
	"\x11PreferenceService\x12i\n" +
	"\x11GetUserPreference\x12 .rpc.v1.GetUserPreferenceRequest\x1a!.rpc.v1.GetUserPreferenceResponse\"\x0f\x82\xf9+\v\n" +
	"\tpref.view\x12t\n" +
	"\x14UpdateUserPreference\x12#.rpc.v1.UpdateUserPreferenceRequest\x1a$.rpc.v1.UpdateUserPreferenceResponse\"\x11\x82\xf9+\r\n" +
	"\vpref.update\x12p\n" +
	"\x13ResetUserPreference\x12\".rpc.v1.ResetUserPreferenceRequest\x1a#.rpc.v1.ResetUserPreferenceResponse\"\x10\x82\xf9+\f\n" +
	"\n" +
	"pref.resetB\x8a\x01\n" +
	"\n" +
	"com.rpc.v1B\x0fPreferenceProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_preference_proto_rawDescOnce sync.Once
	file_rpc_v1_preference_proto_rawDescData []byte
)

func file_rpc_v1_preference_proto_rawDescGZIP() []byte {
	file_rpc_v1_preference_proto_rawDescOnce.Do(func() {
		file_rpc_v1_preference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_preference_proto_rawDesc), len(file_rpc_v1_preference_proto_rawDesc)))
	})
	return file_rpc_v1_preference_proto_rawDescData
}

var file_rpc_v1_preference_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_v1_preference_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_v1_preference_proto_goTypes = []any{
	(ThemeMode)(0),                       // 0: rpc.v1.ThemeMode
	(PreferenceSource)(0),                // 1: rpc.v1.PreferenceSource
	(*UserPreference)(nil),               // 2: rpc.v1.UserPreference
	(*GetUserPreferenceRequest)(nil),     // 3: rpc.v1.GetUserPreferenceRequest
	(*GetUserPreferenceResponse)(nil),    // 4: rpc.v1.GetUserPreferenceResponse
	(*UpdateUserPreferenceRequest)(nil),  // 5: rpc.v1.UpdateUserPreferenceRequest
	(*UpdateUserPreferenceResponse)(nil), // 6: rpc.v1.UpdateUserPreferenceResponse
	(*ResetUserPreferenceRequest)(nil),   // 7: rpc.v1.ResetUserPreferenceRequest
	(*ResetUserPreferenceResponse)(nil),  // 8: rpc.v1.ResetUserPreferenceResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_rpc_v1_preference_proto_depIdxs = []int32{
	0,  // 0: rpc.v1.UserPreference.theme_mode:type_name -> rpc.v1.ThemeMode
	1,  // 1: rpc.v1.UserPreference.preference_source:type_name -> rpc.v1.PreferenceSource
	9,  // 2: rpc.v1.UserPreference.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: rpc.v1.GetUserPreferenceResponse.preference:type_name -> rpc.v1.UserPreference
	0,  // 4: rpc.v1.UpdateUserPreferenceRequest.theme_mode:type_name -> rpc.v1.ThemeMode
	1,  // 5: rpc.v1.UpdateUserPreferenceRequest.preference_source:type_name -> rpc.v1.PreferenceSource
	2,  // 6: rpc.v1.UpdateUserPreferenceResponse.preference:type_name -> rpc.v1.UserPreference
	3,  // 7: rpc.v1.PreferenceService.GetUserPreference:input_type -> rpc.v1.GetUserPreferenceRequest
	5,  // 8: rpc.v1.PreferenceService.UpdateUserPreference:input_type -> rpc.v1.UpdateUserPreferenceRequest
	7,  // 9: rpc.v1.PreferenceService.ResetUserPreference:input_type -> rpc.v1.ResetUserPreferenceRequest
	4,  // 10: rpc.v1.PreferenceService.GetUserPreference:output_type -> rpc.v1.GetUserPreferenceResponse
	6,  // 11: rpc.v1.PreferenceService.UpdateUserPreference:output_type -> rpc.v1.UpdateUserPreferenceResponse
	8,  // 12: rpc.v1.PreferenceService.ResetUserPreference:output_type -> rpc.v1.ResetUserPreferenceResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_v1_preference_proto_init() }
func file_rpc_v1_preference_proto_init() {
	if File_rpc_v1_preference_proto != nil {
		return
	}
	file_rpc_v1_rbac_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_preference_proto_rawDesc), len(file_rpc_v1_preference_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_preference_proto_goTypes,
		DependencyIndexes: file_rpc_v1_preference_proto_depIdxs,
		EnumInfos:         file_rpc_v1_preference_proto_enumTypes,
		MessageInfos:      file_rpc_v1_preference_proto_msgTypes,
	}.Build()
	File_rpc_v1_preference_proto = out.File
	file_rpc_v1_preference_proto_goTypes = nil
	file_rpc_v1_preference_proto_depIdxs = nil
}
