// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/rbac.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PermissionBasedAccessControl replaces the former RoleBasedAccessControl.
// Each RPC method declares required permissions via this option.
// Semantics: user needs ANY ONE of the listed permissions (OR logic).
// Empty required_permissions + allow_unauthenticated=false means "any authenticated user".
type PermissionBasedAccessControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Permission strings required for access (OR semantics).
	// Format: "<domain>.<action>" (e.g., "chat.sendMessage").
	RequiredPermissions []string `protobuf:"bytes,1,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	// If true, bypasses all authentication and permission checks.
	AllowUnauthenticated bool `protobuf:"varint,2,opt,name=allow_unauthenticated,json=allowUnauthenticated,proto3" json:"allow_unauthenticated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PermissionBasedAccessControl) Reset() {
	*x = PermissionBasedAccessControl{}
	mi := &file_rpc_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionBasedAccessControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionBasedAccessControl) ProtoMessage() {}

func (x *PermissionBasedAccessControl) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionBasedAccessControl.ProtoReflect.Descriptor instead.
func (*PermissionBasedAccessControl) Descriptor() ([]byte, []int) {
	return file_rpc_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionBasedAccessControl) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *PermissionBasedAccessControl) GetAllowUnauthenticated() bool {
	if x != nil {
		return x.AllowUnauthenticated
	}
	return false
}

var file_rpc_v1_rbac_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*PermissionBasedAccessControl)(nil),
		Field:         90000,
		Name:          "rpc.v1.access_control",
		Tag:           "bytes,90000,opt,name=access_control",
		Filename:      "rpc/v1/rbac.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional rpc.v1.PermissionBasedAccessControl access_control = 90000;
	E_AccessControl = &file_rpc_v1_rbac_proto_extTypes[0]
)

var File_rpc_v1_rbac_proto protoreflect.FileDescriptor

const file_rpc_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/v1/rbac.proto\x12\x06rpc.v1\x1a google/protobuf/descriptor.proto\"\x86\x01\n" +
	"\x1cPermissionBasedAccessControl\x121\n" +
	"\x14required_permissions\x18\x01 \x03(\tR\x13requiredPermissions\x123\n" +
	"\x15allow_unauthenticated\x18\x02 \x01(\bR\x14allowUnauthenticated:p\n" +
	"\x0eaccess_control\x12\x1e.google.protobuf.MethodOptions\x18\x90\xbf\x05 \x01(\v2$.rpc.v1.PermissionBasedAccessControlR\raccessControl\x88\x01\x01B\x84\x01\n" +
	"\n" +
	"com.rpc.v1B\tRbacProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_rbac_proto_rawDescOnce sync.Once
	file_rpc_v1_rbac_proto_rawDescData []byte
)

func file_rpc_v1_rbac_proto_rawDescGZIP() []byte {
	file_rpc_v1_rbac_proto_rawDescOnce.Do(func() {
		file_rpc_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_rbac_proto_rawDesc), len(file_rpc_v1_rbac_proto_rawDesc)))
	})
	return file_rpc_v1_rbac_proto_rawDescData
}

var file_rpc_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_v1_rbac_proto_goTypes = []any{
	(*PermissionBasedAccessControl)(nil), // 0: rpc.v1.PermissionBasedAccessControl
	(*descriptorpb.MethodOptions)(nil),   // 1: google.protobuf.MethodOptions
}
var file_rpc_v1_rbac_proto_depIdxs = []int32{
	1, // 0: rpc.v1.access_control:extendee -> google.protobuf.MethodOptions
	0, // 1: rpc.v1.access_control:type_name -> rpc.v1.PermissionBasedAccessControl
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_v1_rbac_proto_init() }
func file_rpc_v1_rbac_proto_init() {
	if File_rpc_v1_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_rbac_proto_rawDesc), len(file_rpc_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rpc_v1_rbac_proto_goTypes,
		DependencyIndexes: file_rpc_v1_rbac_proto_depIdxs,
		MessageInfos:      file_rpc_v1_rbac_proto_msgTypes,
		ExtensionInfos:    file_rpc_v1_rbac_proto_extTypes,
	}.Build()
	File_rpc_v1_rbac_proto = out.File
	file_rpc_v1_rbac_proto_goTypes = nil
	file_rpc_v1_rbac_proto_depIdxs = nil
}
