// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/tour.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The client platform asking for the tour. Drives the web-only stop substitution.
type TourPlatform int32

const (
	TourPlatform_TOUR_PLATFORM_UNSPECIFIED TourPlatform = 0 // Invalid; rejected with invalid_argument
	TourPlatform_TOUR_PLATFORM_WEB         TourPlatform = 1
	TourPlatform_TOUR_PLATFORM_MOBILE      TourPlatform = 2
)

// Enum value maps for TourPlatform.
var (
	TourPlatform_name = map[int32]string{
		0: "TOUR_PLATFORM_UNSPECIFIED",
		1: "TOUR_PLATFORM_WEB",
		2: "TOUR_PLATFORM_MOBILE",
	}
	TourPlatform_value = map[string]int32{
		"TOUR_PLATFORM_UNSPECIFIED": 0,
		"TOUR_PLATFORM_WEB":         1,
		"TOUR_PLATFORM_MOBILE":      2,
	}
)

func (x TourPlatform) Enum() *TourPlatform {
	p := new(TourPlatform)
	*p = x
	return p
}

func (x TourPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_tour_proto_enumTypes[0].Descriptor()
}

func (TourPlatform) Type() protoreflect.EnumType {
	return &file_rpc_v1_tour_proto_enumTypes[0]
}

func (x TourPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourPlatform.Descriptor instead.
func (TourPlatform) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{0}
}

// Which of the two tours the caller is served. Decided by the server from the caller's
// permission set; the client cannot ask for the other one.
type TourAudience int32

const (
	TourAudience_TOUR_AUDIENCE_UNSPECIFIED   TourAudience = 0
	TourAudience_TOUR_AUDIENCE_ADMINISTRATOR TourAudience = 1
	TourAudience_TOUR_AUDIENCE_WORKER        TourAudience = 2
)

// Enum value maps for TourAudience.
var (
	TourAudience_name = map[int32]string{
		0: "TOUR_AUDIENCE_UNSPECIFIED",
		1: "TOUR_AUDIENCE_ADMINISTRATOR",
		2: "TOUR_AUDIENCE_WORKER",
	}
	TourAudience_value = map[string]int32{
		"TOUR_AUDIENCE_UNSPECIFIED":   0,
		"TOUR_AUDIENCE_ADMINISTRATOR": 1,
		"TOUR_AUDIENCE_WORKER":        2,
	}
)

func (x TourAudience) Enum() *TourAudience {
	p := new(TourAudience)
	*p = x
	return p
}

func (x TourAudience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourAudience) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_tour_proto_enumTypes[1].Descriptor()
}

func (TourAudience) Type() protoreflect.EnumType {
	return &file_rpc_v1_tour_proto_enumTypes[1]
}

func (x TourAudience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourAudience.Descriptor instead.
func (TourAudience) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{1}
}

// Progress state. NOT_STARTED is the absence of a stored row, never a stored value.
type TourStatus int32

const (
	TourStatus_TOUR_STATUS_UNSPECIFIED TourStatus = 0
	TourStatus_TOUR_STATUS_NOT_STARTED TourStatus = 1 // no stored row
	TourStatus_TOUR_STATUS_IN_PROGRESS TourStatus = 2
	TourStatus_TOUR_STATUS_COMPLETED   TourStatus = 3
	TourStatus_TOUR_STATUS_DISMISSED   TourStatus = 4
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "TOUR_STATUS_UNSPECIFIED",
		1: "TOUR_STATUS_NOT_STARTED",
		2: "TOUR_STATUS_IN_PROGRESS",
		3: "TOUR_STATUS_COMPLETED",
		4: "TOUR_STATUS_DISMISSED",
	}
	TourStatus_value = map[string]int32{
		"TOUR_STATUS_UNSPECIFIED": 0,
		"TOUR_STATUS_NOT_STARTED": 1,
		"TOUR_STATUS_IN_PROGRESS": 2,
		"TOUR_STATUS_COMPLETED":   3,
		"TOUR_STATUS_DISMISSED":   4,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_tour_proto_enumTypes[2].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_tour_proto_enumTypes[2]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{2}
}

// The surface a stop points at. Each client maps this to its own route; a client MUST
// handle every value, enforced by a test on both clients (Constitution VIII).
type TourTarget int32

const (
	TourTarget_TOUR_TARGET_UNSPECIFIED TourTarget = 0
	TourTarget_TOUR_TARGET_NONE        TourTarget = 1 // no action button — used for web-only stops shown on mobile
	TourTarget_TOUR_TARGET_PEOPLE      TourTarget = 2
	TourTarget_TOUR_TARGET_PROJECTS    TourTarget = 3
	TourTarget_TOUR_TARGET_RITUALS     TourTarget = 4
	TourTarget_TOUR_TARGET_CHAT        TourTarget = 5
	TourTarget_TOUR_TARGET_CALENDAR    TourTarget = 6
	TourTarget_TOUR_TARGET_DOCS        TourTarget = 7
	TourTarget_TOUR_TARGET_TODAY       TourTarget = 8
	TourTarget_TOUR_TARGET_ALERTS      TourTarget = 9
	TourTarget_TOUR_TARGET_SEARCH      TourTarget = 10
)

// Enum value maps for TourTarget.
var (
	TourTarget_name = map[int32]string{
		0:  "TOUR_TARGET_UNSPECIFIED",
		1:  "TOUR_TARGET_NONE",
		2:  "TOUR_TARGET_PEOPLE",
		3:  "TOUR_TARGET_PROJECTS",
		4:  "TOUR_TARGET_RITUALS",
		5:  "TOUR_TARGET_CHAT",
		6:  "TOUR_TARGET_CALENDAR",
		7:  "TOUR_TARGET_DOCS",
		8:  "TOUR_TARGET_TODAY",
		9:  "TOUR_TARGET_ALERTS",
		10: "TOUR_TARGET_SEARCH",
	}
	TourTarget_value = map[string]int32{
		"TOUR_TARGET_UNSPECIFIED": 0,
		"TOUR_TARGET_NONE":        1,
		"TOUR_TARGET_PEOPLE":      2,
		"TOUR_TARGET_PROJECTS":    3,
		"TOUR_TARGET_RITUALS":     4,
		"TOUR_TARGET_CHAT":        5,
		"TOUR_TARGET_CALENDAR":    6,
		"TOUR_TARGET_DOCS":        7,
		"TOUR_TARGET_TODAY":       8,
		"TOUR_TARGET_ALERTS":      9,
		"TOUR_TARGET_SEARCH":      10,
	}
)

func (x TourTarget) Enum() *TourTarget {
	p := new(TourTarget)
	*p = x
	return p
}

func (x TourTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_tour_proto_enumTypes[3].Descriptor()
}

func (TourTarget) Type() protoreflect.EnumType {
	return &file_rpc_v1_tour_proto_enumTypes[3]
}

func (x TourTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourTarget.Descriptor instead.
func (TourTarget) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{3}
}

// One card in the sequence, already filtered and platform-adapted.
type TourStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // stable id, also the client testID suffix
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                  // already substituted for platform
	ActionLabel   string                 `protobuf:"bytes,4,opt,name=action_label,json=actionLabel,proto3" json:"action_label,omitempty"` // empty when target is TOUR_TARGET_NONE
	Target        TourTarget             `protobuf:"varint,5,opt,name=target,proto3,enum=rpc.v1.TourTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourStop) Reset() {
	*x = TourStop{}
	mi := &file_rpc_v1_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourStop) ProtoMessage() {}

func (x *TourStop) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourStop.ProtoReflect.Descriptor instead.
func (*TourStop) Descriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{0}
}

func (x *TourStop) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TourStop) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TourStop) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TourStop) GetActionLabel() string {
	if x != nil {
		return x.ActionLabel
	}
	return ""
}

func (x *TourStop) GetTarget() TourTarget {
	if x != nil {
		return x.Target
	}
	return TourTarget_TOUR_TARGET_UNSPECIFIED
}

type GetTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      TourPlatform           `protobuf:"varint,1,opt,name=platform,proto3,enum=rpc.v1.TourPlatform" json:"platform,omitempty"` // required; UNSPECIFIED is rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourRequest) Reset() {
	*x = GetTourRequest{}
	mi := &file_rpc_v1_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourRequest) ProtoMessage() {}

func (x *GetTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourRequest.ProtoReflect.Descriptor instead.
func (*GetTourRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourRequest) GetPlatform() TourPlatform {
	if x != nil {
		return x.Platform
	}
	return TourPlatform_TOUR_PLATFORM_UNSPECIFIED
}

type GetTourResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Audience       TourAudience           `protobuf:"varint,1,opt,name=audience,proto3,enum=rpc.v1.TourAudience" json:"audience,omitempty"`
	TourId         string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"` // "administrator" | "worker"
	ContentVersion string                 `protobuf:"bytes,3,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	Stops          []*TourStop            `protobuf:"bytes,4,rep,name=stops,proto3" json:"stops,omitempty"` // already filtered and adapted; may be shorter than the definition
	Status         TourStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=rpc.v1.TourStatus" json:"status,omitempty"`
	CurrentStop    int32                  `protobuf:"varint,6,opt,name=current_stop,json=currentStop,proto3" json:"current_stop,omitempty"` // index into `stops`, clamped to it; 0 when not started
	ShouldOffer    bool                   `protobuf:"varint,7,opt,name=should_offer,json=shouldOffer,proto3" json:"should_offer,omitempty"` // true only when status is NOT_STARTED or IN_PROGRESS
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTourResponse) Reset() {
	*x = GetTourResponse{}
	mi := &file_rpc_v1_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourResponse) ProtoMessage() {}

func (x *GetTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourResponse.ProtoReflect.Descriptor instead.
func (*GetTourResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{2}
}

func (x *GetTourResponse) GetAudience() TourAudience {
	if x != nil {
		return x.Audience
	}
	return TourAudience_TOUR_AUDIENCE_UNSPECIFIED
}

func (x *GetTourResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *GetTourResponse) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *GetTourResponse) GetStops() []*TourStop {
	if x != nil {
		return x.Stops
	}
	return nil
}

func (x *GetTourResponse) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *GetTourResponse) GetCurrentStop() int32 {
	if x != nil {
		return x.CurrentStop
	}
	return 0
}

func (x *GetTourResponse) GetShouldOffer() bool {
	if x != nil {
		return x.ShouldOffer
	}
	return false
}

type UpdateTourProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TourStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.v1.TourStatus" json:"status,omitempty"`       // IN_PROGRESS, COMPLETED or DISMISSED; NOT_STARTED is rejected
	CurrentStop   int32                  `protobuf:"varint,2,opt,name=current_stop,json=currentStop,proto3" json:"current_stop,omitempty"` // ignored unless status is IN_PROGRESS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourProgressRequest) Reset() {
	*x = UpdateTourProgressRequest{}
	mi := &file_rpc_v1_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourProgressRequest) ProtoMessage() {}

func (x *UpdateTourProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourProgressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTourProgressRequest) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *UpdateTourProgressRequest) GetCurrentStop() int32 {
	if x != nil {
		return x.CurrentStop
	}
	return 0
}

type UpdateTourProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TourStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.v1.TourStatus" json:"status,omitempty"`
	CurrentStop   int32                  `protobuf:"varint,2,opt,name=current_stop,json=currentStop,proto3" json:"current_stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourProgressResponse) Reset() {
	*x = UpdateTourProgressResponse{}
	mi := &file_rpc_v1_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourProgressResponse) ProtoMessage() {}

func (x *UpdateTourProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourProgressResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_tour_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTourProgressResponse) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *UpdateTourProgressResponse) GetCurrentStop() int32 {
	if x != nil {
		return x.CurrentStop
	}
	return 0
}

var File_rpc_v1_tour_proto protoreflect.FileDescriptor

const file_rpc_v1_tour_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/v1/tour.proto\x12\x06rpc.v1\x1a\x11rpc/v1/rbac.proto\"\x95\x01\n" +
	"\bTourStop\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12!\n" +
	"\faction_label\x18\x04 \x01(\tR\vactionLabel\x12*\n" +
	"\x06target\x18\x05 \x01(\x0e2\x12.rpc.v1.TourTargetR\x06target\"B\n" +
	"\x0eGetTourRequest\x120\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x14.rpc.v1.TourPlatformR\bplatform\"\x9f\x02\n" +
	"\x0fGetTourResponse\x120\n" +
	"\baudience\x18\x01 \x01(\x0e2\x14.rpc.v1.TourAudienceR\baudience\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12'\n" +
	"\x0fcontent_version\x18\x03 \x01(\tR\x0econtentVersion\x12&\n" +
	"\x05stops\x18\x04 \x03(\v2\x10.rpc.v1.TourStopR\x05stops\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.rpc.v1.TourStatusR\x06status\x12!\n" +
	"\fcurrent_stop\x18\x06 \x01(\x05R\vcurrentStop\x12!\n" +
	"\fshould_offer\x18\a \x01(\bR\vshouldOffer\"j\n" +
	"\x19UpdateTourProgressRequest\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.rpc.v1.TourStatusR\x06status\x12!\n" +
	"\fcurrent_stop\x18\x02 \x01(\x05R\vcurrentStop\"k\n" +
	"\x1aUpdateTourProgressResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.rpc.v1.TourStatusR\x06status\x12!\n" +
	"\fcurrent_stop\x18\x02 \x01(\x05R\vcurrentStop*^\n" +
	"\fTourPlatform\x12\x1d\n" +
	"\x19TOUR_PLATFORM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOUR_PLATFORM_WEB\x10\x01\x12\x18\n" +
	"\x14TOUR_PLATFORM_MOBILE\x10\x02*h\n" +
	"\fTourAudience\x12\x1d\n" +
	"\x19TOUR_AUDIENCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTOUR_AUDIENCE_ADMINISTRATOR\x10\x01\x12\x18\n" +
	"\x14TOUR_AUDIENCE_WORKER\x10\x02*\x99\x01\n" +
	"\n" +
	"TourStatus\x12\x1b\n" +
	"\x17TOUR_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOUR_STATUS_NOT_STARTED\x10\x01\x12\x1b\n" +
	"\x17TOUR_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TOUR_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15TOUR_STATUS_DISMISSED\x10\x04*\x97\x02\n" +
	"\n" +
	"TourTarget\x12\x1b\n" +
	"\x17TOUR_TARGET_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TOUR_TARGET_NONE\x10\x01\x12\x16\n" +
	"\x12TOUR_TARGET_PEOPLE\x10\x02\x12\x18\n" +
	"\x14TOUR_TARGET_PROJECTS\x10\x03\x12\x17\n" +
	"\x13TOUR_TARGET_RITUALS\x10\x04\x12\x14\n" +
	"\x10TOUR_TARGET_CHAT\x10\x05\x12\x18\n" +
	"\x14TOUR_TARGET_CALENDAR\x10\x06\x12\x14\n" +
	"\x10TOUR_TARGET_DOCS\x10\a\x12\x15\n" +
	"\x11TOUR_TARGET_TODAY\x10\b\x12\x16\n" +
	"\x12TOUR_TARGET_ALERTS\x10\t\x12\x16\n" +
	"\x12TOUR_TARGET_SEARCH\x10\n" +
	"2\xca\x01\n" +
	"\vTourService\x12K\n" +
	"\aGetTour\x12\x16.rpc.v1.GetTourRequest\x1a\x17.rpc.v1.GetTourResponse\"\x0f\x82\xf9+\v\n" +
	"\ttour.view\x12n\n" +
	"\x12UpdateTourProgress\x12!.rpc.v1.UpdateTourProgressRequest\x1a\".rpc.v1.UpdateTourProgressResponse\"\x11\x82\xf9+\r\n" +
	"\vtour.updateB\x84\x01\n" +
	"\n" +
	"com.rpc.v1B\tTourProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_tour_proto_rawDescOnce sync.Once
	file_rpc_v1_tour_proto_rawDescData []byte
)

func file_rpc_v1_tour_proto_rawDescGZIP() []byte {
	file_rpc_v1_tour_proto_rawDescOnce.Do(func() {
		file_rpc_v1_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_tour_proto_rawDesc), len(file_rpc_v1_tour_proto_rawDesc)))
	})
	return file_rpc_v1_tour_proto_rawDescData
}

var file_rpc_v1_tour_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rpc_v1_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_v1_tour_proto_goTypes = []any{
	(TourPlatform)(0),                  // 0: rpc.v1.TourPlatform
	(TourAudience)(0),                  // 1: rpc.v1.TourAudience
	(TourStatus)(0),                    // 2: rpc.v1.TourStatus
	(TourTarget)(0),                    // 3: rpc.v1.TourTarget
	(*TourStop)(nil),                   // 4: rpc.v1.TourStop
	(*GetTourRequest)(nil),             // 5: rpc.v1.GetTourRequest
	(*GetTourResponse)(nil),            // 6: rpc.v1.GetTourResponse
	(*UpdateTourProgressRequest)(nil),  // 7: rpc.v1.UpdateTourProgressRequest
	(*UpdateTourProgressResponse)(nil), // 8: rpc.v1.UpdateTourProgressResponse
}
var file_rpc_v1_tour_proto_depIdxs = []int32{
	3, // 0: rpc.v1.TourStop.target:type_name -> rpc.v1.TourTarget
	0, // 1: rpc.v1.GetTourRequest.platform:type_name -> rpc.v1.TourPlatform
	1, // 2: rpc.v1.GetTourResponse.audience:type_name -> rpc.v1.TourAudience
	4, // 3: rpc.v1.GetTourResponse.stops:type_name -> rpc.v1.TourStop
	2, // 4: rpc.v1.GetTourResponse.status:type_name -> rpc.v1.TourStatus
	2, // 5: rpc.v1.UpdateTourProgressRequest.status:type_name -> rpc.v1.TourStatus
	2, // 6: rpc.v1.UpdateTourProgressResponse.status:type_name -> rpc.v1.TourStatus
	5, // 7: rpc.v1.TourService.GetTour:input_type -> rpc.v1.GetTourRequest
	7, // 8: rpc.v1.TourService.UpdateTourProgress:input_type -> rpc.v1.UpdateTourProgressRequest
	6, // 9: rpc.v1.TourService.GetTour:output_type -> rpc.v1.GetTourResponse
	8, // 10: rpc.v1.TourService.UpdateTourProgress:output_type -> rpc.v1.UpdateTourProgressResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_v1_tour_proto_init() }
func file_rpc_v1_tour_proto_init() {
	if File_rpc_v1_tour_proto != nil {
		return
	}
	file_rpc_v1_rbac_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_tour_proto_rawDesc), len(file_rpc_v1_tour_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_tour_proto_goTypes,
		DependencyIndexes: file_rpc_v1_tour_proto_depIdxs,
		EnumInfos:         file_rpc_v1_tour_proto_enumTypes,
		MessageInfos:      file_rpc_v1_tour_proto_msgTypes,
	}.Build()
	File_rpc_v1_tour_proto = out.File
	file_rpc_v1_tour_proto_goTypes = nil
	file_rpc_v1_tour_proto_depIdxs = nil
}
