// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rpc/v1/voice.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceCallState int32

const (
	VoiceCallState_VOICE_CALL_STATE_UNSPECIFIED VoiceCallState = 0
	VoiceCallState_VOICE_CALL_STATE_RINGING     VoiceCallState = 1
	VoiceCallState_VOICE_CALL_STATE_ACTIVE      VoiceCallState = 2
	VoiceCallState_VOICE_CALL_STATE_ENDING      VoiceCallState = 3
	VoiceCallState_VOICE_CALL_STATE_ENDED       VoiceCallState = 4
)

// Enum value maps for VoiceCallState.
var (
	VoiceCallState_name = map[int32]string{
		0: "VOICE_CALL_STATE_UNSPECIFIED",
		1: "VOICE_CALL_STATE_RINGING",
		2: "VOICE_CALL_STATE_ACTIVE",
		3: "VOICE_CALL_STATE_ENDING",
		4: "VOICE_CALL_STATE_ENDED",
	}
	VoiceCallState_value = map[string]int32{
		"VOICE_CALL_STATE_UNSPECIFIED": 0,
		"VOICE_CALL_STATE_RINGING":     1,
		"VOICE_CALL_STATE_ACTIVE":      2,
		"VOICE_CALL_STATE_ENDING":      3,
		"VOICE_CALL_STATE_ENDED":       4,
	}
)

func (x VoiceCallState) Enum() *VoiceCallState {
	p := new(VoiceCallState)
	*p = x
	return p
}

func (x VoiceCallState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceCallState) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[0].Descriptor()
}

func (VoiceCallState) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[0]
}

func (x VoiceCallState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceCallState.Descriptor instead.
func (VoiceCallState) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{0}
}

type VoiceCallOutcome int32

const (
	VoiceCallOutcome_VOICE_CALL_OUTCOME_UNSPECIFIED VoiceCallOutcome = 0
	VoiceCallOutcome_VOICE_CALL_OUTCOME_ANSWERED    VoiceCallOutcome = 1
	VoiceCallOutcome_VOICE_CALL_OUTCOME_MISSED      VoiceCallOutcome = 2
	VoiceCallOutcome_VOICE_CALL_OUTCOME_DECLINED    VoiceCallOutcome = 3
	VoiceCallOutcome_VOICE_CALL_OUTCOME_CANCELLED   VoiceCallOutcome = 4
	VoiceCallOutcome_VOICE_CALL_OUTCOME_COMPLETED   VoiceCallOutcome = 5
)

// Enum value maps for VoiceCallOutcome.
var (
	VoiceCallOutcome_name = map[int32]string{
		0: "VOICE_CALL_OUTCOME_UNSPECIFIED",
		1: "VOICE_CALL_OUTCOME_ANSWERED",
		2: "VOICE_CALL_OUTCOME_MISSED",
		3: "VOICE_CALL_OUTCOME_DECLINED",
		4: "VOICE_CALL_OUTCOME_CANCELLED",
		5: "VOICE_CALL_OUTCOME_COMPLETED",
	}
	VoiceCallOutcome_value = map[string]int32{
		"VOICE_CALL_OUTCOME_UNSPECIFIED": 0,
		"VOICE_CALL_OUTCOME_ANSWERED":    1,
		"VOICE_CALL_OUTCOME_MISSED":      2,
		"VOICE_CALL_OUTCOME_DECLINED":    3,
		"VOICE_CALL_OUTCOME_CANCELLED":   4,
		"VOICE_CALL_OUTCOME_COMPLETED":   5,
	}
)

func (x VoiceCallOutcome) Enum() *VoiceCallOutcome {
	p := new(VoiceCallOutcome)
	*p = x
	return p
}

func (x VoiceCallOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceCallOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[1].Descriptor()
}

func (VoiceCallOutcome) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[1]
}

func (x VoiceCallOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceCallOutcome.Descriptor instead.
func (VoiceCallOutcome) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{1}
}

type VoiceCallParticipantState int32

const (
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_UNSPECIFIED  VoiceCallParticipantState = 0
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_INVITED      VoiceCallParticipantState = 1
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_RINGING      VoiceCallParticipantState = 2
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_JOINING      VoiceCallParticipantState = 3
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_JOINED       VoiceCallParticipantState = 4
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_DISCONNECTED VoiceCallParticipantState = 5
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_LEFT         VoiceCallParticipantState = 6
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_DECLINED     VoiceCallParticipantState = 7
	VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_REMOVED      VoiceCallParticipantState = 8
)

// Enum value maps for VoiceCallParticipantState.
var (
	VoiceCallParticipantState_name = map[int32]string{
		0: "VOICE_CALL_PARTICIPANT_STATE_UNSPECIFIED",
		1: "VOICE_CALL_PARTICIPANT_STATE_INVITED",
		2: "VOICE_CALL_PARTICIPANT_STATE_RINGING",
		3: "VOICE_CALL_PARTICIPANT_STATE_JOINING",
		4: "VOICE_CALL_PARTICIPANT_STATE_JOINED",
		5: "VOICE_CALL_PARTICIPANT_STATE_DISCONNECTED",
		6: "VOICE_CALL_PARTICIPANT_STATE_LEFT",
		7: "VOICE_CALL_PARTICIPANT_STATE_DECLINED",
		8: "VOICE_CALL_PARTICIPANT_STATE_REMOVED",
	}
	VoiceCallParticipantState_value = map[string]int32{
		"VOICE_CALL_PARTICIPANT_STATE_UNSPECIFIED":  0,
		"VOICE_CALL_PARTICIPANT_STATE_INVITED":      1,
		"VOICE_CALL_PARTICIPANT_STATE_RINGING":      2,
		"VOICE_CALL_PARTICIPANT_STATE_JOINING":      3,
		"VOICE_CALL_PARTICIPANT_STATE_JOINED":       4,
		"VOICE_CALL_PARTICIPANT_STATE_DISCONNECTED": 5,
		"VOICE_CALL_PARTICIPANT_STATE_LEFT":         6,
		"VOICE_CALL_PARTICIPANT_STATE_DECLINED":     7,
		"VOICE_CALL_PARTICIPANT_STATE_REMOVED":      8,
	}
)

func (x VoiceCallParticipantState) Enum() *VoiceCallParticipantState {
	p := new(VoiceCallParticipantState)
	*p = x
	return p
}

func (x VoiceCallParticipantState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceCallParticipantState) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[2].Descriptor()
}

func (VoiceCallParticipantState) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[2]
}

func (x VoiceCallParticipantState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceCallParticipantState.Descriptor instead.
func (VoiceCallParticipantState) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{2}
}

type VoiceInviteResponse int32

const (
	VoiceInviteResponse_VOICE_INVITE_RESPONSE_UNSPECIFIED VoiceInviteResponse = 0
	VoiceInviteResponse_VOICE_INVITE_RESPONSE_ACCEPT      VoiceInviteResponse = 1
	VoiceInviteResponse_VOICE_INVITE_RESPONSE_DECLINE     VoiceInviteResponse = 2
)

// Enum value maps for VoiceInviteResponse.
var (
	VoiceInviteResponse_name = map[int32]string{
		0: "VOICE_INVITE_RESPONSE_UNSPECIFIED",
		1: "VOICE_INVITE_RESPONSE_ACCEPT",
		2: "VOICE_INVITE_RESPONSE_DECLINE",
	}
	VoiceInviteResponse_value = map[string]int32{
		"VOICE_INVITE_RESPONSE_UNSPECIFIED": 0,
		"VOICE_INVITE_RESPONSE_ACCEPT":      1,
		"VOICE_INVITE_RESPONSE_DECLINE":     2,
	}
)

func (x VoiceInviteResponse) Enum() *VoiceInviteResponse {
	p := new(VoiceInviteResponse)
	*p = x
	return p
}

func (x VoiceInviteResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceInviteResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[3].Descriptor()
}

func (VoiceInviteResponse) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[3]
}

func (x VoiceInviteResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceInviteResponse.Descriptor instead.
func (VoiceInviteResponse) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{3}
}

type VoiceInvitationStatus int32

const (
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_UNSPECIFIED VoiceInvitationStatus = 0
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_PENDING     VoiceInvitationStatus = 1
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_ACCEPTED    VoiceInvitationStatus = 2
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_DECLINED    VoiceInvitationStatus = 3
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_EXPIRED     VoiceInvitationStatus = 4
	VoiceInvitationStatus_VOICE_INVITATION_STATUS_REVOKED     VoiceInvitationStatus = 5
)

// Enum value maps for VoiceInvitationStatus.
var (
	VoiceInvitationStatus_name = map[int32]string{
		0: "VOICE_INVITATION_STATUS_UNSPECIFIED",
		1: "VOICE_INVITATION_STATUS_PENDING",
		2: "VOICE_INVITATION_STATUS_ACCEPTED",
		3: "VOICE_INVITATION_STATUS_DECLINED",
		4: "VOICE_INVITATION_STATUS_EXPIRED",
		5: "VOICE_INVITATION_STATUS_REVOKED",
	}
	VoiceInvitationStatus_value = map[string]int32{
		"VOICE_INVITATION_STATUS_UNSPECIFIED": 0,
		"VOICE_INVITATION_STATUS_PENDING":     1,
		"VOICE_INVITATION_STATUS_ACCEPTED":    2,
		"VOICE_INVITATION_STATUS_DECLINED":    3,
		"VOICE_INVITATION_STATUS_EXPIRED":     4,
		"VOICE_INVITATION_STATUS_REVOKED":     5,
	}
)

func (x VoiceInvitationStatus) Enum() *VoiceInvitationStatus {
	p := new(VoiceInvitationStatus)
	*p = x
	return p
}

func (x VoiceInvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceInvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[4].Descriptor()
}

func (VoiceInvitationStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[4]
}

func (x VoiceInvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceInvitationStatus.Descriptor instead.
func (VoiceInvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{4}
}

type VoiceArtifactType int32

const (
	VoiceArtifactType_VOICE_ARTIFACT_TYPE_UNSPECIFIED VoiceArtifactType = 0
	VoiceArtifactType_VOICE_ARTIFACT_TYPE_RECORDING   VoiceArtifactType = 1
	VoiceArtifactType_VOICE_ARTIFACT_TYPE_TRANSCRIPT  VoiceArtifactType = 2
)

// Enum value maps for VoiceArtifactType.
var (
	VoiceArtifactType_name = map[int32]string{
		0: "VOICE_ARTIFACT_TYPE_UNSPECIFIED",
		1: "VOICE_ARTIFACT_TYPE_RECORDING",
		2: "VOICE_ARTIFACT_TYPE_TRANSCRIPT",
	}
	VoiceArtifactType_value = map[string]int32{
		"VOICE_ARTIFACT_TYPE_UNSPECIFIED": 0,
		"VOICE_ARTIFACT_TYPE_RECORDING":   1,
		"VOICE_ARTIFACT_TYPE_TRANSCRIPT":  2,
	}
)

func (x VoiceArtifactType) Enum() *VoiceArtifactType {
	p := new(VoiceArtifactType)
	*p = x
	return p
}

func (x VoiceArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[5].Descriptor()
}

func (VoiceArtifactType) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[5]
}

func (x VoiceArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceArtifactType.Descriptor instead.
func (VoiceArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{5}
}

type VoiceArtifactStatus int32

const (
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_UNSPECIFIED VoiceArtifactStatus = 0
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_PENDING     VoiceArtifactStatus = 1
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_PROCESSING  VoiceArtifactStatus = 2
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_READY       VoiceArtifactStatus = 3
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_UNAVAILABLE VoiceArtifactStatus = 4
	VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_FAILED      VoiceArtifactStatus = 5
)

// Enum value maps for VoiceArtifactStatus.
var (
	VoiceArtifactStatus_name = map[int32]string{
		0: "VOICE_ARTIFACT_STATUS_UNSPECIFIED",
		1: "VOICE_ARTIFACT_STATUS_PENDING",
		2: "VOICE_ARTIFACT_STATUS_PROCESSING",
		3: "VOICE_ARTIFACT_STATUS_READY",
		4: "VOICE_ARTIFACT_STATUS_UNAVAILABLE",
		5: "VOICE_ARTIFACT_STATUS_FAILED",
	}
	VoiceArtifactStatus_value = map[string]int32{
		"VOICE_ARTIFACT_STATUS_UNSPECIFIED": 0,
		"VOICE_ARTIFACT_STATUS_PENDING":     1,
		"VOICE_ARTIFACT_STATUS_PROCESSING":  2,
		"VOICE_ARTIFACT_STATUS_READY":       3,
		"VOICE_ARTIFACT_STATUS_UNAVAILABLE": 4,
		"VOICE_ARTIFACT_STATUS_FAILED":      5,
	}
)

func (x VoiceArtifactStatus) Enum() *VoiceArtifactStatus {
	p := new(VoiceArtifactStatus)
	*p = x
	return p
}

func (x VoiceArtifactStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceArtifactStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[6].Descriptor()
}

func (VoiceArtifactStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[6]
}

func (x VoiceArtifactStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceArtifactStatus.Descriptor instead.
func (VoiceArtifactStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{6}
}

type VoiceMessageStatus int32

const (
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_UNSPECIFIED VoiceMessageStatus = 0
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_REQUESTED   VoiceMessageStatus = 1
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_UPLOADING   VoiceMessageStatus = 2
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_POSTED      VoiceMessageStatus = 3
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_FAILED      VoiceMessageStatus = 4
	VoiceMessageStatus_VOICE_MESSAGE_STATUS_CANCELLED   VoiceMessageStatus = 5
)

// Enum value maps for VoiceMessageStatus.
var (
	VoiceMessageStatus_name = map[int32]string{
		0: "VOICE_MESSAGE_STATUS_UNSPECIFIED",
		1: "VOICE_MESSAGE_STATUS_REQUESTED",
		2: "VOICE_MESSAGE_STATUS_UPLOADING",
		3: "VOICE_MESSAGE_STATUS_POSTED",
		4: "VOICE_MESSAGE_STATUS_FAILED",
		5: "VOICE_MESSAGE_STATUS_CANCELLED",
	}
	VoiceMessageStatus_value = map[string]int32{
		"VOICE_MESSAGE_STATUS_UNSPECIFIED": 0,
		"VOICE_MESSAGE_STATUS_REQUESTED":   1,
		"VOICE_MESSAGE_STATUS_UPLOADING":   2,
		"VOICE_MESSAGE_STATUS_POSTED":      3,
		"VOICE_MESSAGE_STATUS_FAILED":      4,
		"VOICE_MESSAGE_STATUS_CANCELLED":   5,
	}
)

func (x VoiceMessageStatus) Enum() *VoiceMessageStatus {
	p := new(VoiceMessageStatus)
	*p = x
	return p
}

func (x VoiceMessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceMessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_v1_voice_proto_enumTypes[7].Descriptor()
}

func (VoiceMessageStatus) Type() protoreflect.EnumType {
	return &file_rpc_v1_voice_proto_enumTypes[7]
}

func (x VoiceMessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceMessageStatus.Descriptor instead.
func (VoiceMessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{7}
}

type StartVoiceCallRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChannelId        string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	RequestRecording bool                   `protobuf:"varint,2,opt,name=request_recording,json=requestRecording,proto3" json:"request_recording,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartVoiceCallRequest) Reset() {
	*x = StartVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVoiceCallRequest) ProtoMessage() {}

func (x *StartVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*StartVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *StartVoiceCallRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *StartVoiceCallRequest) GetRequestRecording() bool {
	if x != nil {
		return x.RequestRecording
	}
	return false
}

type StartVoiceCallResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Call            *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	JoinCredentials *VoiceJoinCredentials  `protobuf:"bytes,2,opt,name=join_credentials,json=joinCredentials,proto3" json:"join_credentials,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartVoiceCallResponse) Reset() {
	*x = StartVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVoiceCallResponse) ProtoMessage() {}

func (x *StartVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*StartVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *StartVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *StartVoiceCallResponse) GetJoinCredentials() *VoiceJoinCredentials {
	if x != nil {
		return x.JoinCredentials
	}
	return nil
}

type GetActiveVoiceCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveVoiceCallRequest) Reset() {
	*x = GetActiveVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveVoiceCallRequest) ProtoMessage() {}

func (x *GetActiveVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*GetActiveVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveVoiceCallRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetActiveVoiceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	HasActiveCall bool                   `protobuf:"varint,2,opt,name=has_active_call,json=hasActiveCall,proto3" json:"has_active_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveVoiceCallResponse) Reset() {
	*x = GetActiveVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveVoiceCallResponse) ProtoMessage() {}

func (x *GetActiveVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*GetActiveVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *GetActiveVoiceCallResponse) GetHasActiveCall() bool {
	if x != nil {
		return x.HasActiveCall
	}
	return false
}

type JoinVoiceCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Which physical device is joining. Set by clients that present calls through the
	// operating system, so the answered_elsewhere wake that stops this person's other
	// phones is not also sent back to the one that answered — on iOS every call wake is
	// reported to CallKit as a new incoming call, so a wake sent to the answering device
	// rings it again. Empty from clients that do not present calls natively.
	DeviceIdentifier string `protobuf:"bytes,2,opt,name=device_identifier,json=deviceIdentifier,proto3" json:"device_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinVoiceCallRequest) Reset() {
	*x = JoinVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceCallRequest) ProtoMessage() {}

func (x *JoinVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*JoinVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{4}
}

func (x *JoinVoiceCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *JoinVoiceCallRequest) GetDeviceIdentifier() string {
	if x != nil {
		return x.DeviceIdentifier
	}
	return ""
}

type JoinVoiceCallResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Call            *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	JoinCredentials *VoiceJoinCredentials  `protobuf:"bytes,2,opt,name=join_credentials,json=joinCredentials,proto3" json:"join_credentials,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JoinVoiceCallResponse) Reset() {
	*x = JoinVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceCallResponse) ProtoMessage() {}

func (x *JoinVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*JoinVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{5}
}

func (x *JoinVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *JoinVoiceCallResponse) GetJoinCredentials() *VoiceJoinCredentials {
	if x != nil {
		return x.JoinCredentials
	}
	return nil
}

type LeaveVoiceCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Which physical device left. Excluded from the terminal wake fan-out for the same
	// reason as JoinVoiceCallRequest.device_identifier.
	DeviceIdentifier string `protobuf:"bytes,2,opt,name=device_identifier,json=deviceIdentifier,proto3" json:"device_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaveVoiceCallRequest) Reset() {
	*x = LeaveVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveVoiceCallRequest) ProtoMessage() {}

func (x *LeaveVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*LeaveVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveVoiceCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *LeaveVoiceCallRequest) GetDeviceIdentifier() string {
	if x != nil {
		return x.DeviceIdentifier
	}
	return ""
}

type LeaveVoiceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveVoiceCallResponse) Reset() {
	*x = LeaveVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveVoiceCallResponse) ProtoMessage() {}

func (x *LeaveVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*LeaveVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

type EndVoiceCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Which physical device ended the call. Excluded from the terminal wake fan-out for
	// the same reason as JoinVoiceCallRequest.device_identifier.
	DeviceIdentifier string `protobuf:"bytes,2,opt,name=device_identifier,json=deviceIdentifier,proto3" json:"device_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndVoiceCallRequest) Reset() {
	*x = EndVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndVoiceCallRequest) ProtoMessage() {}

func (x *EndVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*EndVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{8}
}

func (x *EndVoiceCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EndVoiceCallRequest) GetDeviceIdentifier() string {
	if x != nil {
		return x.DeviceIdentifier
	}
	return ""
}

type EndVoiceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndVoiceCallResponse) Reset() {
	*x = EndVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndVoiceCallResponse) ProtoMessage() {}

func (x *EndVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*EndVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{9}
}

func (x *EndVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

type InviteToVoiceCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	EmployeeIds   []string               `protobuf:"bytes,2,rep,name=employee_ids,json=employeeIds,proto3" json:"employee_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToVoiceCallRequest) Reset() {
	*x = InviteToVoiceCallRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToVoiceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToVoiceCallRequest) ProtoMessage() {}

func (x *InviteToVoiceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToVoiceCallRequest.ProtoReflect.Descriptor instead.
func (*InviteToVoiceCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{10}
}

func (x *InviteToVoiceCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InviteToVoiceCallRequest) GetEmployeeIds() []string {
	if x != nil {
		return x.EmployeeIds
	}
	return nil
}

type InviteToVoiceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Invitations   []*VoiceCallInvitation `protobuf:"bytes,2,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToVoiceCallResponse) Reset() {
	*x = InviteToVoiceCallResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToVoiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToVoiceCallResponse) ProtoMessage() {}

func (x *InviteToVoiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToVoiceCallResponse.ProtoReflect.Descriptor instead.
func (*InviteToVoiceCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{11}
}

func (x *InviteToVoiceCallResponse) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *InviteToVoiceCallResponse) GetInvitations() []*VoiceCallInvitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type RespondToVoiceCallInviteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InvitationId string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Response     VoiceInviteResponse    `protobuf:"varint,2,opt,name=response,proto3,enum=rpc.v1.VoiceInviteResponse" json:"response,omitempty"`
	// Which physical device answered or declined. Excluded from the terminal wake fan-out
	// for the same reason as JoinVoiceCallRequest.device_identifier.
	DeviceIdentifier string `protobuf:"bytes,3,opt,name=device_identifier,json=deviceIdentifier,proto3" json:"device_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RespondToVoiceCallInviteRequest) Reset() {
	*x = RespondToVoiceCallInviteRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToVoiceCallInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToVoiceCallInviteRequest) ProtoMessage() {}

func (x *RespondToVoiceCallInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToVoiceCallInviteRequest.ProtoReflect.Descriptor instead.
func (*RespondToVoiceCallInviteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{12}
}

func (x *RespondToVoiceCallInviteRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *RespondToVoiceCallInviteRequest) GetResponse() VoiceInviteResponse {
	if x != nil {
		return x.Response
	}
	return VoiceInviteResponse_VOICE_INVITE_RESPONSE_UNSPECIFIED
}

func (x *RespondToVoiceCallInviteRequest) GetDeviceIdentifier() string {
	if x != nil {
		return x.DeviceIdentifier
	}
	return ""
}

type RespondToVoiceCallInviteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Invitation      *VoiceCallInvitation   `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	JoinCredentials *VoiceJoinCredentials  `protobuf:"bytes,2,opt,name=join_credentials,json=joinCredentials,proto3" json:"join_credentials,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RespondToVoiceCallInviteResponse) Reset() {
	*x = RespondToVoiceCallInviteResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToVoiceCallInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToVoiceCallInviteResponse) ProtoMessage() {}

func (x *RespondToVoiceCallInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToVoiceCallInviteResponse.ProtoReflect.Descriptor instead.
func (*RespondToVoiceCallInviteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{13}
}

func (x *RespondToVoiceCallInviteResponse) GetInvitation() *VoiceCallInvitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

func (x *RespondToVoiceCallInviteResponse) GetJoinCredentials() *VoiceJoinCredentials {
	if x != nil {
		return x.JoinCredentials
	}
	return nil
}

type ListCallRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallRecordsRequest) Reset() {
	*x = ListCallRecordsRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallRecordsRequest) ProtoMessage() {}

func (x *ListCallRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListCallRecordsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{14}
}

func (x *ListCallRecordsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ListCallRecordsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListCallRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCallRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*VoiceCallRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallRecordsResponse) Reset() {
	*x = ListCallRecordsResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallRecordsResponse) ProtoMessage() {}

func (x *ListCallRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListCallRecordsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{15}
}

func (x *ListCallRecordsResponse) GetRecords() []*VoiceCallRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListCallRecordsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetCallRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRecordRequest) Reset() {
	*x = GetCallRecordRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRecordRequest) ProtoMessage() {}

func (x *GetCallRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRecordRequest.ProtoReflect.Descriptor instead.
func (*GetCallRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{16}
}

func (x *GetCallRecordRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetCallRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *VoiceCallRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRecordResponse) Reset() {
	*x = GetCallRecordResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRecordResponse) ProtoMessage() {}

func (x *GetCallRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRecordResponse.ProtoReflect.Descriptor instead.
func (*GetCallRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{17}
}

func (x *GetCallRecordResponse) GetRecord() *VoiceCallRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type RequestVoiceMessageUploadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ChannelId              string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ClientDeduplicationKey string                 `protobuf:"bytes,2,opt,name=client_deduplication_key,json=clientDeduplicationKey,proto3" json:"client_deduplication_key,omitempty"`
	Filename               string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType               string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes              int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ExpectedDurationMs     int64                  `protobuf:"varint,6,opt,name=expected_duration_ms,json=expectedDurationMs,proto3" json:"expected_duration_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestVoiceMessageUploadRequest) Reset() {
	*x = RequestVoiceMessageUploadRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoiceMessageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoiceMessageUploadRequest) ProtoMessage() {}

func (x *RequestVoiceMessageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoiceMessageUploadRequest.ProtoReflect.Descriptor instead.
func (*RequestVoiceMessageUploadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{18}
}

func (x *RequestVoiceMessageUploadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RequestVoiceMessageUploadRequest) GetClientDeduplicationKey() string {
	if x != nil {
		return x.ClientDeduplicationKey
	}
	return ""
}

func (x *RequestVoiceMessageUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RequestVoiceMessageUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RequestVoiceMessageUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RequestVoiceMessageUploadRequest) GetExpectedDurationMs() int64 {
	if x != nil {
		return x.ExpectedDurationMs
	}
	return 0
}

type RequestVoiceMessageUploadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VoiceMessageId string                 `protobuf:"bytes,1,opt,name=voice_message_id,json=voiceMessageId,proto3" json:"voice_message_id,omitempty"`
	FileId         string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadUrl      string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestVoiceMessageUploadResponse) Reset() {
	*x = RequestVoiceMessageUploadResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoiceMessageUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoiceMessageUploadResponse) ProtoMessage() {}

func (x *RequestVoiceMessageUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoiceMessageUploadResponse.ProtoReflect.Descriptor instead.
func (*RequestVoiceMessageUploadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{19}
}

func (x *RequestVoiceMessageUploadResponse) GetVoiceMessageId() string {
	if x != nil {
		return x.VoiceMessageId
	}
	return ""
}

func (x *RequestVoiceMessageUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RequestVoiceMessageUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *RequestVoiceMessageUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmVoiceMessageUploadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	VoiceMessageId         string                 `protobuf:"bytes,1,opt,name=voice_message_id,json=voiceMessageId,proto3" json:"voice_message_id,omitempty"`
	FileId                 string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ClientDeduplicationKey string                 `protobuf:"bytes,3,opt,name=client_deduplication_key,json=clientDeduplicationKey,proto3" json:"client_deduplication_key,omitempty"`
	DurationMs             int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	WaveformPeaks          []float32              `protobuf:"fixed32,5,rep,packed,name=waveform_peaks,json=waveformPeaks,proto3" json:"waveform_peaks,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfirmVoiceMessageUploadRequest) Reset() {
	*x = ConfirmVoiceMessageUploadRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVoiceMessageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVoiceMessageUploadRequest) ProtoMessage() {}

func (x *ConfirmVoiceMessageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVoiceMessageUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmVoiceMessageUploadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{20}
}

func (x *ConfirmVoiceMessageUploadRequest) GetVoiceMessageId() string {
	if x != nil {
		return x.VoiceMessageId
	}
	return ""
}

func (x *ConfirmVoiceMessageUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConfirmVoiceMessageUploadRequest) GetClientDeduplicationKey() string {
	if x != nil {
		return x.ClientDeduplicationKey
	}
	return ""
}

func (x *ConfirmVoiceMessageUploadRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ConfirmVoiceMessageUploadRequest) GetWaveformPeaks() []float32 {
	if x != nil {
		return x.WaveformPeaks
	}
	return nil
}

type ConfirmVoiceMessageUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceMessage  *VoiceMessage          `protobuf:"bytes,1,opt,name=voice_message,json=voiceMessage,proto3" json:"voice_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmVoiceMessageUploadResponse) Reset() {
	*x = ConfirmVoiceMessageUploadResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVoiceMessageUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVoiceMessageUploadResponse) ProtoMessage() {}

func (x *ConfirmVoiceMessageUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVoiceMessageUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmVoiceMessageUploadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{21}
}

func (x *ConfirmVoiceMessageUploadResponse) GetVoiceMessage() *VoiceMessage {
	if x != nil {
		return x.VoiceMessage
	}
	return nil
}

type CancelVoiceMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VoiceMessageId string                 `protobuf:"bytes,1,opt,name=voice_message_id,json=voiceMessageId,proto3" json:"voice_message_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelVoiceMessageRequest) Reset() {
	*x = CancelVoiceMessageRequest{}
	mi := &file_rpc_v1_voice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelVoiceMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelVoiceMessageRequest) ProtoMessage() {}

func (x *CancelVoiceMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelVoiceMessageRequest.ProtoReflect.Descriptor instead.
func (*CancelVoiceMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{22}
}

func (x *CancelVoiceMessageRequest) GetVoiceMessageId() string {
	if x != nil {
		return x.VoiceMessageId
	}
	return ""
}

type CancelVoiceMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceMessage  *VoiceMessage          `protobuf:"bytes,1,opt,name=voice_message,json=voiceMessage,proto3" json:"voice_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelVoiceMessageResponse) Reset() {
	*x = CancelVoiceMessageResponse{}
	mi := &file_rpc_v1_voice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelVoiceMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelVoiceMessageResponse) ProtoMessage() {}

func (x *CancelVoiceMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelVoiceMessageResponse.ProtoReflect.Descriptor instead.
func (*CancelVoiceMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{23}
}

func (x *CancelVoiceMessageResponse) GetVoiceMessage() *VoiceMessage {
	if x != nil {
		return x.VoiceMessage
	}
	return nil
}

type VoiceJoinCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LivekitUrl    string                 `protobuf:"bytes,1,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	LivekitToken  string                 `protobuf:"bytes,2,opt,name=livekit_token,json=livekitToken,proto3" json:"livekit_token,omitempty"`
	RoomName      string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceJoinCredentials) Reset() {
	*x = VoiceJoinCredentials{}
	mi := &file_rpc_v1_voice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceJoinCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceJoinCredentials) ProtoMessage() {}

func (x *VoiceJoinCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceJoinCredentials.ProtoReflect.Descriptor instead.
func (*VoiceJoinCredentials) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{24}
}

func (x *VoiceJoinCredentials) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

func (x *VoiceJoinCredentials) GetLivekitToken() string {
	if x != nil {
		return x.LivekitToken
	}
	return ""
}

func (x *VoiceJoinCredentials) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *VoiceJoinCredentials) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VoiceCallSession struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Id                  string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId           string                  `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	InitiatorEmployeeId string                  `protobuf:"bytes,3,opt,name=initiator_employee_id,json=initiatorEmployeeId,proto3" json:"initiator_employee_id,omitempty"`
	State               VoiceCallState          `protobuf:"varint,4,opt,name=state,proto3,enum=rpc.v1.VoiceCallState" json:"state,omitempty"`
	Outcome             VoiceCallOutcome        `protobuf:"varint,5,opt,name=outcome,proto3,enum=rpc.v1.VoiceCallOutcome" json:"outcome,omitempty"`
	Participants        []*VoiceCallParticipant `protobuf:"bytes,6,rep,name=participants,proto3" json:"participants,omitempty"`
	RecordingPermitted  bool                    `protobuf:"varint,7,opt,name=recording_permitted,json=recordingPermitted,proto3" json:"recording_permitted,omitempty"`
	StartedAt           *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt             *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VoiceCallSession) Reset() {
	*x = VoiceCallSession{}
	mi := &file_rpc_v1_voice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCallSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCallSession) ProtoMessage() {}

func (x *VoiceCallSession) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCallSession.ProtoReflect.Descriptor instead.
func (*VoiceCallSession) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{25}
}

func (x *VoiceCallSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceCallSession) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceCallSession) GetInitiatorEmployeeId() string {
	if x != nil {
		return x.InitiatorEmployeeId
	}
	return ""
}

func (x *VoiceCallSession) GetState() VoiceCallState {
	if x != nil {
		return x.State
	}
	return VoiceCallState_VOICE_CALL_STATE_UNSPECIFIED
}

func (x *VoiceCallSession) GetOutcome() VoiceCallOutcome {
	if x != nil {
		return x.Outcome
	}
	return VoiceCallOutcome_VOICE_CALL_OUTCOME_UNSPECIFIED
}

func (x *VoiceCallSession) GetParticipants() []*VoiceCallParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *VoiceCallSession) GetRecordingPermitted() bool {
	if x != nil {
		return x.RecordingPermitted
	}
	return false
}

func (x *VoiceCallSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *VoiceCallSession) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type VoiceCallRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *VoiceCallSession      `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Artifacts     []*VoiceCallArtifact   `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceCallRecord) Reset() {
	*x = VoiceCallRecord{}
	mi := &file_rpc_v1_voice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCallRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCallRecord) ProtoMessage() {}

func (x *VoiceCallRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCallRecord.ProtoReflect.Descriptor instead.
func (*VoiceCallRecord) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{26}
}

func (x *VoiceCallRecord) GetCall() *VoiceCallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *VoiceCallRecord) GetArtifacts() []*VoiceCallArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type VoiceCallParticipant struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	EmployeeId    string                    `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	State         VoiceCallParticipantState `protobuf:"varint,2,opt,name=state,proto3,enum=rpc.v1.VoiceCallParticipantState" json:"state,omitempty"`
	JoinedAt      *timestamppb.Timestamp    `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceCallParticipant) Reset() {
	*x = VoiceCallParticipant{}
	mi := &file_rpc_v1_voice_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCallParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCallParticipant) ProtoMessage() {}

func (x *VoiceCallParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCallParticipant.ProtoReflect.Descriptor instead.
func (*VoiceCallParticipant) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{27}
}

func (x *VoiceCallParticipant) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *VoiceCallParticipant) GetState() VoiceCallParticipantState {
	if x != nil {
		return x.State
	}
	return VoiceCallParticipantState_VOICE_CALL_PARTICIPANT_STATE_UNSPECIFIED
}

func (x *VoiceCallParticipant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *VoiceCallParticipant) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

type VoiceCallInvitation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CallId            string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	InviteeEmployeeId string                 `protobuf:"bytes,3,opt,name=invitee_employee_id,json=inviteeEmployeeId,proto3" json:"invitee_employee_id,omitempty"`
	Status            VoiceInvitationStatus  `protobuf:"varint,4,opt,name=status,proto3,enum=rpc.v1.VoiceInvitationStatus" json:"status,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoiceCallInvitation) Reset() {
	*x = VoiceCallInvitation{}
	mi := &file_rpc_v1_voice_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCallInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCallInvitation) ProtoMessage() {}

func (x *VoiceCallInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCallInvitation.ProtoReflect.Descriptor instead.
func (*VoiceCallInvitation) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{28}
}

func (x *VoiceCallInvitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceCallInvitation) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *VoiceCallInvitation) GetInviteeEmployeeId() string {
	if x != nil {
		return x.InviteeEmployeeId
	}
	return ""
}

func (x *VoiceCallInvitation) GetStatus() VoiceInvitationStatus {
	if x != nil {
		return x.Status
	}
	return VoiceInvitationStatus_VOICE_INVITATION_STATUS_UNSPECIFIED
}

func (x *VoiceCallInvitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VoiceCallArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          VoiceArtifactType      `protobuf:"varint,2,opt,name=type,proto3,enum=rpc.v1.VoiceArtifactType" json:"type,omitempty"`
	Status        VoiceArtifactStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=rpc.v1.VoiceArtifactStatus" json:"status,omitempty"`
	FileId        string                 `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceCallArtifact) Reset() {
	*x = VoiceCallArtifact{}
	mi := &file_rpc_v1_voice_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCallArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCallArtifact) ProtoMessage() {}

func (x *VoiceCallArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCallArtifact.ProtoReflect.Descriptor instead.
func (*VoiceCallArtifact) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{29}
}

func (x *VoiceCallArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceCallArtifact) GetType() VoiceArtifactType {
	if x != nil {
		return x.Type
	}
	return VoiceArtifactType_VOICE_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *VoiceCallArtifact) GetStatus() VoiceArtifactStatus {
	if x != nil {
		return x.Status
	}
	return VoiceArtifactStatus_VOICE_ARTIFACT_STATUS_UNSPECIFIED
}

func (x *VoiceCallArtifact) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *VoiceCallArtifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *VoiceCallArtifact) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type VoiceMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId        string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FileId           string                 `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SenderEmployeeId string                 `protobuf:"bytes,5,opt,name=sender_employee_id,json=senderEmployeeId,proto3" json:"sender_employee_id,omitempty"`
	Status           VoiceMessageStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=rpc.v1.VoiceMessageStatus" json:"status,omitempty"`
	DurationMs       int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	MimeType         string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	WaveformPeaks    []float32              `protobuf:"fixed32,9,rep,packed,name=waveform_peaks,json=waveformPeaks,proto3" json:"waveform_peaks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoiceMessage) Reset() {
	*x = VoiceMessage{}
	mi := &file_rpc_v1_voice_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceMessage) ProtoMessage() {}

func (x *VoiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_voice_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceMessage.ProtoReflect.Descriptor instead.
func (*VoiceMessage) Descriptor() ([]byte, []int) {
	return file_rpc_v1_voice_proto_rawDescGZIP(), []int{30}
}

func (x *VoiceMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *VoiceMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *VoiceMessage) GetSenderEmployeeId() string {
	if x != nil {
		return x.SenderEmployeeId
	}
	return ""
}

func (x *VoiceMessage) GetStatus() VoiceMessageStatus {
	if x != nil {
		return x.Status
	}
	return VoiceMessageStatus_VOICE_MESSAGE_STATUS_UNSPECIFIED
}

func (x *VoiceMessage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *VoiceMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *VoiceMessage) GetWaveformPeaks() []float32 {
	if x != nil {
		return x.WaveformPeaks
	}
	return nil
}

var File_rpc_v1_voice_proto protoreflect.FileDescriptor

const file_rpc_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x12rpc/v1/voice.proto\x12\x06rpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11rpc/v1/rbac.proto\"c\n" +
	"\x15StartVoiceCallRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12+\n" +
	"\x11request_recording\x18\x02 \x01(\bR\x10requestRecording\"\x8f\x01\n" +
	"\x16StartVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\x12G\n" +
	"\x10join_credentials\x18\x02 \x01(\v2\x1c.rpc.v1.VoiceJoinCredentialsR\x0fjoinCredentials\":\n" +
	"\x19GetActiveVoiceCallRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"r\n" +
	"\x1aGetActiveVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\x12&\n" +
	"\x0fhas_active_call\x18\x02 \x01(\bR\rhasActiveCall\"\\\n" +
	"\x14JoinVoiceCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12+\n" +
	"\x11device_identifier\x18\x02 \x01(\tR\x10deviceIdentifier\"\x8e\x01\n" +
	"\x15JoinVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\x12G\n" +
	"\x10join_credentials\x18\x02 \x01(\v2\x1c.rpc.v1.VoiceJoinCredentialsR\x0fjoinCredentials\"]\n" +
	"\x15LeaveVoiceCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12+\n" +
	"\x11device_identifier\x18\x02 \x01(\tR\x10deviceIdentifier\"F\n" +
	"\x16LeaveVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\"[\n" +
	"\x13EndVoiceCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12+\n" +
	"\x11device_identifier\x18\x02 \x01(\tR\x10deviceIdentifier\"D\n" +
	"\x14EndVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\"V\n" +
	"\x18InviteToVoiceCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12!\n" +
	"\femployee_ids\x18\x02 \x03(\tR\vemployeeIds\"\x88\x01\n" +
	"\x19InviteToVoiceCallResponse\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\x12=\n" +
	"\vinvitations\x18\x02 \x03(\v2\x1b.rpc.v1.VoiceCallInvitationR\vinvitations\"\xac\x01\n" +
	"\x1fRespondToVoiceCallInviteRequest\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x127\n" +
	"\bresponse\x18\x02 \x01(\x0e2\x1b.rpc.v1.VoiceInviteResponseR\bresponse\x12+\n" +
	"\x11device_identifier\x18\x03 \x01(\tR\x10deviceIdentifier\"\xa8\x01\n" +
	" RespondToVoiceCallInviteResponse\x12;\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1b.rpc.v1.VoiceCallInvitationR\n" +
	"invitation\x12G\n" +
	"\x10join_credentials\x18\x02 \x01(\v2\x1c.rpc.v1.VoiceJoinCredentialsR\x0fjoinCredentials\"e\n" +
	"\x16ListCallRecordsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"m\n" +
	"\x17ListCallRecordsResponse\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.rpc.v1.VoiceCallRecordR\arecords\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"/\n" +
	"\x14GetCallRecordRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"H\n" +
	"\x15GetCallRecordResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.rpc.v1.VoiceCallRecordR\x06record\"\x85\x02\n" +
	" RequestVoiceMessageUploadRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x128\n" +
	"\x18client_deduplication_key\x18\x02 \x01(\tR\x16clientDeduplicationKey\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x120\n" +
	"\x14expected_duration_ms\x18\x06 \x01(\x03R\x12expectedDurationMs\"\xc0\x01\n" +
	"!RequestVoiceMessageUploadResponse\x12(\n" +
	"\x10voice_message_id\x18\x01 \x01(\tR\x0evoiceMessageId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xe7\x01\n" +
	" ConfirmVoiceMessageUploadRequest\x12(\n" +
	"\x10voice_message_id\x18\x01 \x01(\tR\x0evoiceMessageId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x128\n" +
	"\x18client_deduplication_key\x18\x03 \x01(\tR\x16clientDeduplicationKey\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12%\n" +
	"\x0ewaveform_peaks\x18\x05 \x03(\x02R\rwaveformPeaks\"^\n" +
	"!ConfirmVoiceMessageUploadResponse\x129\n" +
	"\rvoice_message\x18\x01 \x01(\v2\x14.rpc.v1.VoiceMessageR\fvoiceMessage\"E\n" +
	"\x19CancelVoiceMessageRequest\x12(\n" +
	"\x10voice_message_id\x18\x01 \x01(\tR\x0evoiceMessageId\"W\n" +
	"\x1aCancelVoiceMessageResponse\x129\n" +
	"\rvoice_message\x18\x01 \x01(\v2\x14.rpc.v1.VoiceMessageR\fvoiceMessage\"\xe3\x01\n" +
	"\x14VoiceJoinCredentials\x12\x1f\n" +
	"\vlivekit_url\x18\x01 \x01(\tR\n" +
	"livekitUrl\x12#\n" +
	"\rlivekit_token\x18\x02 \x01(\tR\flivekitToken\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomName\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\vice_serversR\x14ice_transport_policy\"\xbc\x03\n" +
	"\x10VoiceCallSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x122\n" +
	"\x15initiator_employee_id\x18\x03 \x01(\tR\x13initiatorEmployeeId\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.rpc.v1.VoiceCallStateR\x05state\x122\n" +
	"\aoutcome\x18\x05 \x01(\x0e2\x18.rpc.v1.VoiceCallOutcomeR\aoutcome\x12@\n" +
	"\fparticipants\x18\x06 \x03(\v2\x1c.rpc.v1.VoiceCallParticipantR\fparticipants\x12/\n" +
	"\x13recording_permitted\x18\a \x01(\bR\x12recordingPermitted\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"x\n" +
	"\x0fVoiceCallRecord\x12,\n" +
	"\x04call\x18\x01 \x01(\v2\x18.rpc.v1.VoiceCallSessionR\x04call\x127\n" +
	"\tartifacts\x18\x02 \x03(\v2\x19.rpc.v1.VoiceCallArtifactR\tartifacts\"\xde\x01\n" +
	"\x14VoiceCallParticipant\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.rpc.v1.VoiceCallParticipantStateR\x05state\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x123\n" +
	"\aleft_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06leftAt\"\xe0\x01\n" +
	"\x13VoiceCallInvitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12.\n" +
	"\x13invitee_employee_id\x18\x03 \x01(\tR\x11inviteeEmployeeId\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.rpc.v1.VoiceInvitationStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xde\x01\n" +
	"\x11VoiceCallArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.rpc.v1.VoiceArtifactTypeR\x04type\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.rpc.v1.VoiceArtifactStatusR\x06status\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\xbc\x02\n" +
	"\fVoiceMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\tR\x06fileId\x12,\n" +
	"\x12sender_employee_id\x18\x05 \x01(\tR\x10senderEmployeeId\x122\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1a.rpc.v1.VoiceMessageStatusR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12%\n" +
	"\x0ewaveform_peaks\x18\t \x03(\x02R\rwaveformPeaks*\xa6\x01\n" +
	"\x0eVoiceCallState\x12 \n" +
	"\x1cVOICE_CALL_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VOICE_CALL_STATE_RINGING\x10\x01\x12\x1b\n" +
	"\x17VOICE_CALL_STATE_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17VOICE_CALL_STATE_ENDING\x10\x03\x12\x1a\n" +
	"\x16VOICE_CALL_STATE_ENDED\x10\x04*\xdb\x01\n" +
	"\x10VoiceCallOutcome\x12\"\n" +
	"\x1eVOICE_CALL_OUTCOME_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVOICE_CALL_OUTCOME_ANSWERED\x10\x01\x12\x1d\n" +
	"\x19VOICE_CALL_OUTCOME_MISSED\x10\x02\x12\x1f\n" +
	"\x1bVOICE_CALL_OUTCOME_DECLINED\x10\x03\x12 \n" +
	"\x1cVOICE_CALL_OUTCOME_CANCELLED\x10\x04\x12 \n" +
	"\x1cVOICE_CALL_OUTCOME_COMPLETED\x10\x05*\x9b\x03\n" +
	"\x19VoiceCallParticipantState\x12,\n" +
	"(VOICE_CALL_PARTICIPANT_STATE_UNSPECIFIED\x10\x00\x12(\n" +
	"$VOICE_CALL_PARTICIPANT_STATE_INVITED\x10\x01\x12(\n" +
	"$VOICE_CALL_PARTICIPANT_STATE_RINGING\x10\x02\x12(\n" +
	"$VOICE_CALL_PARTICIPANT_STATE_JOINING\x10\x03\x12'\n" +
	"#VOICE_CALL_PARTICIPANT_STATE_JOINED\x10\x04\x12-\n" +
	")VOICE_CALL_PARTICIPANT_STATE_DISCONNECTED\x10\x05\x12%\n" +
	"!VOICE_CALL_PARTICIPANT_STATE_LEFT\x10\x06\x12)\n" +
	"%VOICE_CALL_PARTICIPANT_STATE_DECLINED\x10\a\x12(\n" +
	"$VOICE_CALL_PARTICIPANT_STATE_REMOVED\x10\b*\x81\x01\n" +
	"\x13VoiceInviteResponse\x12%\n" +
	"!VOICE_INVITE_RESPONSE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVOICE_INVITE_RESPONSE_ACCEPT\x10\x01\x12!\n" +
	"\x1dVOICE_INVITE_RESPONSE_DECLINE\x10\x02*\xfb\x01\n" +
	"\x15VoiceInvitationStatus\x12'\n" +
	"#VOICE_INVITATION_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fVOICE_INVITATION_STATUS_PENDING\x10\x01\x12$\n" +
	" VOICE_INVITATION_STATUS_ACCEPTED\x10\x02\x12$\n" +
	" VOICE_INVITATION_STATUS_DECLINED\x10\x03\x12#\n" +
	"\x1fVOICE_INVITATION_STATUS_EXPIRED\x10\x04\x12#\n" +
	"\x1fVOICE_INVITATION_STATUS_REVOKED\x10\x05*\x7f\n" +
	"\x11VoiceArtifactType\x12#\n" +
	"\x1fVOICE_ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVOICE_ARTIFACT_TYPE_RECORDING\x10\x01\x12\"\n" +
	"\x1eVOICE_ARTIFACT_TYPE_TRANSCRIPT\x10\x02*\xef\x01\n" +
	"\x13VoiceArtifactStatus\x12%\n" +
	"!VOICE_ARTIFACT_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVOICE_ARTIFACT_STATUS_PENDING\x10\x01\x12$\n" +
	" VOICE_ARTIFACT_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bVOICE_ARTIFACT_STATUS_READY\x10\x03\x12%\n" +
	"!VOICE_ARTIFACT_STATUS_UNAVAILABLE\x10\x04\x12 \n" +
	"\x1cVOICE_ARTIFACT_STATUS_FAILED\x10\x05*\xe8\x01\n" +
	"\x12VoiceMessageStatus\x12$\n" +
	" VOICE_MESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eVOICE_MESSAGE_STATUS_REQUESTED\x10\x01\x12\"\n" +
	"\x1eVOICE_MESSAGE_STATUS_UPLOADING\x10\x02\x12\x1f\n" +
	"\x1bVOICE_MESSAGE_STATUS_POSTED\x10\x03\x12\x1f\n" +
	"\x1bVOICE_MESSAGE_STATUS_FAILED\x10\x04\x12\"\n" +
	"\x1eVOICE_MESSAGE_STATUS_CANCELLED\x10\x052\xeb\n" +
	"\n" +
	"\fVoiceService\x12e\n" +
	"\x0eStartVoiceCall\x12\x1d.rpc.v1.StartVoiceCallRequest\x1a\x1e.rpc.v1.StartVoiceCallResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12s\n" +
	"\x12GetActiveVoiceCall\x12!.rpc.v1.GetActiveVoiceCallRequest\x1a\".rpc.v1.GetActiveVoiceCallResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.viewChannel\x12b\n" +
	"\rJoinVoiceCall\x12\x1c.rpc.v1.JoinVoiceCallRequest\x1a\x1d.rpc.v1.JoinVoiceCallResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12e\n" +
	"\x0eLeaveVoiceCall\x12\x1d.rpc.v1.LeaveVoiceCallRequest\x1a\x1e.rpc.v1.LeaveVoiceCallResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12_\n" +
	"\fEndVoiceCall\x12\x1b.rpc.v1.EndVoiceCallRequest\x1a\x1c.rpc.v1.EndVoiceCallResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12n\n" +
	"\x11InviteToVoiceCall\x12 .rpc.v1.InviteToVoiceCallRequest\x1a!.rpc.v1.InviteToVoiceCallResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12\x83\x01\n" +
	"\x18RespondToVoiceCallInvite\x12'.rpc.v1.RespondToVoiceCallInviteRequest\x1a(.rpc.v1.RespondToVoiceCallInviteResponse\"\x14\x82\xf9+\x10\n" +
	"\x0echat.voiceCall\x12k\n" +
	"\x0fListCallRecords\x12\x1e.rpc.v1.ListCallRecordsRequest\x1a\x1f.rpc.v1.ListCallRecordsResponse\"\x17\x82\xf9+\x13\n" +
	"\x11chat.viewMessages\x12e\n" +
	"\rGetCallRecord\x12\x1c.rpc.v1.GetCallRecordRequest\x1a\x1d.rpc.v1.GetCallRecordResponse\"\x17\x82\xf9+\x13\n" +
	"\x11chat.viewMessages\x12\x88\x01\n" +
	"\x19RequestVoiceMessageUpload\x12(.rpc.v1.RequestVoiceMessageUploadRequest\x1a).rpc.v1.RequestVoiceMessageUploadResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.sendMessage\x12\x88\x01\n" +
	"\x19ConfirmVoiceMessageUpload\x12(.rpc.v1.ConfirmVoiceMessageUploadRequest\x1a).rpc.v1.ConfirmVoiceMessageUploadResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.sendMessage\x12s\n" +
	"\x12CancelVoiceMessage\x12!.rpc.v1.CancelVoiceMessageRequest\x1a\".rpc.v1.CancelVoiceMessageResponse\"\x16\x82\xf9+\x12\n" +
	"\x10chat.sendMessageB\x85\x01\n" +
	"\n" +
	"com.rpc.v1B\n" +
	"VoiceProtoP\x01Z2github.com/nvcnvn/tech-office/backend/rpc/v1;rpcv1\xa2\x02\x03RXX\xaa\x02\x06Rpc.V1\xca\x02\x06Rpc\\V1\xe2\x02\x12Rpc\\V1\\GPBMetadata\xea\x02\aRpc::V1b\x06proto3"

var (
	file_rpc_v1_voice_proto_rawDescOnce sync.Once
	file_rpc_v1_voice_proto_rawDescData []byte
)

func file_rpc_v1_voice_proto_rawDescGZIP() []byte {
	file_rpc_v1_voice_proto_rawDescOnce.Do(func() {
		file_rpc_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_voice_proto_rawDesc), len(file_rpc_v1_voice_proto_rawDesc)))
	})
	return file_rpc_v1_voice_proto_rawDescData
}

var file_rpc_v1_voice_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_rpc_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_rpc_v1_voice_proto_goTypes = []any{
	(VoiceCallState)(0),                       // 0: rpc.v1.VoiceCallState
	(VoiceCallOutcome)(0),                     // 1: rpc.v1.VoiceCallOutcome
	(VoiceCallParticipantState)(0),            // 2: rpc.v1.VoiceCallParticipantState
	(VoiceInviteResponse)(0),                  // 3: rpc.v1.VoiceInviteResponse
	(VoiceInvitationStatus)(0),                // 4: rpc.v1.VoiceInvitationStatus
	(VoiceArtifactType)(0),                    // 5: rpc.v1.VoiceArtifactType
	(VoiceArtifactStatus)(0),                  // 6: rpc.v1.VoiceArtifactStatus
	(VoiceMessageStatus)(0),                   // 7: rpc.v1.VoiceMessageStatus
	(*StartVoiceCallRequest)(nil),             // 8: rpc.v1.StartVoiceCallRequest
	(*StartVoiceCallResponse)(nil),            // 9: rpc.v1.StartVoiceCallResponse
	(*GetActiveVoiceCallRequest)(nil),         // 10: rpc.v1.GetActiveVoiceCallRequest
	(*GetActiveVoiceCallResponse)(nil),        // 11: rpc.v1.GetActiveVoiceCallResponse
	(*JoinVoiceCallRequest)(nil),              // 12: rpc.v1.JoinVoiceCallRequest
	(*JoinVoiceCallResponse)(nil),             // 13: rpc.v1.JoinVoiceCallResponse
	(*LeaveVoiceCallRequest)(nil),             // 14: rpc.v1.LeaveVoiceCallRequest
	(*LeaveVoiceCallResponse)(nil),            // 15: rpc.v1.LeaveVoiceCallResponse
	(*EndVoiceCallRequest)(nil),               // 16: rpc.v1.EndVoiceCallRequest
	(*EndVoiceCallResponse)(nil),              // 17: rpc.v1.EndVoiceCallResponse
	(*InviteToVoiceCallRequest)(nil),          // 18: rpc.v1.InviteToVoiceCallRequest
	(*InviteToVoiceCallResponse)(nil),         // 19: rpc.v1.InviteToVoiceCallResponse
	(*RespondToVoiceCallInviteRequest)(nil),   // 20: rpc.v1.RespondToVoiceCallInviteRequest
	(*RespondToVoiceCallInviteResponse)(nil),  // 21: rpc.v1.RespondToVoiceCallInviteResponse
	(*ListCallRecordsRequest)(nil),            // 22: rpc.v1.ListCallRecordsRequest
	(*ListCallRecordsResponse)(nil),           // 23: rpc.v1.ListCallRecordsResponse
	(*GetCallRecordRequest)(nil),              // 24: rpc.v1.GetCallRecordRequest
	(*GetCallRecordResponse)(nil),             // 25: rpc.v1.GetCallRecordResponse
	(*RequestVoiceMessageUploadRequest)(nil),  // 26: rpc.v1.RequestVoiceMessageUploadRequest
	(*RequestVoiceMessageUploadResponse)(nil), // 27: rpc.v1.RequestVoiceMessageUploadResponse
	(*ConfirmVoiceMessageUploadRequest)(nil),  // 28: rpc.v1.ConfirmVoiceMessageUploadRequest
	(*ConfirmVoiceMessageUploadResponse)(nil), // 29: rpc.v1.ConfirmVoiceMessageUploadResponse
	(*CancelVoiceMessageRequest)(nil),         // 30: rpc.v1.CancelVoiceMessageRequest
	(*CancelVoiceMessageResponse)(nil),        // 31: rpc.v1.CancelVoiceMessageResponse
	(*VoiceJoinCredentials)(nil),              // 32: rpc.v1.VoiceJoinCredentials
	(*VoiceCallSession)(nil),                  // 33: rpc.v1.VoiceCallSession
	(*VoiceCallRecord)(nil),                   // 34: rpc.v1.VoiceCallRecord
	(*VoiceCallParticipant)(nil),              // 35: rpc.v1.VoiceCallParticipant
	(*VoiceCallInvitation)(nil),               // 36: rpc.v1.VoiceCallInvitation
	(*VoiceCallArtifact)(nil),                 // 37: rpc.v1.VoiceCallArtifact
	(*VoiceMessage)(nil),                      // 38: rpc.v1.VoiceMessage
	(*timestamppb.Timestamp)(nil),             // 39: google.protobuf.Timestamp
}
var file_rpc_v1_voice_proto_depIdxs = []int32{
	33, // 0: rpc.v1.StartVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	32, // 1: rpc.v1.StartVoiceCallResponse.join_credentials:type_name -> rpc.v1.VoiceJoinCredentials
	33, // 2: rpc.v1.GetActiveVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	33, // 3: rpc.v1.JoinVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	32, // 4: rpc.v1.JoinVoiceCallResponse.join_credentials:type_name -> rpc.v1.VoiceJoinCredentials
	33, // 5: rpc.v1.LeaveVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	33, // 6: rpc.v1.EndVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	33, // 7: rpc.v1.InviteToVoiceCallResponse.call:type_name -> rpc.v1.VoiceCallSession
	36, // 8: rpc.v1.InviteToVoiceCallResponse.invitations:type_name -> rpc.v1.VoiceCallInvitation
	3,  // 9: rpc.v1.RespondToVoiceCallInviteRequest.response:type_name -> rpc.v1.VoiceInviteResponse
	36, // 10: rpc.v1.RespondToVoiceCallInviteResponse.invitation:type_name -> rpc.v1.VoiceCallInvitation
	32, // 11: rpc.v1.RespondToVoiceCallInviteResponse.join_credentials:type_name -> rpc.v1.VoiceJoinCredentials
	34, // 12: rpc.v1.ListCallRecordsResponse.records:type_name -> rpc.v1.VoiceCallRecord
	34, // 13: rpc.v1.GetCallRecordResponse.record:type_name -> rpc.v1.VoiceCallRecord
	39, // 14: rpc.v1.RequestVoiceMessageUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	38, // 15: rpc.v1.ConfirmVoiceMessageUploadResponse.voice_message:type_name -> rpc.v1.VoiceMessage
	38, // 16: rpc.v1.CancelVoiceMessageResponse.voice_message:type_name -> rpc.v1.VoiceMessage
	39, // 17: rpc.v1.VoiceJoinCredentials.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 18: rpc.v1.VoiceCallSession.state:type_name -> rpc.v1.VoiceCallState
	1,  // 19: rpc.v1.VoiceCallSession.outcome:type_name -> rpc.v1.VoiceCallOutcome
	35, // 20: rpc.v1.VoiceCallSession.participants:type_name -> rpc.v1.VoiceCallParticipant
	39, // 21: rpc.v1.VoiceCallSession.started_at:type_name -> google.protobuf.Timestamp
	39, // 22: rpc.v1.VoiceCallSession.ended_at:type_name -> google.protobuf.Timestamp
	33, // 23: rpc.v1.VoiceCallRecord.call:type_name -> rpc.v1.VoiceCallSession
	37, // 24: rpc.v1.VoiceCallRecord.artifacts:type_name -> rpc.v1.VoiceCallArtifact
	2,  // 25: rpc.v1.VoiceCallParticipant.state:type_name -> rpc.v1.VoiceCallParticipantState
	39, // 26: rpc.v1.VoiceCallParticipant.joined_at:type_name -> google.protobuf.Timestamp
	39, // 27: rpc.v1.VoiceCallParticipant.left_at:type_name -> google.protobuf.Timestamp
	4,  // 28: rpc.v1.VoiceCallInvitation.status:type_name -> rpc.v1.VoiceInvitationStatus
	39, // 29: rpc.v1.VoiceCallInvitation.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 30: rpc.v1.VoiceCallArtifact.type:type_name -> rpc.v1.VoiceArtifactType
	6,  // 31: rpc.v1.VoiceCallArtifact.status:type_name -> rpc.v1.VoiceArtifactStatus
	7,  // 32: rpc.v1.VoiceMessage.status:type_name -> rpc.v1.VoiceMessageStatus
	8,  // 33: rpc.v1.VoiceService.StartVoiceCall:input_type -> rpc.v1.StartVoiceCallRequest
	10, // 34: rpc.v1.VoiceService.GetActiveVoiceCall:input_type -> rpc.v1.GetActiveVoiceCallRequest
	12, // 35: rpc.v1.VoiceService.JoinVoiceCall:input_type -> rpc.v1.JoinVoiceCallRequest
	14, // 36: rpc.v1.VoiceService.LeaveVoiceCall:input_type -> rpc.v1.LeaveVoiceCallRequest
	16, // 37: rpc.v1.VoiceService.EndVoiceCall:input_type -> rpc.v1.EndVoiceCallRequest
	18, // 38: rpc.v1.VoiceService.InviteToVoiceCall:input_type -> rpc.v1.InviteToVoiceCallRequest
	20, // 39: rpc.v1.VoiceService.RespondToVoiceCallInvite:input_type -> rpc.v1.RespondToVoiceCallInviteRequest
	22, // 40: rpc.v1.VoiceService.ListCallRecords:input_type -> rpc.v1.ListCallRecordsRequest
	24, // 41: rpc.v1.VoiceService.GetCallRecord:input_type -> rpc.v1.GetCallRecordRequest
	26, // 42: rpc.v1.VoiceService.RequestVoiceMessageUpload:input_type -> rpc.v1.RequestVoiceMessageUploadRequest
	28, // 43: rpc.v1.VoiceService.ConfirmVoiceMessageUpload:input_type -> rpc.v1.ConfirmVoiceMessageUploadRequest
	30, // 44: rpc.v1.VoiceService.CancelVoiceMessage:input_type -> rpc.v1.CancelVoiceMessageRequest
	9,  // 45: rpc.v1.VoiceService.StartVoiceCall:output_type -> rpc.v1.StartVoiceCallResponse
	11, // 46: rpc.v1.VoiceService.GetActiveVoiceCall:output_type -> rpc.v1.GetActiveVoiceCallResponse
	13, // 47: rpc.v1.VoiceService.JoinVoiceCall:output_type -> rpc.v1.JoinVoiceCallResponse
	15, // 48: rpc.v1.VoiceService.LeaveVoiceCall:output_type -> rpc.v1.LeaveVoiceCallResponse
	17, // 49: rpc.v1.VoiceService.EndVoiceCall:output_type -> rpc.v1.EndVoiceCallResponse
	19, // 50: rpc.v1.VoiceService.InviteToVoiceCall:output_type -> rpc.v1.InviteToVoiceCallResponse
	21, // 51: rpc.v1.VoiceService.RespondToVoiceCallInvite:output_type -> rpc.v1.RespondToVoiceCallInviteResponse
	23, // 52: rpc.v1.VoiceService.ListCallRecords:output_type -> rpc.v1.ListCallRecordsResponse
	25, // 53: rpc.v1.VoiceService.GetCallRecord:output_type -> rpc.v1.GetCallRecordResponse
	27, // 54: rpc.v1.VoiceService.RequestVoiceMessageUpload:output_type -> rpc.v1.RequestVoiceMessageUploadResponse
	29, // 55: rpc.v1.VoiceService.ConfirmVoiceMessageUpload:output_type -> rpc.v1.ConfirmVoiceMessageUploadResponse
	31, // 56: rpc.v1.VoiceService.CancelVoiceMessage:output_type -> rpc.v1.CancelVoiceMessageResponse
	45, // [45:57] is the sub-list for method output_type
	33, // [33:45] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_rpc_v1_voice_proto_init() }
func file_rpc_v1_voice_proto_init() {
	if File_rpc_v1_voice_proto != nil {
		return
	}
	file_rpc_v1_rbac_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_voice_proto_rawDesc), len(file_rpc_v1_voice_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_voice_proto_goTypes,
		DependencyIndexes: file_rpc_v1_voice_proto_depIdxs,
		EnumInfos:         file_rpc_v1_voice_proto_enumTypes,
		MessageInfos:      file_rpc_v1_voice_proto_msgTypes,
	}.Build()
	File_rpc_v1_voice_proto = out.File
	file_rpc_v1_voice_proto_goTypes = nil
	file_rpc_v1_voice_proto_depIdxs = nil
}
