// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: docs.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nvcnvn/tech-office/backend/database/dbuuid"
)

const countActiveEditors = `-- name: CountActiveEditors :one
SELECT COUNT(*) AS editor_count
FROM docs.document_editor
WHERE organization_id = $1 
  AND document_id = $2
  AND last_heartbeat > now() - interval '60 seconds'
`

type CountActiveEditorsParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

func (q *Queries) CountActiveEditors(ctx context.Context, db DBTX, arg *CountActiveEditorsParams) (int64, error) {
	row := db.QueryRow(ctx, countActiveEditors, arg.OrganizationID, arg.DocumentID)
	var editor_count int64
	err := row.Scan(&editor_count)
	return editor_count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO docs.comment (
    id, organization_id, document_id, block_id,
    text_selection_start, text_selection_end, 
    comment_text, author_employee_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8
)
RETURNING id, organization_id, document_id, block_id, text_selection_start, text_selection_end, comment_text, author_employee_id, is_resolved, resolved_by_employee_id, resolved_at, reply_count, updated_at
`

type CreateCommentParams struct {
	ID                 dbuuid.UUID     `json:"id"`
	OrganizationID     dbuuid.UUID     `json:"organization_id"`
	DocumentID         dbuuid.UUID     `json:"document_id"`
	BlockID            dbuuid.NullUUID `json:"block_id"`
	TextSelectionStart pgtype.Int4     `json:"text_selection_start"`
	TextSelectionEnd   pgtype.Int4     `json:"text_selection_end"`
	CommentText        string          `json:"comment_text"`
	AuthorEmployeeID   dbuuid.UUID     `json:"author_employee_id"`
}

func (q *Queries) CreateComment(ctx context.Context, db DBTX, arg *CreateCommentParams) (*DocsComment, error) {
	row := db.QueryRow(ctx, createComment,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentID,
		arg.BlockID,
		arg.TextSelectionStart,
		arg.TextSelectionEnd,
		arg.CommentText,
		arg.AuthorEmployeeID,
	)
	var i DocsComment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.BlockID,
		&i.TextSelectionStart,
		&i.TextSelectionEnd,
		&i.CommentText,
		&i.AuthorEmployeeID,
		&i.IsResolved,
		&i.ResolvedByEmployeeID,
		&i.ResolvedAt,
		&i.ReplyCount,
		&i.UpdatedAt,
	)
	return &i, err
}

const createCommentReply = `-- name: CreateCommentReply :one
INSERT INTO docs.comment_reply (
    id, organization_id, comment_id, reply_text, author_employee_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, comment_id, reply_text, author_employee_id, updated_at
`

type CreateCommentReplyParams struct {
	ID               dbuuid.UUID `json:"id"`
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	CommentID        dbuuid.UUID `json:"comment_id"`
	ReplyText        string      `json:"reply_text"`
	AuthorEmployeeID dbuuid.UUID `json:"author_employee_id"`
}

func (q *Queries) CreateCommentReply(ctx context.Context, db DBTX, arg *CreateCommentReplyParams) (*DocsCommentReply, error) {
	row := db.QueryRow(ctx, createCommentReply,
		arg.ID,
		arg.OrganizationID,
		arg.CommentID,
		arg.ReplyText,
		arg.AuthorEmployeeID,
	)
	var i DocsCommentReply
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CommentID,
		&i.ReplyText,
		&i.AuthorEmployeeID,
		&i.UpdatedAt,
	)
	return &i, err
}

const createDocument = `-- name: CreateDocument :one


INSERT INTO docs.document (
    id, organization_id, title, slug, parent_document_id, depth, 
    content_json, content_text, status, visibility, owner_employee_id, path
)
VALUES (
    $1, $2, $3, $4, $5, 
    $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at
`

type CreateDocumentParams struct {
	ID               dbuuid.UUID     `json:"id"`
	OrganizationID   dbuuid.UUID     `json:"organization_id"`
	Title            string          `json:"title"`
	Slug             string          `json:"slug"`
	ParentDocumentID dbuuid.NullUUID `json:"parent_document_id"`
	Depth            int16           `json:"depth"`
	ContentJson      []byte          `json:"content_json"`
	ContentText      string          `json:"content_text"`
	Status           string          `json:"status"`
	Visibility       string          `json:"visibility"`
	OwnerEmployeeID  dbuuid.UUID     `json:"owner_employee_id"`
	Path             []dbuuid.UUID   `json:"path"`
}

// ============================================================================
// Document Management System - sqlc Queries
// Follows Citus sharding constraints: organization_id first in all keys
// ============================================================================
// ============================================================================
// DOCUMENT CRUD OPERATIONS
// ============================================================================
func (q *Queries) CreateDocument(ctx context.Context, db DBTX, arg *CreateDocumentParams) (*DocsDocument, error) {
	row := db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Slug,
		arg.ParentDocumentID,
		arg.Depth,
		arg.ContentJson,
		arg.ContentText,
		arg.Status,
		arg.Visibility,
		arg.OwnerEmployeeID,
		arg.Path,
	)
	var i DocsDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DocumentType,
		&i.ParentDocumentID,
		&i.Depth,
		&i.Path,
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.Visibility,
		&i.OwnerEmployeeID,
		&i.ChildCount,
		&i.VersionCount,
		&i.FollowerCount,
		&i.IsDeleted,
		&i.UpdatedAt,
	)
	return &i, err
}

const createSectionEmbed = `-- name: CreateSectionEmbed :one

INSERT INTO docs.section_embed (
    id, organization_id, source_document_id, source_line_start, source_line_end,
    target_document_id, target_line_start, target_line_end, target_version_number
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, organization_id, source_document_id, source_line_start, source_line_end, target_document_id, target_line_start, target_line_end, target_version_number, updated_at
`

type CreateSectionEmbedParams struct {
	ID                  dbuuid.UUID `json:"id"`
	OrganizationID      dbuuid.UUID `json:"organization_id"`
	SourceDocumentID    dbuuid.UUID `json:"source_document_id"`
	SourceLineStart     int32       `json:"source_line_start"`
	SourceLineEnd       int32       `json:"source_line_end"`
	TargetDocumentID    dbuuid.UUID `json:"target_document_id"`
	TargetLineStart     int32       `json:"target_line_start"`
	TargetLineEnd       int32       `json:"target_line_end"`
	TargetVersionNumber int32       `json:"target_version_number"`
}

// ============================================================================
// SECTION EMBEDS
// ============================================================================
func (q *Queries) CreateSectionEmbed(ctx context.Context, db DBTX, arg *CreateSectionEmbedParams) (*DocsSectionEmbed, error) {
	row := db.QueryRow(ctx, createSectionEmbed,
		arg.ID,
		arg.OrganizationID,
		arg.SourceDocumentID,
		arg.SourceLineStart,
		arg.SourceLineEnd,
		arg.TargetDocumentID,
		arg.TargetLineStart,
		arg.TargetLineEnd,
		arg.TargetVersionNumber,
	)
	var i DocsSectionEmbed
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SourceDocumentID,
		&i.SourceLineStart,
		&i.SourceLineEnd,
		&i.TargetDocumentID,
		&i.TargetLineStart,
		&i.TargetLineEnd,
		&i.TargetVersionNumber,
		&i.UpdatedAt,
	)
	return &i, err
}

const createSlugHistory = `-- name: CreateSlugHistory :exec

INSERT INTO docs.document_slug_history (id, organization_id, document_id, old_slug)
VALUES ($1, $2, $3, $4)
`

type CreateSlugHistoryParams struct {
	ID             dbuuid.UUID `json:"id"`
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	OldSlug        string      `json:"old_slug"`
}

// ============================================================================
// SLUG HISTORY (for redirects)
// ============================================================================
func (q *Queries) CreateSlugHistory(ctx context.Context, db DBTX, arg *CreateSlugHistoryParams) error {
	_, err := db.Exec(ctx, createSlugHistory,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentID,
		arg.OldSlug,
	)
	return err
}

const createVersion = `-- name: CreateVersion :one

INSERT INTO docs.document_version (
    id, organization_id, document_id, version_number, 
    content_json, content_text, author_employee_id, summary
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, organization_id, document_id, version_number, content_json, content_text, author_employee_id, summary, created_at
`

type CreateVersionParams struct {
	ID               dbuuid.UUID `json:"id"`
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	DocumentID       dbuuid.UUID `json:"document_id"`
	VersionNumber    int32       `json:"version_number"`
	ContentJson      []byte      `json:"content_json"`
	ContentText      string      `json:"content_text"`
	AuthorEmployeeID dbuuid.UUID `json:"author_employee_id"`
	Summary          pgtype.Text `json:"summary"`
}

// ============================================================================
// VERSION HISTORY
// ============================================================================
func (q *Queries) CreateVersion(ctx context.Context, db DBTX, arg *CreateVersionParams) (*DocsDocumentVersion, error) {
	row := db.QueryRow(ctx, createVersion,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentID,
		arg.VersionNumber,
		arg.ContentJson,
		arg.ContentText,
		arg.AuthorEmployeeID,
		arg.Summary,
	)
	var i DocsDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.ContentJson,
		&i.ContentText,
		&i.AuthorEmployeeID,
		&i.Summary,
		&i.CreatedAt,
	)
	return &i, err
}

const decrementChildCount = `-- name: DecrementChildCount :exec
UPDATE docs.document
SET child_count = GREATEST(0, child_count - 1), updated_at = $1
WHERE organization_id = $2 AND id = $3
`

type DecrementChildCountParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) DecrementChildCount(ctx context.Context, db DBTX, arg *DecrementChildCountParams) error {
	_, err := db.Exec(ctx, decrementChildCount, arg.UpdatedAt, arg.OrganizationID, arg.ID)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM docs.comment
WHERE organization_id = $1 AND id = $2
`

type DeleteCommentParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

func (q *Queries) DeleteComment(ctx context.Context, db DBTX, arg *DeleteCommentParams) error {
	_, err := db.Exec(ctx, deleteComment, arg.OrganizationID, arg.ID)
	return err
}

const deleteDocumentReaction = `-- name: DeleteDocumentReaction :exec
DELETE FROM docs.document_reaction
WHERE organization_id = $1
  AND document_id = $2
  AND employee_id = $3
`

type DeleteDocumentReactionParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

func (q *Queries) DeleteDocumentReaction(ctx context.Context, db DBTX, arg *DeleteDocumentReactionParams) error {
	_, err := db.Exec(ctx, deleteDocumentReaction, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	return err
}

const deleteSectionEmbed = `-- name: DeleteSectionEmbed :exec
DELETE FROM docs.section_embed
WHERE organization_id = $1 AND id = $2
`

type DeleteSectionEmbedParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

func (q *Queries) DeleteSectionEmbed(ctx context.Context, db DBTX, arg *DeleteSectionEmbedParams) error {
	_, err := db.Exec(ctx, deleteSectionEmbed, arg.OrganizationID, arg.ID)
	return err
}

const editorHeartbeat = `-- name: EditorHeartbeat :exec
UPDATE docs.document_editor
SET last_heartbeat = now()
WHERE organization_id = $1 
  AND document_id = $2 
  AND employee_id = $3
`

type EditorHeartbeatParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

func (q *Queries) EditorHeartbeat(ctx context.Context, db DBTX, arg *EditorHeartbeatParams) error {
	_, err := db.Exec(ctx, editorHeartbeat, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	return err
}

const getCommentDocumentID = `-- name: GetCommentDocumentID :one
SELECT document_id FROM docs.comment
WHERE organization_id = $1 AND id = $2
`

type GetCommentDocumentIDParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

func (q *Queries) GetCommentDocumentID(ctx context.Context, db DBTX, arg *GetCommentDocumentIDParams) (dbuuid.UUID, error) {
	row := db.QueryRow(ctx, getCommentDocumentID, arg.OrganizationID, arg.ID)
	var document_id dbuuid.UUID
	err := row.Scan(&document_id)
	return document_id, err
}

const getDepartmentDocumentAccess = `-- name: GetDepartmentDocumentAccess :many
SELECT a.access_level
FROM docs.document_access a
JOIN organization.department_member dm ON (dm.organization_id, dm.department_id) = (a.organization_id, a.grantee_id)
WHERE a.organization_id = $1
  AND a.document_id = $2
  AND a.grantee_type = 'department'
  AND dm.employee_id = $3
`

type GetDepartmentDocumentAccessParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

// Check department-based access for an employee
func (q *Queries) GetDepartmentDocumentAccess(ctx context.Context, db DBTX, arg *GetDepartmentDocumentAccessParams) ([]string, error) {
	rows, err := db.Query(ctx, getDepartmentDocumentAccess, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var access_level string
		if err := rows.Scan(&access_level); err != nil {
			return nil, err
		}
		items = append(items, access_level)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at FROM docs.document
WHERE organization_id = $1 AND id = $2 AND is_deleted = FALSE
`

type GetDocumentByIDParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, db DBTX, arg *GetDocumentByIDParams) (*DocsDocument, error) {
	row := db.QueryRow(ctx, getDocumentByID, arg.OrganizationID, arg.ID)
	var i DocsDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DocumentType,
		&i.ParentDocumentID,
		&i.Depth,
		&i.Path,
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.Visibility,
		&i.OwnerEmployeeID,
		&i.ChildCount,
		&i.VersionCount,
		&i.FollowerCount,
		&i.IsDeleted,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at FROM docs.document
WHERE organization_id = $1 AND slug = $2 AND is_deleted = FALSE
`

type GetDocumentBySlugParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
}

func (q *Queries) GetDocumentBySlug(ctx context.Context, db DBTX, arg *GetDocumentBySlugParams) (*DocsDocument, error) {
	row := db.QueryRow(ctx, getDocumentBySlug, arg.OrganizationID, arg.Slug)
	var i DocsDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DocumentType,
		&i.ParentDocumentID,
		&i.Depth,
		&i.Path,
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.Visibility,
		&i.OwnerEmployeeID,
		&i.ChildCount,
		&i.VersionCount,
		&i.FollowerCount,
		&i.IsDeleted,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDocumentComment = `-- name: GetDocumentComment :one



SELECT
  c.id,
  c.organization_id,
  c.document_id,
  c.comment_text,
  c.author_employee_id,
  c.is_resolved,
  c.updated_at
FROM docs.comment c
WHERE c.organization_id = $1
  AND c.id = $2
`

type GetDocumentCommentParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

type GetDocumentCommentRow struct {
	ID               dbuuid.UUID        `json:"id"`
	OrganizationID   dbuuid.UUID        `json:"organization_id"`
	DocumentID       dbuuid.UUID        `json:"document_id"`
	CommentText      string             `json:"comment_text"`
	AuthorEmployeeID dbuuid.UUID        `json:"author_employee_id"`
	IsResolved       bool               `json:"is_resolved"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// Document Follower Preference-Aware Queries
// ============================================================================
// ============================================================================
// Document Recipient Eligibility Queries (for notification targeting)
// ============================================================================
// Single comment with its author, used by the compliance domain to snapshot a
// reported comment at report time (Feature 036).
func (q *Queries) GetDocumentComment(ctx context.Context, db DBTX, arg *GetDocumentCommentParams) (*GetDocumentCommentRow, error) {
	row := db.QueryRow(ctx, getDocumentComment, arg.OrganizationID, arg.ID)
	var i GetDocumentCommentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.CommentText,
		&i.AuthorEmployeeID,
		&i.IsResolved,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDocumentReactionStats = `-- name: GetDocumentReactionStats :one
SELECT
    d.id,
    COUNT(CASE WHEN r.reaction_type = 'thumbs_up' THEN 1 END)::int AS thumbs_up_count,
    COUNT(CASE WHEN r.reaction_type = 'thumbs_down' THEN 1 END)::int AS thumbs_down_count
FROM docs.document d
LEFT JOIN docs.document_reaction r ON (r.organization_id, r.document_id) = (d.organization_id, d.id)
WHERE d.organization_id = $1
  AND d.id = $2
GROUP BY d.id
`

type GetDocumentReactionStatsParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

type GetDocumentReactionStatsRow struct {
	ID              dbuuid.UUID `json:"id"`
	ThumbsUpCount   int32       `json:"thumbs_up_count"`
	ThumbsDownCount int32       `json:"thumbs_down_count"`
}

func (q *Queries) GetDocumentReactionStats(ctx context.Context, db DBTX, arg *GetDocumentReactionStatsParams) (*GetDocumentReactionStatsRow, error) {
	row := db.QueryRow(ctx, getDocumentReactionStats, arg.OrganizationID, arg.DocumentID)
	var i GetDocumentReactionStatsRow
	err := row.Scan(&i.ID, &i.ThumbsUpCount, &i.ThumbsDownCount)
	return &i, err
}

const getDocumentWithChildren = `-- name: GetDocumentWithChildren :many
SELECT id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at FROM docs.document
WHERE organization_id = $1 
  AND is_deleted = FALSE
  AND (id = $2 OR parent_document_id = $2)
ORDER BY depth, title
`

type GetDocumentWithChildrenParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

// Get a document and its direct children for tree building
func (q *Queries) GetDocumentWithChildren(ctx context.Context, db DBTX, arg *GetDocumentWithChildrenParams) ([]*DocsDocument, error) {
	rows, err := db.Query(ctx, getDocumentWithChildren, arg.OrganizationID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DocsDocument
	for rows.Next() {
		var i DocsDocument
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Slug,
			&i.DocumentType,
			&i.ParentDocumentID,
			&i.Depth,
			&i.Path,
			&i.ContentJson,
			&i.ContentText,
			&i.Status,
			&i.Visibility,
			&i.OwnerEmployeeID,
			&i.ChildCount,
			&i.VersionCount,
			&i.FollowerCount,
			&i.IsDeleted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmbeddedContent = `-- name: GetEmbeddedContent :one
SELECT v.content_json, v.content_text, d.status, d.version_count
FROM docs.document_version v
JOIN docs.document d ON (d.organization_id, d.id) = (v.organization_id, v.document_id)
WHERE v.organization_id = $1 
  AND v.document_id = $2 
  AND v.version_number = $3
  AND d.is_deleted = FALSE
`

type GetEmbeddedContentParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
	VersionNumber  int32       `json:"version_number"`
}

type GetEmbeddedContentRow struct {
	ContentJson  []byte `json:"content_json"`
	ContentText  string `json:"content_text"`
	Status       string `json:"status"`
	VersionCount int32  `json:"version_count"`
}

// Get the target document's content for rendering embedded section at specific version
// This returns the content from the versioned snapshot, not the current document
func (q *Queries) GetEmbeddedContent(ctx context.Context, db DBTX, arg *GetEmbeddedContentParams) (*GetEmbeddedContentRow, error) {
	row := db.QueryRow(ctx, getEmbeddedContent, arg.OrganizationID, arg.ID, arg.VersionNumber)
	var i GetEmbeddedContentRow
	err := row.Scan(
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.VersionCount,
	)
	return &i, err
}

const getEmployeeDocumentAccess = `-- name: GetEmployeeDocumentAccess :one
SELECT access_level FROM docs.document_access
WHERE organization_id = $1 
  AND document_id = $2
  AND grantee_type = 'employee'
  AND grantee_id = $3
`

type GetEmployeeDocumentAccessParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

// Check direct employee access
func (q *Queries) GetEmployeeDocumentAccess(ctx context.Context, db DBTX, arg *GetEmployeeDocumentAccessParams) (string, error) {
	row := db.QueryRow(ctx, getEmployeeDocumentAccess, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	var access_level string
	err := row.Scan(&access_level)
	return access_level, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) AS latest_version
FROM docs.document_version
WHERE organization_id = $1 AND document_id = $2
`

type GetLatestVersionNumberParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

func (q *Queries) GetLatestVersionNumber(ctx context.Context, db DBTX, arg *GetLatestVersionNumberParams) (interface{}, error) {
	row := db.QueryRow(ctx, getLatestVersionNumber, arg.OrganizationID, arg.DocumentID)
	var latest_version interface{}
	err := row.Scan(&latest_version)
	return latest_version, err
}

const getSectionEmbed = `-- name: GetSectionEmbed :one
SELECT e.id, e.organization_id, e.source_document_id, e.source_line_start, e.source_line_end, e.target_document_id, e.target_line_start, e.target_line_end, e.target_version_number, e.updated_at, d.title AS target_document_title, d.status AS target_status, d.version_count AS target_latest_version
FROM docs.section_embed e
JOIN docs.document d ON (d.organization_id, d.id) = (e.organization_id, e.target_document_id)
WHERE e.organization_id = $1 AND e.id = $2
`

type GetSectionEmbedParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	ID             dbuuid.UUID `json:"id"`
}

type GetSectionEmbedRow struct {
	ID                  dbuuid.UUID        `json:"id"`
	OrganizationID      dbuuid.UUID        `json:"organization_id"`
	SourceDocumentID    dbuuid.UUID        `json:"source_document_id"`
	SourceLineStart     int32              `json:"source_line_start"`
	SourceLineEnd       int32              `json:"source_line_end"`
	TargetDocumentID    dbuuid.UUID        `json:"target_document_id"`
	TargetLineStart     int32              `json:"target_line_start"`
	TargetLineEnd       int32              `json:"target_line_end"`
	TargetVersionNumber int32              `json:"target_version_number"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TargetDocumentTitle string             `json:"target_document_title"`
	TargetStatus        string             `json:"target_status"`
	TargetLatestVersion int32              `json:"target_latest_version"`
}

func (q *Queries) GetSectionEmbed(ctx context.Context, db DBTX, arg *GetSectionEmbedParams) (*GetSectionEmbedRow, error) {
	row := db.QueryRow(ctx, getSectionEmbed, arg.OrganizationID, arg.ID)
	var i GetSectionEmbedRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SourceDocumentID,
		&i.SourceLineStart,
		&i.SourceLineEnd,
		&i.TargetDocumentID,
		&i.TargetLineStart,
		&i.TargetLineEnd,
		&i.TargetVersionNumber,
		&i.UpdatedAt,
		&i.TargetDocumentTitle,
		&i.TargetStatus,
		&i.TargetLatestVersion,
	)
	return &i, err
}

const getUserDocumentReaction = `-- name: GetUserDocumentReaction :one
SELECT id, organization_id, document_id, employee_id, reaction_type, updated_at FROM docs.document_reaction
WHERE organization_id = $1
  AND document_id = $2
  AND employee_id = $3
`

type GetUserDocumentReactionParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

func (q *Queries) GetUserDocumentReaction(ctx context.Context, db DBTX, arg *GetUserDocumentReactionParams) (*DocsDocumentReaction, error) {
	row := db.QueryRow(ctx, getUserDocumentReaction, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	var i DocsDocumentReaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.ReactionType,
		&i.UpdatedAt,
	)
	return &i, err
}

const getVersion = `-- name: GetVersion :one
SELECT v.id, v.organization_id, v.document_id, v.version_number, v.content_json, v.content_text, v.author_employee_id, v.summary, v.created_at, e.given_name || ' ' || e.family_name AS author_name
FROM docs.document_version v
JOIN organization.employee e ON (e.organization_id, e.id) = (v.organization_id, v.author_employee_id)
WHERE v.organization_id = $1 
  AND v.document_id = $2 
  AND v.version_number = $3
`

type GetVersionParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	VersionNumber  int32       `json:"version_number"`
}

type GetVersionRow struct {
	ID               dbuuid.UUID        `json:"id"`
	OrganizationID   dbuuid.UUID        `json:"organization_id"`
	DocumentID       dbuuid.UUID        `json:"document_id"`
	VersionNumber    int32              `json:"version_number"`
	ContentJson      []byte             `json:"content_json"`
	ContentText      string             `json:"content_text"`
	AuthorEmployeeID dbuuid.UUID        `json:"author_employee_id"`
	Summary          pgtype.Text        `json:"summary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AuthorName       interface{}        `json:"author_name"`
}

func (q *Queries) GetVersion(ctx context.Context, db DBTX, arg *GetVersionParams) (*GetVersionRow, error) {
	row := db.QueryRow(ctx, getVersion, arg.OrganizationID, arg.DocumentID, arg.VersionNumber)
	var i GetVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.ContentJson,
		&i.ContentText,
		&i.AuthorEmployeeID,
		&i.Summary,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return &i, err
}

const getVersionRange = `-- name: GetVersionRange :many
SELECT v.id, v.organization_id, v.document_id, v.version_number, v.content_json, v.content_text, v.author_employee_id, v.summary, v.created_at, e.given_name || ' ' || e.family_name AS author_name
FROM docs.document_version v
JOIN organization.employee e ON (e.organization_id, e.id) = (v.organization_id, v.author_employee_id)
WHERE v.organization_id = $1 
  AND v.document_id = $2
  AND v.version_number >= $3
  AND v.version_number <= $4
ORDER BY v.version_number ASC
`

type GetVersionRangeParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	FromVersion    int32       `json:"from_version"`
	ToVersion      int32       `json:"to_version"`
}

type GetVersionRangeRow struct {
	ID               dbuuid.UUID        `json:"id"`
	OrganizationID   dbuuid.UUID        `json:"organization_id"`
	DocumentID       dbuuid.UUID        `json:"document_id"`
	VersionNumber    int32              `json:"version_number"`
	ContentJson      []byte             `json:"content_json"`
	ContentText      string             `json:"content_text"`
	AuthorEmployeeID dbuuid.UUID        `json:"author_employee_id"`
	Summary          pgtype.Text        `json:"summary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AuthorName       interface{}        `json:"author_name"`
}

// For computing diffs between versions
func (q *Queries) GetVersionRange(ctx context.Context, db DBTX, arg *GetVersionRangeParams) ([]*GetVersionRangeRow, error) {
	rows, err := db.Query(ctx, getVersionRange,
		arg.OrganizationID,
		arg.DocumentID,
		arg.FromVersion,
		arg.ToVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetVersionRangeRow
	for rows.Next() {
		var i GetVersionRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.ContentJson,
			&i.ContentText,
			&i.AuthorEmployeeID,
			&i.Summary,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementChildCount = `-- name: IncrementChildCount :exec
UPDATE docs.document
SET child_count = child_count + 1, updated_at = $1
WHERE organization_id = $2 AND id = $3
`

type IncrementChildCountParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) IncrementChildCount(ctx context.Context, db DBTX, arg *IncrementChildCountParams) error {
	_, err := db.Exec(ctx, incrementChildCount, arg.UpdatedAt, arg.OrganizationID, arg.ID)
	return err
}

const incrementCommentReplyCount = `-- name: IncrementCommentReplyCount :exec
UPDATE docs.comment
SET reply_count = reply_count + 1, updated_at = $1
WHERE organization_id = $2 AND id = $3
`

type IncrementCommentReplyCountParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) IncrementCommentReplyCount(ctx context.Context, db DBTX, arg *IncrementCommentReplyCountParams) error {
	_, err := db.Exec(ctx, incrementCommentReplyCount, arg.UpdatedAt, arg.OrganizationID, arg.ID)
	return err
}

const joinDocumentAsEditor = `-- name: JoinDocumentAsEditor :exec

INSERT INTO docs.document_editor (
    organization_id, document_id, employee_id, connection_id, 
    instance_id, cursor_position, connected_at, last_heartbeat
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $7
)
ON CONFLICT (organization_id, document_id, employee_id) 
DO UPDATE SET 
    connection_id = EXCLUDED.connection_id,
    instance_id = EXCLUDED.instance_id,
    connected_at = EXCLUDED.connected_at,
    last_heartbeat = EXCLUDED.last_heartbeat
`

type JoinDocumentAsEditorParams struct {
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	DocumentID     dbuuid.UUID        `json:"document_id"`
	EmployeeID     dbuuid.UUID        `json:"employee_id"`
	ConnectionID   dbuuid.UUID        `json:"connection_id"`
	InstanceID     string             `json:"instance_id"`
	CursorPosition []byte             `json:"cursor_position"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
}

// ============================================================================
// ACTIVE EDITORS (UNLOGGED table for collaborative editing)
// ============================================================================
func (q *Queries) JoinDocumentAsEditor(ctx context.Context, db DBTX, arg *JoinDocumentAsEditorParams) error {
	_, err := db.Exec(ctx, joinDocumentAsEditor,
		arg.OrganizationID,
		arg.DocumentID,
		arg.EmployeeID,
		arg.ConnectionID,
		arg.InstanceID,
		arg.CursorPosition,
		arg.ConnectedAt,
	)
	return err
}

const leaveDocument = `-- name: LeaveDocument :exec
DELETE FROM docs.document_editor
WHERE organization_id = $1 
  AND document_id = $2 
  AND employee_id = $3
`

type LeaveDocumentParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

func (q *Queries) LeaveDocument(ctx context.Context, db DBTX, arg *LeaveDocumentParams) error {
	_, err := db.Exec(ctx, leaveDocument, arg.OrganizationID, arg.DocumentID, arg.EmployeeID)
	return err
}

const listActiveEditors = `-- name: ListActiveEditors :many
SELECT 
    e.organization_id, e.document_id, e.employee_id, e.connection_id, e.instance_id, e.cursor_position, e.connected_at, e.last_heartbeat,
    emp.given_name || ' ' || emp.family_name AS employee_name
FROM docs.document_editor e
JOIN organization.employee emp ON (emp.organization_id, emp.id) = (e.organization_id, e.employee_id)
WHERE e.organization_id = $1 
  AND e.document_id = $2
  AND e.last_heartbeat > now() - interval '60 seconds'
`

type ListActiveEditorsParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

type ListActiveEditorsRow struct {
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	DocumentID     dbuuid.UUID        `json:"document_id"`
	EmployeeID     dbuuid.UUID        `json:"employee_id"`
	ConnectionID   dbuuid.UUID        `json:"connection_id"`
	InstanceID     string             `json:"instance_id"`
	CursorPosition []byte             `json:"cursor_position"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	EmployeeName   interface{}        `json:"employee_name"`
}

func (q *Queries) ListActiveEditors(ctx context.Context, db DBTX, arg *ListActiveEditorsParams) ([]*ListActiveEditorsRow, error) {
	rows, err := db.Query(ctx, listActiveEditors, arg.OrganizationID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActiveEditorsRow
	for rows.Next() {
		var i ListActiveEditorsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.DocumentID,
			&i.EmployeeID,
			&i.ConnectionID,
			&i.InstanceID,
			&i.CursorPosition,
			&i.ConnectedAt,
			&i.LastHeartbeat,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildDocuments = `-- name: ListChildDocuments :many
SELECT id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at FROM docs.document
WHERE organization_id = $1 
  AND parent_document_id = $2
  AND is_deleted = FALSE
  AND ($3::text IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR id < $4)
ORDER BY id DESC
LIMIT $5
`

type ListChildDocumentsParams struct {
	OrganizationID   dbuuid.UUID     `json:"organization_id"`
	ParentDocumentID dbuuid.NullUUID `json:"parent_document_id"`
	Status           pgtype.Text     `json:"status"`
	Cursor           dbuuid.NullUUID `json:"cursor"`
	DocLimit         int32           `json:"doc_limit"`
}

func (q *Queries) ListChildDocuments(ctx context.Context, db DBTX, arg *ListChildDocumentsParams) ([]*DocsDocument, error) {
	rows, err := db.Query(ctx, listChildDocuments,
		arg.OrganizationID,
		arg.ParentDocumentID,
		arg.Status,
		arg.Cursor,
		arg.DocLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DocsDocument
	for rows.Next() {
		var i DocsDocument
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Slug,
			&i.DocumentType,
			&i.ParentDocumentID,
			&i.Depth,
			&i.Path,
			&i.ContentJson,
			&i.ContentText,
			&i.Status,
			&i.Visibility,
			&i.OwnerEmployeeID,
			&i.ChildCount,
			&i.VersionCount,
			&i.FollowerCount,
			&i.IsDeleted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentAccess = `-- name: ListDocumentAccess :many
SELECT 
    a.id, a.organization_id, a.document_id, a.grantee_type, a.grantee_id, a.access_level, a.granted_by_employee_id, a.updated_at,
    CASE 
        WHEN a.grantee_type = 'employee' THEN e.given_name || ' ' || e.family_name
        WHEN a.grantee_type = 'department' THEN d.name
    END AS grantee_name,
    g.given_name || ' ' || g.family_name AS granted_by_name
FROM docs.document_access a
LEFT JOIN organization.employee e ON a.grantee_type = 'employee' 
    AND (e.organization_id, e.id) = (a.organization_id, a.grantee_id)
LEFT JOIN organization.department d ON a.grantee_type = 'department'
    AND (d.organization_id, d.id) = (a.organization_id, a.grantee_id)
JOIN organization.employee g ON (g.organization_id, g.id) = (a.organization_id, a.granted_by_employee_id)
WHERE a.organization_id = $1 AND a.document_id = $2
`

type ListDocumentAccessParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
}

type ListDocumentAccessRow struct {
	ID                  dbuuid.UUID        `json:"id"`
	OrganizationID      dbuuid.UUID        `json:"organization_id"`
	DocumentID          dbuuid.UUID        `json:"document_id"`
	GranteeType         string             `json:"grantee_type"`
	GranteeID           dbuuid.UUID        `json:"grantee_id"`
	AccessLevel         string             `json:"access_level"`
	GrantedByEmployeeID dbuuid.UUID        `json:"granted_by_employee_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	GranteeName         interface{}        `json:"grantee_name"`
	GrantedByName       interface{}        `json:"granted_by_name"`
}

func (q *Queries) ListDocumentAccess(ctx context.Context, db DBTX, arg *ListDocumentAccessParams) ([]*ListDocumentAccessRow, error) {
	rows, err := db.Query(ctx, listDocumentAccess, arg.OrganizationID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDocumentAccessRow
	for rows.Next() {
		var i ListDocumentAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.GranteeType,
			&i.GranteeID,
			&i.AccessLevel,
			&i.GrantedByEmployeeID,
			&i.UpdatedAt,
			&i.GranteeName,
			&i.GrantedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentComments = `-- name: ListDocumentComments :many
SELECT 
    c.id, c.organization_id, c.document_id, c.block_id, c.text_selection_start, c.text_selection_end, c.comment_text, c.author_employee_id, c.is_resolved, c.resolved_by_employee_id, c.resolved_at, c.reply_count, c.updated_at,
    e.given_name || ' ' || e.family_name AS author_name,
    r.given_name || ' ' || r.family_name AS resolved_by_name
FROM docs.comment c
JOIN organization.employee e ON (e.organization_id, e.id) = (c.organization_id, c.author_employee_id)
LEFT JOIN organization.employee r ON c.is_resolved AND (r.organization_id, r.id) = (c.organization_id, c.resolved_by_employee_id)
WHERE c.organization_id = $1 
  AND c.document_id = $2
  AND ($3 OR c.is_resolved = FALSE)
ORDER BY c.updated_at DESC
`

type ListDocumentCommentsParams struct {
	OrganizationID  dbuuid.UUID `json:"organization_id"`
	DocumentID      dbuuid.UUID `json:"document_id"`
	IncludeResolved interface{} `json:"include_resolved"`
}

type ListDocumentCommentsRow struct {
	ID                   dbuuid.UUID        `json:"id"`
	OrganizationID       dbuuid.UUID        `json:"organization_id"`
	DocumentID           dbuuid.UUID        `json:"document_id"`
	BlockID              dbuuid.NullUUID    `json:"block_id"`
	TextSelectionStart   pgtype.Int4        `json:"text_selection_start"`
	TextSelectionEnd     pgtype.Int4        `json:"text_selection_end"`
	CommentText          string             `json:"comment_text"`
	AuthorEmployeeID     dbuuid.UUID        `json:"author_employee_id"`
	IsResolved           bool               `json:"is_resolved"`
	ResolvedByEmployeeID dbuuid.NullUUID    `json:"resolved_by_employee_id"`
	ResolvedAt           pgtype.Timestamptz `json:"resolved_at"`
	ReplyCount           int32              `json:"reply_count"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AuthorName           interface{}        `json:"author_name"`
	ResolvedByName       interface{}        `json:"resolved_by_name"`
}

func (q *Queries) ListDocumentComments(ctx context.Context, db DBTX, arg *ListDocumentCommentsParams) ([]*ListDocumentCommentsRow, error) {
	rows, err := db.Query(ctx, listDocumentComments, arg.OrganizationID, arg.DocumentID, arg.IncludeResolved)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDocumentCommentsRow
	for rows.Next() {
		var i ListDocumentCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.BlockID,
			&i.TextSelectionStart,
			&i.TextSelectionEnd,
			&i.CommentText,
			&i.AuthorEmployeeID,
			&i.IsResolved,
			&i.ResolvedByEmployeeID,
			&i.ResolvedAt,
			&i.ReplyCount,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.ResolvedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentEmbeds = `-- name: ListDocumentEmbeds :many
SELECT e.id, e.organization_id, e.source_document_id, e.source_line_start, e.source_line_end, e.target_document_id, e.target_line_start, e.target_line_end, e.target_version_number, e.updated_at, d.title AS target_document_title, d.status AS target_status, d.version_count AS target_latest_version
FROM docs.section_embed e
JOIN docs.document d ON (d.organization_id, d.id) = (e.organization_id, e.target_document_id)
WHERE e.organization_id = $1 AND e.source_document_id = $2
`

type ListDocumentEmbedsParams struct {
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	SourceDocumentID dbuuid.UUID `json:"source_document_id"`
}

type ListDocumentEmbedsRow struct {
	ID                  dbuuid.UUID        `json:"id"`
	OrganizationID      dbuuid.UUID        `json:"organization_id"`
	SourceDocumentID    dbuuid.UUID        `json:"source_document_id"`
	SourceLineStart     int32              `json:"source_line_start"`
	SourceLineEnd       int32              `json:"source_line_end"`
	TargetDocumentID    dbuuid.UUID        `json:"target_document_id"`
	TargetLineStart     int32              `json:"target_line_start"`
	TargetLineEnd       int32              `json:"target_line_end"`
	TargetVersionNumber int32              `json:"target_version_number"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TargetDocumentTitle string             `json:"target_document_title"`
	TargetStatus        string             `json:"target_status"`
	TargetLatestVersion int32              `json:"target_latest_version"`
}

func (q *Queries) ListDocumentEmbeds(ctx context.Context, db DBTX, arg *ListDocumentEmbedsParams) ([]*ListDocumentEmbedsRow, error) {
	rows, err := db.Query(ctx, listDocumentEmbeds, arg.OrganizationID, arg.SourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDocumentEmbedsRow
	for rows.Next() {
		var i ListDocumentEmbedsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SourceDocumentID,
			&i.SourceLineStart,
			&i.SourceLineEnd,
			&i.TargetDocumentID,
			&i.TargetLineStart,
			&i.TargetLineEnd,
			&i.TargetVersionNumber,
			&i.UpdatedAt,
			&i.TargetDocumentTitle,
			&i.TargetStatus,
			&i.TargetLatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbedsBySource = `-- name: ListEmbedsBySource :many
SELECT id, organization_id, source_document_id, target_document_id
FROM docs.section_embed
WHERE organization_id = $1 AND source_document_id = $2
`

type ListEmbedsBySourceParams struct {
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	SourceDocumentID dbuuid.UUID `json:"source_document_id"`
}

type ListEmbedsBySourceRow struct {
	ID               dbuuid.UUID `json:"id"`
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	SourceDocumentID dbuuid.UUID `json:"source_document_id"`
	TargetDocumentID dbuuid.UUID `json:"target_document_id"`
}

// Get all embeds created from this source document
// Used for cleanup when embeds are removed from document content
func (q *Queries) ListEmbedsBySource(ctx context.Context, db DBTX, arg *ListEmbedsBySourceParams) ([]*ListEmbedsBySourceRow, error) {
	rows, err := db.Query(ctx, listEmbedsBySource, arg.OrganizationID, arg.SourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEmbedsBySourceRow
	for rows.Next() {
		var i ListEmbedsBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SourceDocumentID,
			&i.TargetDocumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingCitations = `-- name: ListIncomingCitations :many
SELECT 
    e.id,
    e.organization_id,
    e.source_document_id,
    e.source_line_start,
    e.source_line_end,
    e.target_document_id,
    e.target_line_start,
    e.target_line_end,
    COALESCE(e.target_version_number, target_d.version_count) AS target_version_number,
    e.updated_at,
    source_d.title AS source_document_title,
    source_d.slug AS source_document_slug,
    source_d.owner_employee_id AS source_owner_employee_id,
    emp.given_name || ' ' || emp.family_name AS source_owner_name,
    source_d.updated_at AS source_updated_at,
    target_d.version_count AS target_current_version
FROM docs.section_embed e
JOIN docs.document source_d ON (source_d.organization_id, source_d.id) = (e.organization_id, e.source_document_id)
JOIN docs.document target_d ON (target_d.organization_id, target_d.id) = (e.organization_id, e.target_document_id)
JOIN organization.employee emp ON (emp.organization_id, emp.id) = (source_d.organization_id, source_d.owner_employee_id)
WHERE e.organization_id = $1 
  AND e.target_document_id = $2
  AND source_d.is_deleted = FALSE
ORDER BY e.target_line_start ASC, source_d.updated_at DESC
`

type ListIncomingCitationsParams struct {
	OrganizationID   dbuuid.UUID `json:"organization_id"`
	TargetDocumentID dbuuid.UUID `json:"target_document_id"`
}

type ListIncomingCitationsRow struct {
	ID                    dbuuid.UUID        `json:"id"`
	OrganizationID        dbuuid.UUID        `json:"organization_id"`
	SourceDocumentID      dbuuid.UUID        `json:"source_document_id"`
	SourceLineStart       int32              `json:"source_line_start"`
	SourceLineEnd         int32              `json:"source_line_end"`
	TargetDocumentID      dbuuid.UUID        `json:"target_document_id"`
	TargetLineStart       int32              `json:"target_line_start"`
	TargetLineEnd         int32              `json:"target_line_end"`
	TargetVersionNumber   int32              `json:"target_version_number"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	SourceDocumentTitle   string             `json:"source_document_title"`
	SourceDocumentSlug    string             `json:"source_document_slug"`
	SourceOwnerEmployeeID dbuuid.UUID        `json:"source_owner_employee_id"`
	SourceOwnerName       interface{}        `json:"source_owner_name"`
	SourceUpdatedAt       pgtype.Timestamptz `json:"source_updated_at"`
	TargetCurrentVersion  int32              `json:"target_current_version"`
}

// Get all embeds that cite this document (incoming citations)
// Used to show document owners who is citing their content
func (q *Queries) ListIncomingCitations(ctx context.Context, db DBTX, arg *ListIncomingCitationsParams) ([]*ListIncomingCitationsRow, error) {
	rows, err := db.Query(ctx, listIncomingCitations, arg.OrganizationID, arg.TargetDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListIncomingCitationsRow
	for rows.Next() {
		var i ListIncomingCitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SourceDocumentID,
			&i.SourceLineStart,
			&i.SourceLineEnd,
			&i.TargetDocumentID,
			&i.TargetLineStart,
			&i.TargetLineEnd,
			&i.TargetVersionNumber,
			&i.UpdatedAt,
			&i.SourceDocumentTitle,
			&i.SourceDocumentSlug,
			&i.SourceOwnerEmployeeID,
			&i.SourceOwnerName,
			&i.SourceUpdatedAt,
			&i.TargetCurrentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDocuments = `-- name: ListRootDocuments :many
SELECT id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at FROM docs.document
WHERE organization_id = $1 
  AND parent_document_id IS NULL 
  AND is_deleted = FALSE
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListRootDocumentsParams struct {
	OrganizationID dbuuid.UUID     `json:"organization_id"`
	Status         pgtype.Text     `json:"status"`
	Cursor         dbuuid.NullUUID `json:"cursor"`
	DocLimit       int32           `json:"doc_limit"`
}

func (q *Queries) ListRootDocuments(ctx context.Context, db DBTX, arg *ListRootDocumentsParams) ([]*DocsDocument, error) {
	rows, err := db.Query(ctx, listRootDocuments,
		arg.OrganizationID,
		arg.Status,
		arg.Cursor,
		arg.DocLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DocsDocument
	for rows.Next() {
		var i DocsDocument
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Slug,
			&i.DocumentType,
			&i.ParentDocumentID,
			&i.Depth,
			&i.Path,
			&i.ContentJson,
			&i.ContentText,
			&i.Status,
			&i.Visibility,
			&i.OwnerEmployeeID,
			&i.ChildCount,
			&i.VersionCount,
			&i.FollowerCount,
			&i.IsDeleted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT v.id, v.organization_id, v.document_id, v.version_number, v.content_json, v.content_text, v.author_employee_id, v.summary, v.created_at, e.given_name || ' ' || e.family_name AS author_name
FROM docs.document_version v
JOIN organization.employee e ON (e.organization_id, e.id) = (v.organization_id, v.author_employee_id)
WHERE v.organization_id = $1 AND v.document_id = $2
  AND ($3::int IS NULL OR v.version_number < $3)
ORDER BY v.version_number DESC
LIMIT $4
`

type ListVersionsParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	Cursor         pgtype.Int4 `json:"cursor"`
	VersionLimit   int32       `json:"version_limit"`
}

type ListVersionsRow struct {
	ID               dbuuid.UUID        `json:"id"`
	OrganizationID   dbuuid.UUID        `json:"organization_id"`
	DocumentID       dbuuid.UUID        `json:"document_id"`
	VersionNumber    int32              `json:"version_number"`
	ContentJson      []byte             `json:"content_json"`
	ContentText      string             `json:"content_text"`
	AuthorEmployeeID dbuuid.UUID        `json:"author_employee_id"`
	Summary          pgtype.Text        `json:"summary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AuthorName       interface{}        `json:"author_name"`
}

func (q *Queries) ListVersions(ctx context.Context, db DBTX, arg *ListVersionsParams) ([]*ListVersionsRow, error) {
	rows, err := db.Query(ctx, listVersions,
		arg.OrganizationID,
		arg.DocumentID,
		arg.Cursor,
		arg.VersionLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVersionsRow
	for rows.Next() {
		var i ListVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.ContentJson,
			&i.ContentText,
			&i.AuthorEmployeeID,
			&i.Summary,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanChildren = `-- name: OrphanChildren :execrows
UPDATE docs.document
SET parent_document_id = NULL, depth = 0, path = ARRAY[]::uuid[], updated_at = $1
WHERE organization_id = $2 AND parent_document_id = $3 AND is_deleted = FALSE
`

type OrphanChildrenParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ParentID       dbuuid.NullUUID    `json:"parent_id"`
}

// When parent is deleted, children become root documents
func (q *Queries) OrphanChildren(ctx context.Context, db DBTX, arg *OrphanChildrenParams) (int64, error) {
	result, err := db.Exec(ctx, orphanChildren, arg.UpdatedAt, arg.OrganizationID, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeDocumentAccess = `-- name: RemoveDocumentAccess :exec
DELETE FROM docs.document_access
WHERE organization_id = $1 
  AND document_id = $2
  AND grantee_type = $3
  AND grantee_id = $4
`

type RemoveDocumentAccessParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	GranteeType    string      `json:"grantee_type"`
	GranteeID      dbuuid.UUID `json:"grantee_id"`
}

func (q *Queries) RemoveDocumentAccess(ctx context.Context, db DBTX, arg *RemoveDocumentAccessParams) error {
	_, err := db.Exec(ctx, removeDocumentAccess,
		arg.OrganizationID,
		arg.DocumentID,
		arg.GranteeType,
		arg.GranteeID,
	)
	return err
}

const resolveComment = `-- name: ResolveComment :one
UPDATE docs.comment
SET is_resolved = TRUE, resolved_by_employee_id = $1, resolved_at = $2, updated_at = $3
WHERE organization_id = $4 AND id = $5
RETURNING id, organization_id, document_id, block_id, text_selection_start, text_selection_end, comment_text, author_employee_id, is_resolved, resolved_by_employee_id, resolved_at, reply_count, updated_at
`

type ResolveCommentParams struct {
	ResolvedBy     dbuuid.NullUUID    `json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) ResolveComment(ctx context.Context, db DBTX, arg *ResolveCommentParams) (*DocsComment, error) {
	row := db.QueryRow(ctx, resolveComment,
		arg.ResolvedBy,
		arg.ResolvedAt,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
	)
	var i DocsComment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.BlockID,
		&i.TextSelectionStart,
		&i.TextSelectionEnd,
		&i.CommentText,
		&i.AuthorEmployeeID,
		&i.IsResolved,
		&i.ResolvedByEmployeeID,
		&i.ResolvedAt,
		&i.ReplyCount,
		&i.UpdatedAt,
	)
	return &i, err
}

const resolveOldSlug = `-- name: ResolveOldSlug :one
SELECT document_id FROM docs.document_slug_history
WHERE organization_id = $1 AND old_slug = $2
`

type ResolveOldSlugParams struct {
	OrganizationID dbuuid.UUID `json:"organization_id"`
	OldSlug        string      `json:"old_slug"`
}

func (q *Queries) ResolveOldSlug(ctx context.Context, db DBTX, arg *ResolveOldSlugParams) (dbuuid.UUID, error) {
	row := db.QueryRow(ctx, resolveOldSlug, arg.OrganizationID, arg.OldSlug)
	var document_id dbuuid.UUID
	err := row.Scan(&document_id)
	return document_id, err
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT 
    d.id, d.organization_id, d.title, d.slug, d.document_type, d.parent_document_id, d.depth, d.path, d.content_json, d.content_text, d.status, d.visibility, d.owner_employee_id, d.child_count, d.version_count, d.follower_count, d.is_deleted, d.updated_at,
    pgroonga_score(tableoid, ctid) AS score,
    pgroonga_snippet_html(
        d.content_text, 
        pgroonga_query_extract_keywords($1),
        200  -- snippet length
    ) AS snippet
FROM docs.document d
WHERE d.organization_id = $2
  AND d.is_deleted = FALSE
  AND ($3::text IS NULL OR d.status = $3)
  AND d.content_text &@~ $1
  AND ($4::uuid IS NULL OR d.id < $4)
ORDER BY score DESC, d.id DESC
LIMIT $5
`

type SearchDocumentsParams struct {
	Query          interface{}     `json:"query"`
	OrganizationID dbuuid.UUID     `json:"organization_id"`
	Status         pgtype.Text     `json:"status"`
	Cursor         dbuuid.NullUUID `json:"cursor"`
	SearchLimit    int32           `json:"search_limit"`
}

type SearchDocumentsRow struct {
	ID               dbuuid.UUID        `json:"id"`
	OrganizationID   dbuuid.UUID        `json:"organization_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	DocumentType     string             `json:"document_type"`
	ParentDocumentID dbuuid.NullUUID    `json:"parent_document_id"`
	Depth            int16              `json:"depth"`
	Path             []dbuuid.UUID      `json:"path"`
	ContentJson      []byte             `json:"content_json"`
	ContentText      string             `json:"content_text"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	OwnerEmployeeID  dbuuid.UUID        `json:"owner_employee_id"`
	ChildCount       int32              `json:"child_count"`
	VersionCount     int32              `json:"version_count"`
	FollowerCount    int32              `json:"follower_count"`
	IsDeleted        bool               `json:"is_deleted"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Score            interface{}        `json:"score"`
	Snippet          interface{}        `json:"snippet"`
}

// PGroonga full-text search with weighted scoring
// Title matches score higher (2x) than content matches
func (q *Queries) SearchDocuments(ctx context.Context, db DBTX, arg *SearchDocumentsParams) ([]*SearchDocumentsRow, error) {
	rows, err := db.Query(ctx, searchDocuments,
		arg.Query,
		arg.OrganizationID,
		arg.Status,
		arg.Cursor,
		arg.SearchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchDocumentsRow
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Slug,
			&i.DocumentType,
			&i.ParentDocumentID,
			&i.Depth,
			&i.Path,
			&i.ContentJson,
			&i.ContentText,
			&i.Status,
			&i.Visibility,
			&i.OwnerEmployeeID,
			&i.ChildCount,
			&i.VersionCount,
			&i.FollowerCount,
			&i.IsDeleted,
			&i.UpdatedAt,
			&i.Score,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentAccess = `-- name: SetDocumentAccess :one

INSERT INTO docs.document_access (
    id, organization_id, document_id, grantee_type, 
    grantee_id, access_level, granted_by_employee_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (organization_id, document_id, grantee_type, grantee_id) 
DO UPDATE SET 
    access_level = EXCLUDED.access_level,
    granted_by_employee_id = EXCLUDED.granted_by_employee_id,
    updated_at = $8
RETURNING id, organization_id, document_id, grantee_type, grantee_id, access_level, granted_by_employee_id, updated_at
`

type SetDocumentAccessParams struct {
	ID                  dbuuid.UUID        `json:"id"`
	OrganizationID      dbuuid.UUID        `json:"organization_id"`
	DocumentID          dbuuid.UUID        `json:"document_id"`
	GranteeType         string             `json:"grantee_type"`
	GranteeID           dbuuid.UUID        `json:"grantee_id"`
	AccessLevel         string             `json:"access_level"`
	GrantedByEmployeeID dbuuid.UUID        `json:"granted_by_employee_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// ACCESS CONTROL
// ============================================================================
func (q *Queries) SetDocumentAccess(ctx context.Context, db DBTX, arg *SetDocumentAccessParams) (*DocsDocumentAccess, error) {
	row := db.QueryRow(ctx, setDocumentAccess,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentID,
		arg.GranteeType,
		arg.GranteeID,
		arg.AccessLevel,
		arg.GrantedByEmployeeID,
		arg.UpdatedAt,
	)
	var i DocsDocumentAccess
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.GranteeType,
		&i.GranteeID,
		&i.AccessLevel,
		&i.GrantedByEmployeeID,
		&i.UpdatedAt,
	)
	return &i, err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE docs.document
SET is_deleted = TRUE, updated_at = $1
WHERE organization_id = $2 AND id = $3
`

type SoftDeleteDocumentParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, db DBTX, arg *SoftDeleteDocumentParams) error {
	_, err := db.Exec(ctx, softDeleteDocument, arg.UpdatedAt, arg.OrganizationID, arg.ID)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE docs.document
SET 
    title = $1,
    slug = $2,
    content_json = $3,
    content_text = $4,
    version_count = version_count + 1,
    updated_at = $5
WHERE organization_id = $6 AND id = $7 AND is_deleted = FALSE
RETURNING id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at
`

type UpdateDocumentParams struct {
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	ContentJson    []byte             `json:"content_json"`
	ContentText    string             `json:"content_text"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, db DBTX, arg *UpdateDocumentParams) (*DocsDocument, error) {
	row := db.QueryRow(ctx, updateDocument,
		arg.Title,
		arg.Slug,
		arg.ContentJson,
		arg.ContentText,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
	)
	var i DocsDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DocumentType,
		&i.ParentDocumentID,
		&i.Depth,
		&i.Path,
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.Visibility,
		&i.OwnerEmployeeID,
		&i.ChildCount,
		&i.VersionCount,
		&i.FollowerCount,
		&i.IsDeleted,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE docs.document
SET status = $1, updated_at = $2
WHERE organization_id = $3 AND id = $4 AND is_deleted = FALSE
RETURNING id, organization_id, title, slug, document_type, parent_document_id, depth, path, content_json, content_text, status, visibility, owner_employee_id, child_count, version_count, follower_count, is_deleted, updated_at
`

type UpdateDocumentStatusParams struct {
	Status         string             `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	ID             dbuuid.UUID        `json:"id"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, db DBTX, arg *UpdateDocumentStatusParams) (*DocsDocument, error) {
	row := db.QueryRow(ctx, updateDocumentStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
	)
	var i DocsDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DocumentType,
		&i.ParentDocumentID,
		&i.Depth,
		&i.Path,
		&i.ContentJson,
		&i.ContentText,
		&i.Status,
		&i.Visibility,
		&i.OwnerEmployeeID,
		&i.ChildCount,
		&i.VersionCount,
		&i.FollowerCount,
		&i.IsDeleted,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateEditorCursor = `-- name: UpdateEditorCursor :exec
UPDATE docs.document_editor
SET cursor_position = $1, last_heartbeat = now()
WHERE organization_id = $2 
  AND document_id = $3 
  AND employee_id = $4
`

type UpdateEditorCursorParams struct {
	CursorPosition []byte      `json:"cursor_position"`
	OrganizationID dbuuid.UUID `json:"organization_id"`
	DocumentID     dbuuid.UUID `json:"document_id"`
	EmployeeID     dbuuid.UUID `json:"employee_id"`
}

func (q *Queries) UpdateEditorCursor(ctx context.Context, db DBTX, arg *UpdateEditorCursorParams) error {
	_, err := db.Exec(ctx, updateEditorCursor,
		arg.CursorPosition,
		arg.OrganizationID,
		arg.DocumentID,
		arg.EmployeeID,
	)
	return err
}

const upsertDocumentReaction = `-- name: UpsertDocumentReaction :one
INSERT INTO docs.document_reaction (
    id, organization_id, document_id, employee_id, reaction_type
)
VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (organization_id, document_id, employee_id) 
DO UPDATE SET 
    reaction_type = EXCLUDED.reaction_type,
    updated_at = $6
RETURNING id, organization_id, document_id, employee_id, reaction_type, updated_at
`

type UpsertDocumentReactionParams struct {
	ID             dbuuid.UUID        `json:"id"`
	OrganizationID dbuuid.UUID        `json:"organization_id"`
	DocumentID     dbuuid.UUID        `json:"document_id"`
	EmployeeID     dbuuid.UUID        `json:"employee_id"`
	ReactionType   string             `json:"reaction_type"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertDocumentReaction(ctx context.Context, db DBTX, arg *UpsertDocumentReactionParams) (*DocsDocumentReaction, error) {
	row := db.QueryRow(ctx, upsertDocumentReaction,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentID,
		arg.EmployeeID,
		arg.ReactionType,
		arg.UpdatedAt,
	)
	var i DocsDocumentReaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.ReactionType,
		&i.UpdatedAt,
	)
	return &i, err
}
