// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/v1/preference.proto

package rpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nvcnvn/tech-office/backend/rpc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PreferenceServiceName is the fully-qualified name of the PreferenceService service.
	PreferenceServiceName = "rpc.v1.PreferenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PreferenceServiceGetUserPreferenceProcedure is the fully-qualified name of the
	// PreferenceService's GetUserPreference RPC.
	PreferenceServiceGetUserPreferenceProcedure = "/rpc.v1.PreferenceService/GetUserPreference"
	// PreferenceServiceUpdateUserPreferenceProcedure is the fully-qualified name of the
	// PreferenceService's UpdateUserPreference RPC.
	PreferenceServiceUpdateUserPreferenceProcedure = "/rpc.v1.PreferenceService/UpdateUserPreference"
	// PreferenceServiceResetUserPreferenceProcedure is the fully-qualified name of the
	// PreferenceService's ResetUserPreference RPC.
	PreferenceServiceResetUserPreferenceProcedure = "/rpc.v1.PreferenceService/ResetUserPreference"
)

// PreferenceServiceClient is a client for the rpc.v1.PreferenceService service.
type PreferenceServiceClient interface {
	// GetUserPreference retrieves the current user's preference settings.
	// Returns default values if no preference record exists.
	GetUserPreference(context.Context, *connect.Request[v1.GetUserPreferenceRequest]) (*connect.Response[v1.GetUserPreferenceResponse], error)
	// UpdateUserPreference updates the current user's preference settings.
	// Creates a new preference record if none exists (upsert behavior).
	UpdateUserPreference(context.Context, *connect.Request[v1.UpdateUserPreferenceRequest]) (*connect.Response[v1.UpdateUserPreferenceResponse], error)
	// ResetUserPreference deletes the current user's preference record,
	// causing the system to revert to default values and OS preferences.
	ResetUserPreference(context.Context, *connect.Request[v1.ResetUserPreferenceRequest]) (*connect.Response[v1.ResetUserPreferenceResponse], error)
}

// NewPreferenceServiceClient constructs a client for the rpc.v1.PreferenceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPreferenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PreferenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	preferenceServiceMethods := v1.File_rpc_v1_preference_proto.Services().ByName("PreferenceService").Methods()
	return &preferenceServiceClient{
		getUserPreference: connect.NewClient[v1.GetUserPreferenceRequest, v1.GetUserPreferenceResponse](
			httpClient,
			baseURL+PreferenceServiceGetUserPreferenceProcedure,
			connect.WithSchema(preferenceServiceMethods.ByName("GetUserPreference")),
			connect.WithClientOptions(opts...),
		),
		updateUserPreference: connect.NewClient[v1.UpdateUserPreferenceRequest, v1.UpdateUserPreferenceResponse](
			httpClient,
			baseURL+PreferenceServiceUpdateUserPreferenceProcedure,
			connect.WithSchema(preferenceServiceMethods.ByName("UpdateUserPreference")),
			connect.WithClientOptions(opts...),
		),
		resetUserPreference: connect.NewClient[v1.ResetUserPreferenceRequest, v1.ResetUserPreferenceResponse](
			httpClient,
			baseURL+PreferenceServiceResetUserPreferenceProcedure,
			connect.WithSchema(preferenceServiceMethods.ByName("ResetUserPreference")),
			connect.WithClientOptions(opts...),
		),
	}
}

// preferenceServiceClient implements PreferenceServiceClient.
type preferenceServiceClient struct {
	getUserPreference    *connect.Client[v1.GetUserPreferenceRequest, v1.GetUserPreferenceResponse]
	updateUserPreference *connect.Client[v1.UpdateUserPreferenceRequest, v1.UpdateUserPreferenceResponse]
	resetUserPreference  *connect.Client[v1.ResetUserPreferenceRequest, v1.ResetUserPreferenceResponse]
}

// GetUserPreference calls rpc.v1.PreferenceService.GetUserPreference.
func (c *preferenceServiceClient) GetUserPreference(ctx context.Context, req *connect.Request[v1.GetUserPreferenceRequest]) (*connect.Response[v1.GetUserPreferenceResponse], error) {
	return c.getUserPreference.CallUnary(ctx, req)
}

// UpdateUserPreference calls rpc.v1.PreferenceService.UpdateUserPreference.
func (c *preferenceServiceClient) UpdateUserPreference(ctx context.Context, req *connect.Request[v1.UpdateUserPreferenceRequest]) (*connect.Response[v1.UpdateUserPreferenceResponse], error) {
	return c.updateUserPreference.CallUnary(ctx, req)
}

// ResetUserPreference calls rpc.v1.PreferenceService.ResetUserPreference.
func (c *preferenceServiceClient) ResetUserPreference(ctx context.Context, req *connect.Request[v1.ResetUserPreferenceRequest]) (*connect.Response[v1.ResetUserPreferenceResponse], error) {
	return c.resetUserPreference.CallUnary(ctx, req)
}

// PreferenceServiceHandler is an implementation of the rpc.v1.PreferenceService service.
type PreferenceServiceHandler interface {
	// GetUserPreference retrieves the current user's preference settings.
	// Returns default values if no preference record exists.
	GetUserPreference(context.Context, *connect.Request[v1.GetUserPreferenceRequest]) (*connect.Response[v1.GetUserPreferenceResponse], error)
	// UpdateUserPreference updates the current user's preference settings.
	// Creates a new preference record if none exists (upsert behavior).
	UpdateUserPreference(context.Context, *connect.Request[v1.UpdateUserPreferenceRequest]) (*connect.Response[v1.UpdateUserPreferenceResponse], error)
	// ResetUserPreference deletes the current user's preference record,
	// causing the system to revert to default values and OS preferences.
	ResetUserPreference(context.Context, *connect.Request[v1.ResetUserPreferenceRequest]) (*connect.Response[v1.ResetUserPreferenceResponse], error)
}

// NewPreferenceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPreferenceServiceHandler(svc PreferenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	preferenceServiceMethods := v1.File_rpc_v1_preference_proto.Services().ByName("PreferenceService").Methods()
	preferenceServiceGetUserPreferenceHandler := connect.NewUnaryHandler(
		PreferenceServiceGetUserPreferenceProcedure,
		svc.GetUserPreference,
		connect.WithSchema(preferenceServiceMethods.ByName("GetUserPreference")),
		connect.WithHandlerOptions(opts...),
	)
	preferenceServiceUpdateUserPreferenceHandler := connect.NewUnaryHandler(
		PreferenceServiceUpdateUserPreferenceProcedure,
		svc.UpdateUserPreference,
		connect.WithSchema(preferenceServiceMethods.ByName("UpdateUserPreference")),
		connect.WithHandlerOptions(opts...),
	)
	preferenceServiceResetUserPreferenceHandler := connect.NewUnaryHandler(
		PreferenceServiceResetUserPreferenceProcedure,
		svc.ResetUserPreference,
		connect.WithSchema(preferenceServiceMethods.ByName("ResetUserPreference")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.v1.PreferenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PreferenceServiceGetUserPreferenceProcedure:
			preferenceServiceGetUserPreferenceHandler.ServeHTTP(w, r)
		case PreferenceServiceUpdateUserPreferenceProcedure:
			preferenceServiceUpdateUserPreferenceHandler.ServeHTTP(w, r)
		case PreferenceServiceResetUserPreferenceProcedure:
			preferenceServiceResetUserPreferenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPreferenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPreferenceServiceHandler struct{}

func (UnimplementedPreferenceServiceHandler) GetUserPreference(context.Context, *connect.Request[v1.GetUserPreferenceRequest]) (*connect.Response[v1.GetUserPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.PreferenceService.GetUserPreference is not implemented"))
}

func (UnimplementedPreferenceServiceHandler) UpdateUserPreference(context.Context, *connect.Request[v1.UpdateUserPreferenceRequest]) (*connect.Response[v1.UpdateUserPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.PreferenceService.UpdateUserPreference is not implemented"))
}

func (UnimplementedPreferenceServiceHandler) ResetUserPreference(context.Context, *connect.Request[v1.ResetUserPreferenceRequest]) (*connect.Response[v1.ResetUserPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.PreferenceService.ResetUserPreference is not implemented"))
}
